### ISSUE TITLE
Service request: Radio Paradise

### ISSUE THREAD

**Issue by beerslayer** [tiliado/nuvolaruntime#143]
http://www.radioparadise.com

Should be a simple one, I hope - only one channel and a wide variety of streams available.
##

**Comment by fenryxo** [comment]
Hello @beerslayer. Thanks for your idea. I would love to add as many streaming services as possible. However, development of Nuvola Player is limited by project funding. I usually work on [features requested by Nuvola Patrons](https://github.com/tiliado/nuvolaplayer/labels/patron) first and other feature request are [postponed to be implemented later](https://github.com/tiliado/nuvolaplayer/labels/postponed). Would you like to [become a Nuvola Patron](https://tiliado.eu/nuvolaplayer/funding/#donate) by supporting the project financially?

**Comment by fenryxo** [comment]
I'm moving this feature request to postponed tasks as I haven't received any response for a month.

**Comment by fenryxo** [comment]
Hello @beerslayer. Do you still use Nuvola and are you interested in having Radio Paradise supported by Nuvola? Thanks.
