### ISSUE TITLE
Service request: Mentor FM

### ISSUE THREAD

**Issue by ChrisBeeley** [tiliado/nuvolaruntime#151]
This is one of the best radio streamers I've ever used, recommendation-wise. It would be good to have it in Nuvola.

http://mentor.fm
##

**Comment by fenryxo** [comment]
Hello. Thanks for your service request. I've added tag Patron to raise its priority ;-)

**Comment by fenryxo** [comment]
[Fixed in Nuvola 4.14](https://medium.com/nuvola-news/nuvola-4-14-released-533f1677ab5b)
