### ISSUE TITLE
Progress indication while loading the Google Play Music page

### ISSUE THREAD

**Issue by alekstar** [tiliado/nuvolaruntime#229]
While I start the Google Play Music (using Nuvola Player interface), I see the blank page for some time (10 seconds and more sometimes) without any indication of working. After that, I see, that Google Play Music have been opened and then I see the loading page of this service.

I think it would be great to add some indication of loading the page of the Google Play Music (maybe other services have the same problem).

I'm using Ubuntu 16.04, Nuvola Player 3.02 and Google Play Music 5.13.
##

**Comment by alekstar** [comment]
Sometimes the black page is shown for a very long time when launching the application and user can think, that the Nuvola Player (its part, that is called "Google Play Music") does nothing or freeze. That's why I created the #228. I thought, that the player does nothing, but it seems to load the Google Play Music page and nothing indicates about it.

**Comment by fenryxo** [comment]
Hello @alekstar. Thanks for your feature request. Would you be interested in sponsoring its development?

**Comment by fenryxo** [comment]
Will be released in Nuvola 4.9.
