### ISSUE TITLE
Can't restore from tray (Plasma 5.8.2, X)

### ISSUE THREAD

**Issue by Evpok** [tiliado/nuvolaruntime#261]
With the "play in background on close" setting, closing the player does put it in the system tray, but it can't be restored from there, which is pretty counter-intuitive. Related to — but, I believe, not duplicate of — issue #89

**Comment by fenryxo** [comment]
Hello @Evpok. Thanks for taking the time to report your issue. I need more information to investigate it further:

* Which distribution and version do you use?
* Which [version of Nuvola player](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#your-nuvola-player-instance) do you use?
* The debugging output from a terminal as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output), especially before and after you click the tray icon.

**Comment by Evpok** [comment]
Hello @fenryxo and thanks for your interest:

  - **Distro** KDE Neon (dev stable) over Ubuntu 16.10
  - **DE** plasmashell over kwin_x11 (v5.8.2 both)
  - **Nuvola player**

    ```
   Nuvola Player 3 3.0.4
   Revision bb4fdef51d50a620d739687eec9eb67dd6033da5
   WebKitGTK 2.14.1
   libsoup 2.54.1
   ```

See [debug output](https://gist.github.com/Evpok/08764d8b15f90d424c4c9acd1d521f6f) for
  - Run `nuvolaplayer3 --debug`
  - Launch deezer
  - Start playing the current playlist
  - Close the player window
  - Click on the systray icon (nothing happens))

**Comment by fenryxo** [comment]
Thanks @Evpok. I need to look at it closer on my own. However, since Nuvola Player doesn't officially support KDE (only Unity and GNOME at the moment), this is a low priority task and I'm not sure when I get around to it.

**Comment by fenryxo** [comment]
Hello @Evpok. Is this issue stil valid in Nuvola 4.7?

**Comment by Evpok** [comment]
Hey, as far as I can tell, the tray icon is a Premium-only feature in 4.7 and I have only got a Basic account so I can't help you there :)

**Comment by fenryxo** [comment]
@Evpok, you have been granted a Tiliado developer account for two months. Could you check the issue? Thanks :-) You may need to refresh account details in Nuvola before that though.

**Comment by Evpok** [comment]
It seems to work now ! Thanks for your dedication :)

**Comment by fenryxo** [comment]
Great. Closing 👍
