### ISSUE TITLE
Detect and warn about OpenGL/VA-API/VDPAU driver errors

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaruntime#280]
**Hello :-) Chances are that you have been redirected to this ticket by Start-Up Check Dialog (picture bellow). In that case, please leave a comment with the name of the missing driver from the dialog (e.g. `r600` in the picture bellow) and the name of your graphics card. Thank you.**

![statup-check-dialog](https://user-images.githubusercontent.com/853706/28508971-03e3bb56-703f-11e7-98ea-b9ecff30be32.png)

---

Developer notes:

* [Info about r600](https://bbs.archlinux.org/viewtopic.php?pid=1300701#p1300701)
* [libva homepage](https://www.freedesktop.org/wiki/Software/vaapi/)
* [libva API](https://cgit.freedesktop.org/libva/tree/va/va.h)

tiliado/nuvolaplayer#278:

```
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
```

https://github.com/tiliado/nuvolaplayer/issues/224#issuecomment-223895704:

```
Failed to open VDPAU backend libvdpau_va_gl.so: nem nyitható meg a megosztott objektumfájl: Nincs ilyen fájl vagy könyvtár
Translation:
Failed to open VDPAU backend libvdpau_va_gl.so: can not open shared object file: No such file or directory
```

https://github.com/tiliado/nuvola-app-spotify/issues/11
```
Failed to open VDPAU backend libvdpau_va_gl.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
```

tiliado/nuvolaruntime#342

```
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```
```
Failed to open VDPAU backend libvdpau_i965.so: cannot open shared object file: No such file or directory
```

Links

* https://github.com/anholt/libepoxy
* https://github.com/01org/libva
* https://stackoverflow.com/questions/24708231/how-to-find-my-opengl-verion-in-linuxubuntu-14-04/24708482#24708482

**Comment by steevsachs** [comment]
Getting the warning for VA-API Driver 'radeonsi' not found

**Comment by fenryxo** [comment]
Hello @steevsachs. Thanks for your report. I'll take a look at it at the weekend.

**Comment by fenryxo** [comment]
urschuca from Patreon: Fedora 26: `VA-API driver and VDPAU driver : Failed to get DRI2 driver name. DRI2QueryExtension failed, 0, 0`.

**Comment by urschuca** [comment]
![dri2query](https://user-images.githubusercontent.com/17567850/28916078-4d09661e-7841-11e7-9544-898a097fa945.png)

**Comment by fenryxo** [comment]
@urschuca Regarding to the first error "Failed to connect to Nuvola Apps Service" - if it keeps popping, please try to reboot your computer. It it won't help, please [create a new ticket for it](https://github.com/tiliado/nuvolaruntime/issues/new).

**Comment by fenryxo** [comment]
@steevsachs and @urschuca, could you run `flatpak update && flatpak update --user` and check whether your issue is still reproducible with Nuvola 4.6.6?

**Comment by steevsachs** [comment]
I can no longer reproduce on 4.6.6.  Thank you!

**Comment by fenryxo** [comment]
No error for a month. I'm closing this issue but anybody can still comment to reopen it when an issue appears.

**Comment by regisz** [comment]
![image](https://user-images.githubusercontent.com/5145946/31373749-85481284-ad9b-11e7-907b-0d159ae93798.png)

I got this warning.

**Comment by fenryxo** [comment]
Hello @regisz. Could you check again with Nuvola 4.8.18? If the issue is still present, please provide me with [a debugging output](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#debugging-output) to investigate it further. Thank.

Also, if you see broken fonts, take a look at #388.

**Comment by regisz** [comment]
Unfortunately, the problem is still present.

```
$ flatpak run eu.tiliado.NuvolaAppGooglePlayMusic --version
Google Play Music script 6.0
Maintainer: Jiří Janoušek

--- Powered by ---

Nuvola Apps - Genuine flatpak build
Version 4.8.18
Revision 18-g3e3ee74
Diorite 4.8.6
WebKitGTK 2.18.0
libsoup 2.58.2
```
```
$ flatpak run eu.tiliado.NuvolaAppGooglePlayMusic -v -D
Runner: [DEBUG Δ021689us <unknown>] launch_app.vala:74: App data dir: /app/share/nuvolaruntime/web_apps/google_play_music
Runner: [DEBUG Δ046516us DioriteGtk] DesktopShell.vala:152: Shell: xfwm4 (null), CSD 0, appmenu 0, menubar 0
Runner: [DEBUG Δ116171us Nuvola] FormatSupport.vala:95: Trying to play /app/share/nuvolaruntime/audio/audiotest.mp3.
Runner: [DEBUG Δ001601us DioriteGtk] Application.vala:241: XFCE session appeared: org.xfce.SessionManager, :1.17
Runner: [DEBUG Δ028188us Nuvola] FormatSupport.vala:95: Pipeline state changed from NULL to READY.
Runner: [DEBUG Δ003020us Nuvola] FormatSupport.vala:95: Pipeline state changed from READY to PAUSED.
Runner: [DEBUG Δ001446us Nuvola] FormatSupport.vala:95: Pipeline state changed from PAUSED to PLAYING.
Runner: [DEBUG Δ000109us Nuvola] FormatSupport.vala:95: End of stream for file /app/share/nuvolaruntime/audio/audiotest.mp3.
Runner: [DEBUG Δ004457us Nuvola] Graphics.vala:101: DRI 1.3; driver i965
Runner: [DEBUG Δ000282us Nuvola] Graphics.vala:149: i965: VDPAU driver paths: /usr/lib/vdpau/libvdpau_i965.so
Runner: [WARNING Δ000356us Nuvola] StartupWindow.vala:183: vdpau-driver-message: VDPAU Driver for 'i965' not found. Rendering performance of some web apps may suffer. Please <a href="https://github.com/tiliado/nuvolaruntime/issues/280">report your issue</a> so that the driver can be added to Nuvola Runtime flatpak.
Runner: [DEBUG Δ000109us Nuvola] Graphics.vala:171: VA-API driver found: /app/lib/dri/i965_drv_video.so
Runner: [DEBUG Δ001618us Nuvola] Traits.vala:135: Feature[flash] -> false 
Runner: [DEBUG Δ000071us Nuvola] Traits.vala:135: Codec[mp3] -> false 
Runner: [DEBUG Δ000061us Nuvola] Traits.vala:135: WebKitGTK[2.16.3] -> true 
Runner: [DEBUG Δ000048us Nuvola] StartupCheck.vala:213: Nuvola.WebPlugin: Shockwave Flash (enabled, flash) at /app/lib/flash/libflashplayer.so: Shockwave Flash 26.0 r0
Runner: [DEBUG Δ000033us Nuvola] StartupCheck.vala:234: MSE supported: yes
Runner: [DEBUG Δ000089us Nuvola] WebApp.vala:299: Requirements expression: 'Feature[flash] Codec[mp3] WebKitGTK[2.16.3]'
Runner: [DEBUG Δ000061us Nuvola] Traits.vala:135: Feature[flash] -> true 
Runner: [DEBUG Δ000043us Nuvola] Traits.vala:135: Codec[mp3] -> true 
Runner: [DEBUG Δ000044us Nuvola] Traits.vala:135: WebKitGTK[2.16.3] -> true 
Runner: [DEBUG Δ000033us Nuvola] WebApp.vala:301: Requirements expression: 'Feature[flash] Codec[mp3] WebKitGTK[2.16.3]' -> true; (null)
Runner: [WARNING Δ233230us Nuvola] StartupWindow.vala:183: tiliado-account-message: Tiliado account: Balázs
Runner: [DEBUG Δ04s799528us DioriteGlib] DuplexChannel.vala:551: Channel (1) has been closed.
Runner: [DEBUG Δ000103us DioriteGlib] DuplexChannel.vala:338: The channel has already been closed
```

**Comment by fenryxo** [comment]
> `Graphics.vala:149: i965: VDPAU driver paths: /usr/lib/vdpau/libvdpau_i965.so`

Nuvola seems to ignore `/app/lib` directory. What does `flatpak run --command=env eu.tiliado.NuvolaAppGooglePlayMusic` show? If it contains any sensitive information, you can strip it.

**Comment by regisz** [comment]
[NuvolaAppGooglePlayMusic-Env.log](https://github.com/tiliado/nuvolaruntime/files/1378664/NuvolaAppGooglePlayMusic-Env.log)

**Comment by fenryxo** [comment]
Indeed, the latest version of Flatpak does not set `LD_LIBRARY_PATH` (flatpak/flatpak#1073).

**Comment by fenryxo** [comment]
Hello @regisz. Could you check again with Nuvola 4.8.19?

**Comment by regisz** [comment]
Ok, it is fixed :+1: 
Thx :)!

**Comment by fenryxo** [comment]
Great :-)

**Comment by fenryxo** [comment]
From https://www.patreon.com/posts/15088225:

> Hello, I'm having this problem in Arch Linux + Gnome 3.26 + Wayland + Nvidia propietary drivers. I want to know if I am missing something. Deezer works fine but I get this warning everytime before launching it.

![img](https://c10.patreonusercontent.com/3/eyJ3IjoxNjAwfQ%3D%3D/patreon-posts/037C9igfiXNmRPVwn61kTwOZ_u2tpycbW61MzHq2bHo1BV6j8Mk5mc5XJtp0Xbj6.png?token-time=2145916800&token-hash=0HA2MLEHImYLWfClfRiQoSybCE2VqTIFu9u1gzQwegg%3D)

**Comment by fenryxo** [comment]
Is the issue still reproducible with Nuvola 4.8.27?
