### ISSUE TITLE
Support KDE Desktop Environment

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaruntime#289]
Distro: OpenSUSE

**Comment by DJViking** [comment]
Currently I am running KDE Plasma 5.9 and installed nuvolaplayer from the OpenSUSE repository. However starting the player I got segmentation fault (core dumped).

**Comment by fenryxo** [comment]
Hello @DJViking. This ticket is about the process of supporting KDE. Please create a new ticket for your issue (with a title "Segmentation fault with KDE Plasma 5.9/OpenSUSE") and add required information from [Bug reporting guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines).

**Comment by fenryxo** [comment]
Better not to use server-side window decorations by default tiliado/nuvolaruntime#486
![suse_ssd_active](https://user-images.githubusercontent.com/853706/49341427-7de6ea00-f64d-11e8-8386-ee64a17dbdd9.png)

**Comment by fenryxo** [comment]
We support KDE for a while...

**Comment by thibaultmol** [comment]
I feel like people (including me) who use KDE Plasma feel left out, because (from your website) it doesn't exactly look like you 'properly' support plasma https://nuvola.tiliado.eu/docs/4/

**Comment by fenryxo** [comment]
Hello @thibaultmol, thanks for your feedback. I've created a new issue for that: #729.
