### ISSUE TITLE
Clean Flatpaks

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaruntime#311]
- Remove unnecessary files in both stable and master flatpaks.
- Optimize CEF to take less space  - reticketed as tiliado/valacef#9
- Remove icon & GTK+ themes - reticketed as: #403

**Comment by fenryxo** [comment]
From [a mailing list](https://groups.google.com/d/msg/nuvola-player-users/fEDzr59AuFc/uy0Dc9UMBAAJ)

> I'm wondering why the flatpak build of Nuvola with GPM takes up such an insane amount of space. 
>
> Ref                                               Installed size 
> eu.tiliado.Nuvola/x86_64/stable                   293.5 MB 
> eu.tiliado.NuvolaAppGooglePlayMusic/x86_64/stable 408.7 MB 
> org.gnome.Platform.Locale/x86_64/3.26             512 bytes 
> org.gnome.Platform/x86_64/3.26                    782.3 MB 
> 
> Okay, I get the Gnome runtime is huge, but 700 MiB for a web wrapper?  I also have Revolt, another web wrapper written in Python, that is only 700 KiB...an entire order of magnitude smaller! 
> 
> The GPM package also seems to contain runtime files—why?  I see lots of header files, Python, WebkitGTK, etc. along with what appears to be another copy of the Nuvola runtime.  Are both packages even required?  Both packages also include all kinds of unrelated icons and translation files. 
> 
> Since Nuvola 3.x has been EOL'd, I would highly suggest prioritizing a fix for this with the upcoming Chromium release. 

My response:

First of all, Nuvola depends on ostree deduplication feature. All files that are same are downloaded only once and exist on the disk only in a single copy. I believe ostree uses hard links for that. Taking this into account, the real overhead of eu.tiliado.NuvolaAppGooglePlayMusic *stable* flatpak is roughly 408.7 MB - 293.5 MB = 115.2 MB. 

It is true that the size of the *stable* Flatpaks is still not optimal. That's because I haven't paid enough attention to that issue. However, upcoming Nuvola 4.10 will change that: flatpaks were carefully trimmed, and any new file must be explicitly whitelisted, or the build fails. This should prevent the accidental growth of the size as it happened with the current stable builds. 

You can look at the *master* branch. NuvolaCDK (540.1 MB) is the base flatpak with a complete build environment. Nuvola, NuvolaAppDeezer, and NuvolaAppGooglePlayMusic have almost the same size (363.1 MB), and almost all files are shared & deduplicated. 

eu.tiliado.Nuvola/x86_64/master 363.1 MB 
eu.tiliado.NuvolaAppDeezer/x86_64/master 363.1 MB 
eu.tiliado.NuvolaAppGooglePlayMusic/x86_64/master 363.1 MB 
eu.tiliado.NuvolaCdk/x86_64/master 540.1 MB 

Now let's discuss the size (363.1 MB): 
- Chromium Embedded Framework: cca 200 MB - not sure whether this can be reduced. Honestly, I'm glad I've managed to build this beast. I need to investigate possible optimizations. 
- Icons & themes: cca 120 MB - Nuvola currently bundles a lot of icon & GTK+ themes to look great regardless whether a user uses GNOME/Unity/Elementary/.... However, this was introduced when Flatpak didn't support GTK+ theme extensions and Nuvola should be ported to that instead of bundling. This would require a mechanism to detect whether the user's GTK+ theme has a corresponding GTK+ theme flatpak extension installed and provide them with installation instructions otherwise. The development has already started, but it is unlikely to land before the Chromium port is finished. 
- Nuvola and its runtime dependencies: cca 40 MB - not bad 

> Okay, I get the Gnome runtime is huge, but 700 MiB for a web wrapper? I also have Revolt, another web wrapper written in Python, that is only 700 KiB...an entire order of magnitude smaller! 

Well, that is not 700 MiB (stable) / 360 MiB (master) for a web wrapper, but for the web wrapper, runtime dependencies and temporary integration hacks(icons and GTK+ themes). Nuvola itself has only 400 KiB. Does that 700 KiB include also runtime dependencies? 

> The GPM package also seems to contain runtime files—why? I see lots of header files, Python, WebkitGTK, etc. along with what appears to be another copy of the Nuvola runtime. 

Because it needs the runtime files to run :-) The NuvolaAppGooglePlayMusic flatpak does not have access to the files from the Nuvola flatpak. I believe header files and Python no longer exist in the master flatpaks. 

> Both packages also include all kinds of unrelated icons and translation files. 

The issue with icons has been addressed above; unrelated translation files no longer exist in the master flatpaks. 

> Are both packages even required? 

The Nuvola flatpak provides global services to the individual web app flatpaks, e.g. global keyboard shortcuts, media keys handling, HTTP remote control, command line controller, global configuration (e.g. Last.fm token). There is an unfinished effort to make individual web app flatpaks independent of the Nuvola service and disable the features when the service is not available. Currently, the experimental build disables these features at build time and the goal is to make it happen at runtime. 

> I'm wondering why the flatpak build of Nuvola with GPM takes up such an insane amount of space. 
> 
> Since Nuvola 3.x has been EOL'd, I would highly suggest prioritizing a fix for this with the upcoming Chromium release. 

As you can see, there is some progress regarding this. The disk usage of the master branch (360 MiB, upcoming Nuvola 4.10) is not insane but reasonable and will be improved further. As a side note, the size of an uncompressed Nuvola/Deezer snap package it 1.4 GB before optimizations, so there is even more work to do. 

I hope I've addressed all your questions. If not, please ask again. Feedback is always welcome. If you have some tips how to reduce the master flatpaks even more, I'd like to hear them :-)

**Comment by DidierLoiseau** [comment]
I just removed Nuvola because of its disk space usage :frowning_face:. I am not using it that much but I am on a system with limited resources and I have to free some space for the Ubuntu 20.10 upgrade.
```
$ sudo flatpak uninstall nuvola
Found installed ref ‘app/eu.tiliado.Nuvola/x86_64/stable’ (system). Is this correct? [Y/n]: 


        ID                      Branch       Op
 1. [-] eu.tiliado.Nuvola       stable       r

Uninstall complete.
$ sudo flatpak uninstall --unused


        ID                                            Branch          Op
 1. [-] org.freedesktop.Platform.GL.default           19.08           r
 2. [-] org.freedesktop.Platform.VAAPI.Intel          19.08           r
 3. [-] org.freedesktop.Platform.openh264             2.0             r
 4. [-] org.gnome.Platform                            3.34            r
 5. [-] org.gnome.Platform.Locale                     3.34            r
 6. [-] org.gtk.Gtk3theme.Ambiance                    3.22            r

Uninstall complete.
```
This freed up about 1.5GiB.

**Comment by fenryxo** [comment]
Sure, if you have limited disk space, there is no point using Flatpaks nor Snaps.
