### ISSUE TITLE
Remembering song Position in Google Play Music

### ISSUE THREAD

**Issue by fur0n** [tiliado/nuvolaruntime#316]
Being able to save the position I am at in Google Play Music when the app is closed, even if it just picked up which song I was on, even if it couldn't find exactly where I was at in the song, would still be nice.

This is my feature request.

**Comment by fenryxo** [comment]
Hello @fur0n. Thanks for your feature request. I'm not sure whether it sis possible but I'll give it a try.

Note to self: [An article about Epiphany 3.20](https://blogs.gnome.org/mcatanzaro/2016/03/30/epiphany-3-20/) mentions improved session restoration in WebKitGTK.

**Comment by fenryxo** [comment]
Hello @fur0n. With Nuvola 3.1.3 out, I have finally some time to look at this. Unfortunately, I [cannot sign in to Google Play Music right now](https://bugs.webkit.org/show_bug.cgi?id=171770). I hope it gets resolved soon.

**Comment by fenryxo** [comment]
Google Play Music is EOL  #660.
