### ISSUE TITLE
Unbundle engine.io.js

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaruntime#341]
Nuvola bundles engine.io.js library. It would be better to have it as a dependency. However, I have no idea what is the typical filesystem location for JavaScript libraries.

**Comment by martinkg** [comment]
for Fedora is it %{_datadir}/javascript or the RPM Macro %{_jsdir}
https://fedoraproject.org/wiki/Packaging:JavaScript#RPM_Macros

**Comment by voxik** [comment]
@fenryxo I don't think there is necessarily any action required on the upstream side. If we decide to unbundle in Fedora (the unbundling requirements are not that strict as they used  to be anymore), it would be enough to provide symlink from the system location to the place where Nuvola expect the file to be.

But what would be helpful is to understand the workflow you are using for updating, e.g. if there was something like "make update-engineiojs" and we should understand the engine.io.js lifecycle and backward compatibility.

But thx for considering.

**Comment by fenryxo** [comment]
It's better to have engine.io.js as a separate module in flatpak-builder manifest rather than as a bundled copy.

- [ ] Add [engine.io-client](https://github.com/socketio/engine.io-client) to flatpak builds
- [ ] Add version of engine.io to README.md
- [ ] Add `--jsdir` to wscript (defaults to `${datadir}/javascript`)
- [ ] Replace `engine.io.js` with a symlink created during `waf install` pointing to  `${jsdir}/engine.io-client/engine.io.js` (`/usr/share/javascript/engine.io-client/engine.io.js`) 
- [ ] Add check that the symlink is valid
