### ISSUE TITLE
User agent for Nuvola Player is incompatible with Groove Music

### ISSUE THREAD

**Issue by jonseppanen** [tiliado/nuvolaruntime#344]
Groove music does extensive user agent checking in order to load the right kind of audio for the capabilities of the browser.
Unfortunately, it can't 'see' the epiphany browser as compatible.

I have tried updating the user agent for the plugin in JS but the detection is happening beforehand or in some other way.

I suggest modifying the electron user agent for Nuvola to be chrome based so that these kind of 'special' checks can be bypassed.

**Comment by fenryxo** [comment]
Hello @jonseppanen. Thanks for taking the time to report this issue. [The maintainer of the Groove script seems to be aware of this issue and be working on it.](https://groups.google.com/d/msg/nuvola-player-devel/yrvqUpWFvOQ/yDI6PK5tAwAJ)

**Comment by fenryxo** [comment]
Closing in favour of tiliado/nuvola-app-groove#6
