### ISSUE TITLE
Service Request: NPR One

### ISSUE THREAD

**Issue by dericke** [tiliado/nuvolaruntime#345]
- http://one.npr.org/
- I'm a Nuvola Patron with username ederickson

**Comment by fenryxo** [comment]
Hello @dericke. Thanks for your feature request. I have attached it to the Service Backlog milestone. These services has higher priority.

**Comment by fenryxo** [comment]
WIP: https://github.com/tiliado/nuvola-app-npr-one

**Comment by fenryxo** [comment]
* Published but not announced yet.
* [Flatpak package](https://nuvola.tiliado.eu/app/npr_one/)
* [Source code](https://github.com/tiliado/nuvola-app-npr-one)
