### ISSUE TITLE
failed to find dioriteglib4 but diorite4 from your links installed

### ISSUE THREAD

**Issue by jerome-diver** [tiliado/nuvolaruntime#352]
i installed diorite, then try to link /usr/local/lib libdiorite* /usr/lib and /lib
(not work)
then i remove links and try to copy
(not work)
then i try to indicate --libdir flag (try with /usr/local/lib, /usr/lib, with copy or linked diorite libs...)  at nuvolaruntime config time
(not work)
then question is:
-how to link diorite installed (from your own git repo) libraries with this libruntime to be able to configure than compil/install ? actualy, dioriteglib4 dependency failed after install diorite and after try with copy and/or link diorite libs provide by your diorite git repo. what i forget/not understand ?

**Comment by fenryxo** [comment]
Hello @jerome-diver 

> i installed diorite, then try to link /usr/local/lib libdiorite* /usr/lib and /lib
(not work)
then i remove links and try to copy
(not work)

Are you sure this is the typical/recommended way in your distribution? It isn't in Debian, for example.

> then i try to indicate --libdir flag

This option indicates where to install Nuvola's libs, not where to look for dependencies.

Anyway, the installation of Diorite & Nuvola from git under /usr/local prefix should be as simple as running `./waf configure; ./waf build; sudo ./waf install; sudo ldconfig`. It works out of the box in Debian, for example. However, you system my require additional options for that and you are supposed to know them. If you don't know them, you have at least three options

1. You can use the genuine flatpak builds of Nuvola Apps.
2. You can ask other users of your distribution to assist you. In a forum or mailing list, for example.
3. I could find out all necessary information and provide you with detailed instructions for you system. However, that's far beyond free support. If you are interested in paid support, you can contact me at support@tiliado.com for a price quote.

**Comment by jerome-diver** [comment]
thank you for your answer,
i arrived to install from flatpak, but by this way, i should paid a rent for be able to use this player (imagine... paid a rent, not for content, but for a content player... crazy no ?).
I'm on archlinux and i clone git repos inside my own user directory, i think at install time (after compile then) it should put files where ever it needs. But ok, i will try to clone inside /usr/local directly instead.
I will ask the archlinux community to help then...
I will not paid for install this player and i tell you why:
this player is usefull for read deezer or other streamers (who are already not free, but offer some contents, and not just a web UI), so i think it would be logic (but not automatic) that these contents provider will paid you a rent for people can use a sofware for access there contents. But that is my opinion. I will not win monnaie for use this player (if make monnaie with this player, sure, i will buy it, not sure by paid a life rent...) to.
Anyway, i hope some people happy to paid rents here and other place for everything and you will win your life by this way.
good luck

**Comment by jerome-diver** [comment]
@fenryxo 

> Anyway, the installation of Diorite & Nuvola from git under /usr/local prefix should be as simple as running ./waf configure; ./waf build; sudo ./waf install; sudo ldconfig. It works out of the box in Debian

So the correct sentence is: Anyway, in Debian like OS, the installation of Diorite & Nuvola from git under /usr/local prefix should be as simple as running ./waf configure; ./waf build; sudo ./waf install; sudo ldconfig, but maybe not on other distributions. Because on archlinux/antergos, it is not as simple as that in the real fact.

1 use flatpack builds is easy... but expensive for paid two times... one time for the soft (and a rent... not a one time paid...) and rent for content music on deezer... crazy, isn't it ? So definitly not a reasonable way.
2 yes, that should be the way, and after, i will go back here for share for other one like me
3 yes, i understand the idea... no, thank you, i will paid for something who make me win something to.
