### ISSUE TITLE
libdri2 dependency is problematic

### ISSUE THREAD

**Issue by voxik** [tiliado/nuvolaruntime#355]
It seems that nuvolaruntime depends on libdri2 since these two commits https://github.com/tiliado/nuvolaruntime/commit/9e2e039f72fd5ff576a15b5d4dc67275624aadd3, https://github.com/tiliado/nuvolaruntime/commit/3f60b35fc365a1052ff2951249a3af612a66b569. However, this dependency is a bit unfortunate, since libdri2 is not available in Fedora yet. I was wondering why so and this was answer from @robclark, the libdri2 developer:

> The whole libdri2 thing never really caught on. if something really depends on this, I'd suggest just copying the needed code into whatever is using it.

Is there a chance to avoid the dependnecy on libdri2? Isn't similar functionality you are using in the above reference commits available directly in Mesa?

**Comment by fenryxo** [comment]
> I'd suggest just copying the needed code into whatever is using it.

You can bundle libdri2 downstream and build it before Nuvola.

> Is there a chance to avoid the dependency on libdri2?

You can revert the commits you have mentioned.

> Isn't similar functionality you are using in the above reference commits available directly in Mesa?

If I recall correctly, the code which is in libdri2 is available in mesa but is not public i.e. not available in public C header files and cannot be used by third-party code.

**Comment by voxik** [comment]
>> Is there a chance to avoid the dependency on libdri2?
>
> You can revert the commits you have mentioned.

Yes, this is probably the most reasonable approach ATM. I suggested this already to @martinkg, since we try to avoid bundling in Fedora. It would be more reasonable to package the libdri2 in this case.

>>  Isn't similar functionality you are using in the above reference commits available directly in Mesa?
> 
> If I recall correctly, the code which is in libdri2 is available in mesa but is not public i.e. not available in public C header files and cannot be used by third-party code.

😭

**Comment by fenryxo** [comment]
Anyway, I'm closing this ticket as it's a downstream issue.
