### ISSUE TITLE
Duration/track position greater than 35 minutes broken.

### ISSUE THREAD

**Issue by a-m-s** [tiliado/nuvolaruntime#358]
If track duration or track position is greater than 35:47 then the number of microseconds exceeds a 32-bit signed integer and the time display goes wrong (typically is says "-35:-47").

**Comment by fenryxo** [comment]
Thanks for reporting this issue. I'll switch to int64.

**Comment by fenryxo** [comment]
Could you check that it has been fixed in the latest build?

**Comment by a-m-s** [comment]
All working now. :-)
