### ISSUE TITLE
3 3.0.9 got the path for Deezer and Google Play Music wrong

### ISSUE THREAD

**Issue by Evpok** [tiliado/nuvolaruntime#362]
## TL;DR

After the last update (Plasma DE, KDE Neon/Ubuntu 17.04 x86_64, using the stable Ubuntu repo). The main player doesn't have the Deezer and Google Play Music apps listed and is apparently looking for them in the wrong place.

## Steps to reproduce

1. Start `nuvolaplayer3`
2. The Deezer app is not listed
3. It should

## Packages versions

```
$ nuvolaplayer3 --version
Nuvola Player 3 3.0.9
Revision f79856a684ab9fbce31d814059a4fc20a51489c1
WebKitGTK 2.16.3
libsoup 2.56.0
```
```
$ aptitude show nuvolaplayer3-deezer           
Package: nuvolaplayer3-deezer            
Version: 2.7-1~zesty
```

## stderr

```
$ nuvolaplayer3
Master: [WARNING  Nuvola] WebAppRegistry.vala:165: Unable to load web app from /usr/share/nuvolaplayer3/web_apps/deezer: /usr/share/nuvolaplayer3/web_apps/deezer/metadata.json is not a file
Master: [WARNING  Nuvola] WebAppRegistry.vala:165: Unable to load web app from /usr/share/nuvolaplayer3/web_apps/google_play_music: /usr/share/nuvolaplayer3/web_apps/google_play_music/metadata.json is not a file
```

## More details

```
$ dpkg -L nuvolaplayer3-deezer  
 [snip]
/usr/share/nuvolaruntime
/usr/share/nuvolaruntime/web_apps
/usr/share/nuvolaruntime/web_apps/deezer
/usr/share/nuvolaruntime/web_apps/deezer/icons
/usr/share/nuvolaruntime/web_apps/deezer/icons/scalable.svg
/usr/share/nuvolaruntime/web_apps/deezer/icons/24.png
/usr/share/nuvolaruntime/web_apps/deezer/icons/16.png
/usr/share/nuvolaruntime/web_apps/deezer/icons/48.png
/usr/share/nuvolaruntime/web_apps/deezer/icons/32.png
/usr/share/nuvolaruntime/web_apps/deezer/icons/256.png
/usr/share/nuvolaruntime/web_apps/deezer/icons/128.png
/usr/share/nuvolaruntime/web_apps/deezer/icons/64.png
/usr/share/nuvolaruntime/web_apps/deezer/icons/22.png
/usr/share/nuvolaruntime/web_apps/deezer/CONTRIBUTING.md
/usr/share/nuvolaruntime/web_apps/deezer/LICENSE
/usr/share/nuvolaruntime/web_apps/deezer/README.md
/usr/share/nuvolaruntime/web_apps/deezer/CHANGELOG.md
/usr/share/nuvolaruntime/web_apps/deezer/integrate.js`
/usr/share/nuvolaruntime/web_apps/deezer/metadata.json
[snip]
/usr/share/nuvolaplayer3/web_apps/deezer
```

So the main player is apparently looking for Deezer in `/usr/share/nuvolaplayer3` while it is actually in `/usr/share/nuvolaruntime`. `/usr/share/nuvolaplayer3/web_apps/deezer/` exists but is empty.

**Comment by fenryxo** [comment]
Thanks @Evpok for reporting this issue. `/usr/share/nuvolaplayer3/web_apps/deezer/` should be a symlink to `/usr/share/nuvolaruntime/web_apps/deezer`. I need to find out what went wrong.

**Comment by Evpok** [comment]
With that information I `rmdir`-ed `/usr/share/nuvolaplayer3/web_apps/deezer/` and did a `aptitude reinstall nuvolaplayer3-deezer` and that fixed the issue.

**Comment by fenryxo** [comment]
Hm, so it seems that Debian packaging tools cannot replace a directory with a symlink. I'll change the symlink name (`deezer-symlink`) to workaround the issue.

**Comment by fenryxo** [comment]
@Evpok, could you test following?

* `apt remove nuvolaplayer3-deezer`
* `rm -f /usr/share/nuvolaplayer3/web_apps/deezer`
* `mkdir /usr/share/nuvolaplayer3/web_apps/deezer`
* `apt update`
* `apt install nuvolaplayer3-deezer`

**Comment by Evpok** [comment]
Same result as before

```
$ nuvolaplayer3
Master: [WARNING  Nuvola] WebAppRegistry.vala:165: Unable to load web app from /usr/share/nuvolaplayer3/web_apps/deezer: /usr/share/nuvolaplayer3/web_apps/deezer/metadata.json is not a file
$ file /usr/share/nuvolaplayer3/web_apps/deezer
/usr/share/nuvolaplayer3/web_apps/deezer: directory
```

**Comment by fenryxo** [comment]
And how about `ls -l /usr/share/nuvolaplayer3/web_apps/deezer-link`?

**Comment by fenryxo** [comment]
I mean when I run `nuvolaplayer3 -D` it shows `... Found web app Deezer at /usr/share/nuvolaplayer3/web_apps/deezer-link, version 2.7 ...` with `nuvolaplayer3-deezer 2.7-5`. Does that also work on your system? If yes, that `Unable to load web app from /usr/share/nuvolaplayer3/web_apps/deezer: /usr/share/nuvolaplayer3/web_apps/deezer/metadata.json is not a file` warning can be ignored.

**Comment by Evpok** [comment]
Oh yes, I forgot to check if the deezer app was in the launcher and it actually is. So it *is* working after all, sorry.
