### ISSUE TITLE
Code review: nuvola-app-jupiter-broadcasting

### ISSUE THREAD

**Issue by a-m-s** [tiliado/nuvolaruntime#366]
https://github.com/a-m-s/nuvola-app-jupiter-broadcasting/issues/1

It should integrate track info and player controls (inc. seek and volume), for both types of player used on that site.

BTW, this is the site for which I wanted to record played state. I've not yet implemented anything for that though.

**Comment by fenryxo** [comment]
🎉 Flatpak built 👍
