### ISSUE TITLE
allowed_uri ineffective

### ISSUE THREAD

**Issue by a-m-s** [tiliado/nuvolaruntime#367]
The "allowed_uri" option successfully causes external links to open in an external browser, but fails to prevent the link also opening within Nuvola.

The feature is broken in 4.6, but works with the exact same service integration files in 3.0.

**Comment by fenryxo** [comment]
It should be fixed now. Can you verify? Thanks.

**Comment by a-m-s** [comment]
Confirmed, thanks.
