### ISSUE TITLE
Port to Chromium Embedded Framework

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaruntime#372]
Primary Targets
--------------------

  * **Spotify** - it doesn't work with WebKit at all. Requires Widevine. tiliado/nuvolaruntime#374
  * **Google Play Music** - Flash-free playback doesn't work in WebKit. tiliado/nuvolaruntime#91
  * **Deezer** - Flash-free playback doesn't work in WebKit. tiliado/nuvola-app-deezer#12
  * **BBC iPlayer** - Requires MSE. Might work better with Chromium. tiliado/nuvola-app-bbc-iplayer#8
  * **Microsoft Groove** - Requires MSE. Might work better with Chromium. Discontinued? tiliado/nuvola-app-groove#8

Unresolved Issues
------------------------

* ~~Background playback: Nuvola quits when the window is closed.~~ Fixed in Nuvola 4.9.50.
* ~~Proxy settings: It is grabbed from the system and cannot be changed yet.~~
* ~~Clipboard: CEF cannot paste text from the system clipboard unless external message pump is disabled, but CPU usage is higher then  tiliado/valacef#2~~
* ~~Missing support for `web_app.allow_insecure_content` - it is used by only a single script.~~
* ~~Password manager does not work and may crash.~~ → #418 
* ~~Request filtering is not implemented.~~
* ~~Scripts depending on deprecated synchronous API calls need to be ported:~~
  - Amazon Cloud Player: `Nuvola._keyValueStorageSetDefaultValue`
* ~~Poor performance with NVidia GTX 1070 (driver 387.34)~~ - see tiliado/valacef#1

Testing
---------

* Users with Nuvola Premium/Patron account have been invited.
* Users with Nuvola Basic account will be invited later.

**Comment by fenryxo** [comment]
CEF is not compatible with GTK+ 3.22: cztomczak/cefcapi#9

**Comment by fenryxo** [comment]
Nether compatible:  3.20.9-1ubuntu2.1 (Ubuntu 16.10), 3.18.9-1ubuntu3.3 (Ubuntu 16.04).

**Comment by fenryxo** [comment]
- Neither compatible: 3.16.8 (Ubuntu 15:10)
- Compatible: 3.14.13 (Ubuntu 15.04)

**Comment by fenryxo** [comment]
* Neither compatible: 3.16.7, 3.16.0, 3.15.5, **3.15.2**
* Compatible: **3.15.1**, 3.15.0, 3.14.14
* Need to go through commits between 3.15.1 and 3.15.2

**Comment by fenryxo** [comment]
The first failing commit between 3.15.1 and 3.15.2 is GNOME/gtk@dae447728d

**Comment by fenryxo** [comment]
This works:

```C
GtkWidget* create_gtk_window(char* title, int width, int height) {
    printf("create_gtk_window\n");
    // Create window.
    GtkWidget* window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
    ...
    // GTK+ > 3.15.1 uses an X11 visual optimized for GTK+'s OpenGL stuff
    // since revid dae447728d: https://github.com/GNOME/gtk/commit/dae447728d
    // However, it breaks CEF: https://github.com/cztomczak/cefcapi/issues/9
    // Let's use the default X11 visual instead the GTK's blessed one.
    GdkScreen* screen = gdk_screen_get_default();
    GList* visuals = gdk_screen_list_visuals(screen);
    printf("n visuals: %u\n", g_list_length(visuals));
    GdkX11Screen* x11_screen = GDK_X11_SCREEN(screen);
    g_assert(x11_screen != NULL);
    Visual* default_xvisual = DefaultVisual(GDK_SCREEN_XDISPLAY(x11_screen),
        GDK_SCREEN_XNUMBER(x11_screen));
    GdkVisual* default_visual = NULL;
    int i = 0;
    while (visuals != NULL) {
	GdkVisual* visual = GDK_X11_VISUAL (visuals->data);
        if (default_xvisual->visualid == gdk_x11_visual_get_xvisual(
           GDK_X11_VISUAL (visuals->data))->visualid) {
           printf("Default visual %d\n", i);
           default_visual = visual;
        }
        i++;
        visuals = visuals->next;
    }
    gtk_widget_set_visual(GTK_WIDGET(window), default_visual);
    gtk_widget_show_all(window);
    return vbox;
}
```

**Comment by fenryxo** [comment]
Vala + GTK+ 3 bindings of CEF for Nuvola:
![cefium](https://user-images.githubusercontent.com/853706/33810582-bde29bfa-de06-11e7-9bc0-40188a1817e5.png)

Widevine DRM works (Spotify):
![cef_spotify](https://user-images.githubusercontent.com/853706/33810592-f4a32678-de06-11e7-8073-9dc9c04df9f7.png)

**Comment by fenryxo** [comment]
[Status of Chromium-based Port of Nuvola](https://medium.com/nuvola-news/nuvola-chromium-port-status-3b1648b29c77)

**Comment by fenryxo** [comment]
New issue: Poor performance with NVidia GTX 1070 (driver 387.34) - see tiliado/valacef#1

**Comment by bartlibert** [comment]
From my initial tests with Google Play Music (with a subscriptions), it seems at least as fast and smooth as the WebKit version on my system (if not smoother) and playing music works as expected. Developer toolbar also does wat is has to.

However, I noticed one big problem: any action in the "overflow menu" (3 dots) does not work, but only if it is called from that menu.

So for example, when pressing "Shuffle" as seen in the screenshot below, it works...
![screenshot from 2018-01-04 08-06-06](https://user-images.githubusercontent.com/948770/34553269-d23a88a0-f126-11e7-8031-abc56e0982fa.png)
... but when clicked here it does not (neither do any of the other options).
![screenshot from 2018-01-04 08-06-38](https://user-images.githubusercontent.com/948770/34553275-d68262ca-f126-11e7-87e4-f79bde21f068.png)

Same thing for example in the "recent activity" screen (screenshots are in Dutch, but I hope it's clear enough): The "play" button works, but the overflow actions don't.
![screenshot from 2018-01-04 08-07-11](https://user-images.githubusercontent.com/948770/34553303-f8076a1c-f126-11e7-9f8f-502eae154242.png)
![screenshot from 2018-01-04 08-07-23](https://user-images.githubusercontent.com/948770/34553305-f9a40d30-f126-11e7-8f88-68aa5009848a.png)

In proper Chromium and in the WebKit version these actions work. I have not seens any logs in the terminal, nor in the developer tools console.

**Comment by fenryxo** [comment]
Thanks @bartlibert. I cannot reproduce the issue on my machine. It might disappear after I solve tiliado/valacef#1. Can you reproduce the issue also with Cefium demo browser?

```
flatpak run --command=Cefium eu.tiliado.NuvolaAppGooglePlayMusic//master --url="https://play.google.com/music/" --disable-flash
```

**Comment by bartlibert** [comment]
Hi, I tried testing it with Cefium and got:

`[0108/125313.206216:WARNING:browser_main_loop.cc(297)] GLib-GObject: invalid cast from 'GdkWaylandVisual' to 'GdkX11Visual'
`

Soo... this pointed me to try everything in X11 instead of Wayland and guess what: there it works.
So the issue is most likely related to running under Wayland.

**Comment by fenryxo** [comment]
Thanks, @bartlibert. Could you test again under Wayland with Cefium which comes with Nuvola 4.9.93?

**Comment by bartlibert** [comment]
I don't get the "invalid cast" error anymore and get into google music, but the popup menus are still not working. (No errors in terminal nor web console)

**Comment by TrevorScheitrum** [comment]
I don't know if this is where I should post this, or if I should create a new issue (clicking report bug took me here instead of the general 'issues' page) But here's my bug report:

OS - Linux Mint 18.3
Hardware - Dell Latitude E5470
Video Hardware - Intel Skylake Integrated Graphics
Nuvola Installed Version - Experimental Chromium 63.0.3239.109 web engine through the flatpak repo
Problem - Launching Spotify through the Chrome-ported Nuvola flatpak crashes randomly during playback or just leaving the window open.  Not sure how to collect more details but just wanted to report it in case it hasn't already.

Not sure if this matters but I also have the official spotify app installed through their flatpak as well, 'flatpak list' returns:
Ref                                                              Options
com.spotify.Client/x86_64/stable                system,current
eu.tiliado.Nuvola/x86_64/master                 system        
eu.tiliado.Nuvola/x86_64/stable                 system,current
eu.tiliado.NuvolaAppSpotify/x86_64/master       system,current
eu.tiliado.NuvolaAppSpotify/x86_64/stable       system        
io.github.Pithos/x86_64/stable                  system,current
org.musicbrainz.Picard/x86_64/stable            system,current
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 system,runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6      system,runtime
org.freedesktop.Platform/x86_64/1.6             system,runtime
org.gnome.Platform/x86_64/3.24                  system,runtime
org.gnome.Platform/x86_64/3.26                  system,runtime

**Comment by fenryxo** [comment]
Hello @TrevorScheitrum. Thanks for reporting your issue. Could you create a new ticket for that with [debug logs](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines) from Nuvola 4.9.163?

**Comment by TrevorScheitrum** [comment]
Since posting this report it hasn't crashed, so i'm wondering if my system was low on ram or something.  If it starts crashing again I'll try to grab debug logs

**Comment by fenryxo** [comment]
Recently ported:

- [Nuvola 4.10 Uses Chromium Engine for Spotify, Deezer, YouTube, Mixcloud, and BBC iPlayer to Play Without Flash Plugin](https://medium.com/nuvola-news/nuvola-4-10-da46a5088c94)
- [Nuvola 4.10.23 Updates 8tracks, Bandcamp, Google Play Music, and Google Calendar](https://medium.com/nuvola-news/nuvola-4-10-23-325c54a9d494)

Overral progress:

- [x] [8tracks](https://github.com/tiliado-nuvola-app-8tracks) (Jiří Janoušek)
- [ ] [Amazon Cloud Player](https://github.com/tiliado-nuvola-app-amazon-cloud-player) (Andrew Stubbs)
- [ ] [BBC iPlayer](https://github.com/tiliado-nuvola-app-bbc-iplayer) (Andrew Stubbs)
- [x] [Bandcamp](https://github.com/tiliado-nuvola-app-bandcamp) (Jiří Janoušek)
- [x] [Deezer](https://github.com/tiliado-nuvola-app-deezer) (Jiří Janoušek)
- [x] [Google Calendar](https://github.com/tiliado-nuvola-app-google-calendar) (Jiří Janoušek)
- [ ] [Google Keep](https://github.com/tiliado-nuvola-app-google-keep) (Matthew Gabeler-Lee) - unreleased, in progress
- [x] [Google Play Music](https://github.com/tiliado-nuvola-app-google-play-music) (Jiří Janoušek)
- [x] [Groove](https://github.com/tiliado-nuvola-app-groove) (Joel Cumberland) - dead
- [ ] [Jango](https://github.com/tiliado-nuvola-app-jango) (Stefano Bagnatica)
- [ ] [Jupiter Broadcasting](https://github.com/tiliado-nuvola-app-jupiter-broadcasting) (Andrew Stubbs)
- [ ] [KEXP Live Stream](https://github.com/tiliado-nuvola-app-kexp) (Michael Nye)
- [ ] [Logitech Media Server](https://github.com/tiliado-nuvola-app-logitech-media-server) (Steffen Coenen)
- [x] [Mixcloud](https://github.com/tiliado-nuvola-app-mixcloud) (Jiří Janoušek)
- [ ] [NPR One](https://github.com/tiliado-nuvola-app-npr-one) (Jiří Janoušek)  - unreleased, in progress
- [ ] [Plex Music](https://github.com/tiliado-nuvola-app-plex) (Jiří Janoušek) - in progress
- [ ] [Pocket Casts](https://github.com/tiliado-nuvola-app-pocket-casts) (Jiří Janoušek) - in progress
- [ ] [SiriusXM](https://github.com/tiliado-nuvola-app-siriusxm) (Jiří Janoušek) - in progress
- [ ] [SoundCloud](https://github.com/tiliado-nuvola-app-soundcloud) (KiXaM)
- [x] [Spotify](https://github.com/tiliado-nuvola-app-spotify) (Jiří Janoušek)
- [ ] [TuneIn](https://github.com/tiliado-nuvola-app-tunein) (Aurélien Jabot)
- [ ] [Yandex Music](https://github.com/tiliado-nuvola-app-yandex-music) (Aleksey Zhidkov)
- [x] [YouTube](https://github.com/tiliado-nuvola-app-youtube) (Jiří Janoušek)
- [ ] [ownCloud Music](https://github.com/tiliado-nuvola-app-owncloud-music) (Jiří Janoušek) - in progress

**Comment by fenryxo** [comment]
More scripts ported:

* [Nuvola 4.10.29 Supports Ubuntu 18.04; Updates OwnCloud Music, Plex Music, Pocket Casts, and SiriusXM](https://medium.com/nuvola-news/nuvola-4-10-29-784f90063b44)
* [Nuvola Updates Amazon Cloud Player, BBC iPlayer & Jupiter Broadcasting; Supports Fedora 28](https://medium.com/nuvola-news/nuvola-updates-amazon-cloud-player-bbc-iplayer-jupiter-broadcasting-supports-fedora-28-38c809a08639)

**Comment by fenryxo** [comment]
Closing in favor of #424.
