### ISSUE TITLE
Spotify no longer works with WebKitGTK, Chromium port in development

### ISSUE THREAD

**Issue by gregghz** [tiliado/nuvolaruntime#374]
Spotify no longer works with WebKitGTK, Chromium port in development
-----------------------------------------------------

Unfortunately, [Spotify’s Web Player no longer works on Safari](https://www.theverge.com/2017/9/10/16283494/spotify-web-player-safari-browser-support-apple) and Nuvola uses a variant of Safari's web rendering engine (WebKitGTK). There is an ongoing effort to port Nuvola to Chromium backend (#372).

### Update January 6th, 2017

>  _Users with Nuvola Basic/Premium/Patron account will be invited to test development builds soon._
> -- [Status of Chromium-based Port of Nuvola](https://medium.com/nuvola-news/nuvola-chromium-port-status-3b1648b29c77)

All Nuvola Patron & Premium user have been invited to test Nuvola with working Chromium backend, Nuvola Basic users will follow in a week.

Original report
------------------

### My System:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

```
$ uname -m
x86_64
```

Desktop Environment: Unity

### Nuvola Player Instance:

Spotify 2.3
Nuvola Apps 4.7.0
Diorite 4.7.0
WebKitGTK 2.16.6
libsoup 2.58.2

Installed via stable flatpak.

### Steps to reproduce:

1.) run `flatpak run eu.tiliado.NuvolaAppSpotify`
2.) click "continue" if the "there are a few issues" screen shows up (for me, I get a warning on VA-API Driver and VDPAU Driver)
3.) At this point I get an "integration error" popup in the screenshot below. Notice that the source of that is likely because the spotify web app is detecting Nuvola Apps as an unsupported web browser (yellow bar at the top)

![spotify-bug](https://user-images.githubusercontent.com/220801/30292775-9f415d70-96f4-11e7-9bb4-dc9f21ed9fc3.png)

I expect spotify to load and let me play music.

### Debugging output:

Nuvola:
[nuvola.txt](https://github.com/tiliado/nuvolaruntime/files/1293729/nuvola.txt)

NuvolaAppSpotify:
[nuvola-spotify.txt](https://github.com/tiliado/nuvolaruntime/files/1293728/nuvola-spotify.txt)

### Extra information:

I get the same "This browser doesn't support Spotify Web Player" banner using WebKitGtk MiniBrowser.

**Comment by gregghz** [comment]
I came across instructions [here](https://github.com/tiliado/nuvolaruntime/issues/330#issuecomment-299218679) on how to get more detailed logs (original attached above follow the basic logs on the same comment). I've attached the detailed logs here:

Nuvola:
[nuvola-log.txt](https://github.com/tiliado/nuvolaruntime/files/1294213/nuvola-log.txt)

Spotify:
[nuvola-spotify.txt](https://github.com/tiliado/nuvolaruntime/files/1294216/nuvola-spotify.txt)

**Comment by fenryxo** [comment]
Hello @gregghz. Thanks for reporting this issue. Unfortunately, [Spotify’s Web Player no longer works on Safari](https://www.theverge.com/2017/9/10/16283494/spotify-web-player-safari-browser-support-apple) and Nuvola uses a variant of Safari's web rendering engine (WebKitGTK). There is ongoing effort to port Nuvola to Chromium backend (#372) but it is going to take a few months to complete.

**Comment by fenryxo** [comment]
Spotify does not work even when the user agent is set to Chrome. [It really requires DRM](https://support.spotify.com/cz/using_spotify/system_settings/enable-the-spotify-web-player/).

**Comment by fenryxo** [comment]
Vala + GTK+ 3 bindings of CEF for Nuvola - Widevine DRM works (Spotify):
![cef_spotify](https://user-images.githubusercontent.com/853706/33810592-f4a32678-de06-11e7-8073-9dc9c04df9f7.png)

**Comment by gregghz** [comment]
This is awesome. Will that make it into mainline nuvola or will using widevine need some manual work?

**Comment by fenryxo** [comment]
There is still a lot of work to do. All high-level WebKitGTK API used by Nuvola needs to be reimplemented on top of Chromium Embedded Framework. Once it's done, Nuvola will use CEF by default. Widevine is not an issue, it can be easily extracted from Google Chrome.

There is also some info in a blog post draft: https://medium.com/nuvola-news/status-of-chromium-based-port-of-nuvola-3b1648b29c77

**Comment by fenryxo** [comment]
Blog post: [Status of Chromium-based Port of Nuvola](https://medium.com/nuvola-news/nuvola-chromium-port-status-3b1648b29c77)

**Comment by fenryxo** [comment]
>  _Users with Nuvola Basic/Premium/Patron account will be invited to test development builds soon._
> -- [Status of Chromium-based Port of Nuvola](https://medium.com/nuvola-news/nuvola-chromium-port-status-3b1648b29c77)

All Nuvola Patron & Premium user have been invited to test Nuvola with working Chromium backend, Nuvola Basic users will follow in a week.

**Comment by fenryxo** [comment]
>>  _Users with Nuvola Basic/Premium/Patron account will be invited to test development builds soon._
>> -- [Status of Chromium-based Port of Nuvola](https://medium.com/nuvola-news/nuvola-chromium-port-status-3b1648b29c77)
>
> All Nuvola Patron & Premium user have been invited to test Nuvola with working Chromium backend, Nuvola Basic users will follow in a week.

Nuvola Basic users have also been invited.

**Comment by fenryxo** [comment]
The stable flatpak of Spotify now uses the Chromium backend. It will be officially announced with Nuvola 4.10 release.
