### ISSUE TITLE
Play/Pause keyboard button does not work

### ISSUE THREAD

**Issue by voxik** [tiliado/nuvolaruntime#375]
Play/Pause keyboard button does not work anymore using Mixcloud app. This is the warning I see in my Journal:

~~~
Sep 19 09:04:12 localhost.localdomain eu.tiliado.NuvolaAppMixcloud.desktop[7979]: Runner: [WARNING Δ01m51s432452us DioriteGtk] Action.vala:74: Cannot activate action 'toggle-play', because it is disabled.
~~~

$ rpm -qa nuvola*
nuvolaruntime-4.7.0-1.fc28.x86_64
nuvola-app-mixcloud-3.2-3.fc28.noarch

$ rpm -q gtk3
gtk3-3.22.20-1.fc28.x86_64

**Comment by fenryxo** [comment]
Hello @voxik. Thanks for reporting this issue. I've copied it as tiliado/nuvola-app-mixcloud#11 for the Mixcloud script maintainer to address it.

**Comment by fenryxo** [comment]
Closing as we no have [a shared board](https://github.com/orgs/tiliado/projects/1) so there is no need for two tickets.

**Comment by voxik** [comment]
Sorry, is the link broken or I don't have access to that board?

**Comment by fenryxo** [comment]
The project boards seem not to be public.
