### ISSUE TITLE
Can't relaunch Nuvola-app or launch second Nuvola-App

### ISSUE THREAD

**Issue by laramy2020** [tiliado/nuvolaruntime#378]
System: Arch Linux 4.12.14-1 x86_64
DE: Gnome 3.24.3
nuvola --version:
```
Web Apps - based on Nuvola Apps™ project
Version 4.7.0
Revision snapshot
Diorite 4.7.0
WebKitGTK 2.16.6
libsoup 2.58.2

```
Affects all nuvola-apps

How to reproduce.

- Launch nuvola via the Web App Desktop shortcut, The dedi nuvola-app shortcut, or running nuvola in the commandline
- Close the Web app.
- Launch any web app using any of the same 3 steps above

Error dialog pops up saying: 

> *app can not start*
> Failed to connect to nuvola app runtime service 
> Error message: Failed to connect to socket 'N3'. Connection refused

This issue prevents 2 nuvola-apps from running at the same time as well.

To kill the service I run 
`pkill -f nuvola
`
Forgot to mention. These are compiled builds. Using update PKGBUILDS found in the aur
[AUR](https://aur.archlinux.org/packages/?O=0&SeB=M&K=laramy2020&outdated=&SB=n&SO=a&PP=50&do_Search=Go)
And
[GitHub](https://github.com/laramy2020/NuvolaPlayer_Arch)

**Comment by fenryxo** [comment]
Hello @laramy2020. Thank for reporting this issue. Does it still affect Nuvola 4.8? If so, could you provide me with debug logs (`nuvola --debug`)?

> Using update PKGBUILDS found in the aur

Off topic but you pass `--webkitgtk-supports-mse` to Nuvola's build. Are you 100% sure that Arch Linux builds of WebKitGTK+ support MSE (`-DENABLE_MEDIA_SOURCE=ON`)?

**Comment by laramy2020** [comment]
The program still hangs
[nuvolaout.txt](https://github.com/tiliado/nuvolaruntime/files/1356191/nuvolaout.txt)
I don't have dbus launcher enabled yet. I am aiming for enabling that once i get all packages managed/maintained in the aur. If that might help i will give that a try as well.


I did not see that flag exactly. But I did a recursive grep of "ENABLE_MEDIA_SOURCE" in the source files (including the PKGBUILD) and i got returns of all ENABLE_MEDIA_SOURCE=ON

So that was everywhere, just not in the build script.
If there is a way I can confirm an installed package, that would be great.

If the source requires DENABLE_MEDIA_SOURCE=ON for the build to be enabled i can add that to my PKGBUILD libs.

Ok looks like things have changed from 2.16 to 2.18 i might have to make a modified webkitgtk build in the aur.
[webkit2gtk.txt](https://github.com/tiliado/nuvolaruntime/files/1356257/webkit2gtk.txt)

**Comment by fenryxo** [comment]
> The program still hangs nuvolaout.txt

I cannot see any sign of an error in the log. It shows that Google Play Music started and exited successfully, nothing more.

> If there is a way I can confirm an installed package, that would be great.

Check `window.MediaSource` in [WebKit WebInspector](http://tiliado.github.io/nuvolaplayer/development/images/guide/inspect_element.png). Nuvola 4.9 will do that for you though (since 1d8c398). If you need more info, start a new topic at [nuvola-devel mailing list](https://groups.google.com/d/forum/nuvola-player-devel).

**Comment by laramy2020** [comment]
> Check window.MediaSource in WebKit WebInspector. Nuvola 4.9 will do that for you though (since 1d8c398). If you need more info, start a new topic at nuvola-devel mailing list.

Looks like arch dose not enable MSE. Will be making that package now as well...

I plan on making a new debug build tomorrow in a clean arch install. I will grab logs and videos.

**Comment by laramy2020** [comment]
Attached are two more logs and the system it was tested on
[systempackages.txt](https://github.com/tiliado/nuvolaruntime/files/1405361/systempackages.txt)
[system.txt](https://github.com/tiliado/nuvolaruntime/files/1405362/system.txt)

[nuvola.log](https://github.com/tiliado/nuvolaruntime/files/1405359/nuvola.log)
[nuvola2.log](https://github.com/tiliado/nuvolaruntime/files/1405360/nuvola2.log)

And a video of the 3 machine I have with this issue (all 3 have this issue) [Video](https://packages.laramyblack.com/2017-10-22_15-16-13.mp4)

And the updated [AUR](https://aur.archlinux.org/packages/nuvolaruntime) PKGBUILD

**Comment by fenryxo** [comment]
There obviously is an issue with a socket connection from the youtube subprocess to the master process. A relevant code in Diorite might be:

```
grep -rn "Failed to connect to socket" src
src/glib/io.vala:57:		throw new IOError.CONN_FAILED("Failed to connect to socket '%s'. %s", path, e.message);
src/glib/SocketChannel.vala:64:			throw new IOError.CONN_FAILED("Failed to connect to socket '%s'. %s", name, e.message);
src/glib/SocketChannel.vala:78:			throw new IOError.CONN_FAILED("Failed to connect to socket '%s'. %s", name, e.message);
```

**Comment by fenryxo** [comment]
@laramy2020, Diorite master now produces three unique error messages instead of "Failed to connect to socket". Could you post new debugging output once this changeset reaches your builds (Diorite 4.9)?

**Comment by fenryxo** [comment]
> Could you post new debugging output once this changeset reaches your builds (Diorite 4.9)?

Nuvola 4.9 is out ;-)

**Comment by laramy2020** [comment]
Awesome. will do soon. Been a busy month, but my scripts seem to be working on making new pkgbuilds.

**Comment by fenryxo** [comment]
Closing as expired because there has not been any response for a month. Feel free to add requested information to reopen this issue.
