### ISSUE TITLE
Deezer: back button causes Web App to freeze

### ISSUE THREAD

**Issue by ou-li** [tiliado/nuvolaruntime#389]
Web App Integration Script 2.7
Genuine Flatpak Build  4.8.2 Revision 2-g9519b22
Ubuntu 16.04 64bit

Steps to reproduce: Launch Deezer WebApp, play a couple of songs, click "<" Arrow button .
Currently playing song will continue playing till the end, GUI will become instantly become unresponsive, at the end of the song silence occurs.

**Comment by fenryxo** [comment]
Hello @ou-li. Thanks for reporting this issue.

**Comment by fenryxo** [comment]
Could you check whether Nuvola 4.8.23 fixes the issue?

**Comment by ou-li** [comment]
It does indeed. Thank you for the quick fix!
