### ISSUE TITLE
Problem with apt-get update before installing

### ISSUE THREAD

**Issue by cmguigamf** [tiliado/nuvolaruntime#393]
Hi, I'm using Elementary OS (Loki) and for the past few days, I've been struggling with installing Nuvola Player. I'm following this tutorial http://www.edivaldobrito.com.br/como-instalar-o-nuvola-player-no-ubuntu-debian-e-derivados/ it's in english, but I think you can get the hang of it.

This is my terminal log when I sudo apt-get update:

sudo apt-get update
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 http://ppa.launchpad.net/atareao/atareao/ubuntu xenial InRelease                           
Hit:3 http://repo.steampowered.com/steam precise InRelease                                       
Hit:4 http://packages.elementary.io/appcenter xenial InRelease                                   
Hit:5 http://repository.spotify.com stable InRelease                                             
Hit:6 http://ppa.launchpad.net/elementary-os/stable/ubuntu xenial InRelease                      
Hit:7 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu xenial InRelease                  
Ign:8 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ InRelease        
Hit:9 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu xenial InRelease                             
Ign:10 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Release         
Ign:11 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Packages        
Hit:12 http://ppa.launchpad.net/wfg/0ad/ubuntu xenial InRelease                          
Ign:13 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Translation-en_US
Ign:14 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Translation-en
Ign:15 https://tiliado.eu/nuvolaplayer/repository/deb loki InRelease
Ign:11 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Packages
Ign:16 https://tiliado.eu/nuvolaplayer/repository/deb loki Release
Ign:13 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Translation-en_US
Ign:17 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable amd64 Packages
Ign:14 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Translation-en
Ign:18 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable i386 Packages
Ign:11 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Packages
Ign:19 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable all Packages
Ign:13 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Translation-en_US
Ign:14 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Translation-en
Ign:20 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable Translation-en_US
Ign:11 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Packages
Ign:21 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable Translation-en
Ign:13 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Translation-en_US
Ign:22 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable amd64 DEP-11 Metadata
Ign:14 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Translation-en
Ign:23 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable DEP-11 64x64 Icons
Hit:24 http://br.archive.ubuntu.com/ubuntu xenial InRelease
Hit:25 http://br.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:26 http://br.archive.ubuntu.com/ubuntu xenial-backports InRelease
Ign:17 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable amd64 Packages
Ign:11 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Packages
Ign:18 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable i386 Packages
Ign:13 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Translation-en_US
Ign:19 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable all Packages
Ign:14 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Translation-en
Ign:20 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable Translation-en_US
Err:11 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Packages        
  404  Not Found [IP: 195.135.221.134 80]
Ign:21 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable Translation-en                 
Ign:13 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Translation-en_US
Ign:14 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Translation-en  
Ign:22 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable amd64 DEP-11 Metadata          
Ign:23 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable DEP-11 64x64 Icons             
Ign:17 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable amd64 Packages                 
Ign:18 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable i386 Packages                  
Ign:19 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable all Packages                   
Ign:20 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable Translation-en_US              
Ign:21 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable Translation-en                 
Ign:22 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable amd64 DEP-11 Metadata          
Ign:23 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable DEP-11 64x64 Icons             
Ign:17 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable amd64 Packages                 
Ign:18 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable i386 Packages                  
Ign:19 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable all Packages                   
Ign:20 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable Translation-en_US              
Ign:21 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable Translation-en                 
Ign:22 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable amd64 DEP-11 Metadata          
Ign:23 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable DEP-11 64x64 Icons             
Ign:17 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable amd64 Packages                 
Ign:18 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable i386 Packages                  
Ign:19 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable all Packages                   
Ign:20 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable Translation-en_US              
Ign:21 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable Translation-en                 
Ign:22 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable amd64 DEP-11 Metadata          
Ign:23 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable DEP-11 64x64 Icons             
Err:17 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable amd64 Packages
  404  Not Found
Ign:18 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable i386 Packages
Ign:19 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable all Packages
Ign:20 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable Translation-en_US
Ign:21 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable Translation-en
Ign:22 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable amd64 DEP-11 Metadata
Ign:23 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable DEP-11 64x64 Icons
Fetched 102 kB in 14s (7.005 B/s)
Reading package lists... Done
W: Target Packages (non-free/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/spotify.list:1 and /etc/apt/sources.list.d/spotify.list:2
W: Target Packages (non-free/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/spotify.list:1 and /etc/apt/sources.list.d/spotify.list:2
W: Target Packages (non-free/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/spotify.list:1 and /etc/apt/sources.list.d/spotify.list:2
W: Target Translations (non-free/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/spotify.list:1 and /etc/apt/sources.list.d/spotify.list:2
W: Target Translations (non-free/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/spotify.list:1 and /etc/apt/sources.list.d/spotify.list:2
W: Target DEP-11 (non-free/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/spotify.list:1 and /etc/apt/sources.list.d/spotify.list:2
W: Target DEP-11-icons (non-free/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/spotify.list:1 and /etc/apt/sources.list.d/spotify.list:2
W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:2
W: Target Packages (stable/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:2
W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:2
W: Target Translations (stable/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:2
W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:2
W: Target DEP-11 (stable/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:2
W: Target DEP-11-icons (stable/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:2
W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:3
W: Target Packages (stable/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:3
W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:3
W: Target Translations (stable/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:3
W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:3
W: Target DEP-11 (stable/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:3
W: Target DEP-11-icons (stable/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:3
W: The repository 'http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1 ./ Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'https://tiliado.eu/nuvolaplayer/repository/deb loki Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://download.opensuse.org/repositories/home:/strycore/xUbuntu_0.4.1/./Packages  404  Not Found [IP: 195.135.221.134 80]
E: Failed to fetch https://tiliado.eu/nuvolaplayer/repository/deb/dists/loki/stable/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
W: Target Packages (non-free/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/spotify.list:1 and /etc/apt/sources.list.d/spotify.list:2
W: Target Packages (non-free/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/spotify.list:1 and /etc/apt/sources.list.d/spotify.list:2
W: Target Packages (non-free/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/spotify.list:1 and /etc/apt/sources.list.d/spotify.list:2
W: Target Translations (non-free/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/spotify.list:1 and /etc/apt/sources.list.d/spotify.list:2
W: Target Translations (non-free/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/spotify.list:1 and /etc/apt/sources.list.d/spotify.list:2
W: Target DEP-11 (non-free/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/spotify.list:1 and /etc/apt/sources.list.d/spotify.list:2
W: Target DEP-11-icons (non-free/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/spotify.list:1 and /etc/apt/sources.list.d/spotify.list:2
W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:2
W: Target Packages (stable/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:2
W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:2
W: Target Translations (stable/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:2
W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:2
W: Target DEP-11 (stable/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:2
W: Target DEP-11-icons (stable/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:2
W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:3
W: Target Packages (stable/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:3
W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:3
W: Target Translations (stable/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:3
W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:3
W: Target DEP-11 (stable/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:3
W: Target DEP-11-icons (stable/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:1 and /etc/apt/sources.list.d/tiliado-nuvolaplayer.list:3

So, when I use sudo apt-get install nuvolaplayer3, I obviously come up empty. What am I doing wrong?

Thanks

**Comment by fenryxo** [comment]
Hello @cmguigamf. The instructions are for obsolete **Nuvola 3.0.9**, which will [reach the end of life on December 31st, 2017](https://medium.com/nuvola-news/nuvola-3-0-9-688e20f18a1c) and its repository will be deleted. Nuvola **4.8** is the latest available release and it officially supports elementaryOS Loki.

> Err:17 https://tiliado.eu/nuvolaplayer/repository/deb loki/stable amd64 Packages
404 Not Found

As you can see, the Nuvola 3 repository does not provide packages for Loki.

1. Run `sudo rm -f /etc/apt/sources.list.d/tiliado-nuvolaplayer.list`.
2. [Follow installation instructions for Nuvola 4](https://nuvola.tiliado.eu/index/elementary/loki/).
