### ISSUE TITLE
Service Request: Brain.fm

### ISSUE THREAD

**Issue by brwyatt** [tiliado/nuvolaruntime#397]
* Web app located here: https://www1.brain.fm/app
* Mainly would be useful for play/pause and skip forward (there's no skip back).
* Low-priority (this app is largely a set it and leave it use case, but would be convenient to use system controls for play/pause and skip)
* Patreon username: [brwyatt](https://www.patreon.com/brwyatt/creators)

**Comment by fenryxo** [comment]
Hello @brwyatt.Thanks for your tip. Nuvola might add new scripts as soon as the Chromium transition is completed in February.

**Comment by fenryxo** [comment]
* Published but not announced yet.
* [Flatpak package](https://nuvola.tiliado.eu/app/focus_at_will/)
* [Source code](https://github.com/tiliado/nuvola-app-brain-fm)

**Comment by brwyatt** [comment]
Awesome! Thanks!
