### ISSUE TITLE
"Nuvola._keyValueStorageSetDefaultValue is not a function" with CEF

### ISSUE THREAD

**Issue by a-m-s** [tiliado/nuvolaruntime#401]
When `NUVOLA_USE_CEF=true` is set, the Amazon Cloud Player app fails at startup with the following message:

![screenshot from 2018-01-17 22-41-08](https://user-images.githubusercontent.com/5088295/35071211-d27d40ee-fbd7-11e7-9ed6-7709b0655004.png)

If I remove this line, from `integrate.js` ....
```
Nuvola.config.setDefault(COUNTRY_VARIANT, "");
```
... then the app runs just fine.

Either the API should be fixed or removed (in which case, I'll fix the app accordingly; I'm not actually sure what it's trying to do here).

**Comment by fenryxo** [comment]
* Use [setDefaultAsync](https://tiliado.github.io/nuvolaplayer/development/apps/api_reference.html#Nuvola.KeyValueStorage.setDefaultAsync) instead. CEF engine doesn't and won't support synchronous IPC calls. That will be announced in some porting howto after Nuvola 4.10.
* The default values are usually used if the script is run for the first time with no configuration at all. Then some scripts show [an initialization form](https://tiliado.github.io/nuvolaplayer/development/apps/initialization-and-preferences-forms.html), which uses the default values. You can try to rename the config file `~/.var/app/eu.tiliado.Nuvola{CamelCaseFlatpakId)/config/nuvolaruntime/apps_data/{script-id-with-dashes}/config.json` and check whether the form works.

**Comment by fenryxo** [comment]
Example: https://github.com/tiliado/nuvola-app-google-play-music/commit/6015e7b3ed634f0423cc7cb9a0df0c38e4ebee22

**Comment by a-m-s** [comment]
This should be fixed now. I confirmed that the config form shows correctly.
