### ISSUE TITLE
App crashes when trying to activate tiliado account

### ISSUE THREAD

**Issue by bartlibert** [tiliado/nuvolaruntime#402]
**System info**
My system: Debian GNU/Linux buster/sid
Architecture: x86_64
Desktop environment: Gnome (issue reproduced in both Xorg and Wayland)

**App info**
Nuvola Apps - Genuine flatpak build
Version 4.9.93
Revision 93-g3d6c34f
Diorite 4.9.10
WebKitGTK 2.18.4
Chromium N/A
libsoup 2.60.0

Issue is seen with both master and stable branches

**Steps to reproduce**
1. Make sure you are not activated and see the "free trial" bar in the main app
2. Click "Purchase Nuvola"
3. Click "I already have a plan"
4. Click "I already have a Tiliado account"
5. Click "Activate Nuvola" -> Crash

I tried some other buttons in the menu, and the result is the same. Also "Get Nuvola for free" gives the same result.
**Logs**

Logs: (just startup, no logs are seen any more after interacting with the buttons)
Master: [DEBUG Δ051155us DioriteGtk] DesktopShell.vala:251: Shell: gnome shell 3.26.2, CSD 1, appmenu 1, menubar 0
Master: [DEBUG Δ002615us Nuvola] XKeyGrabber.vala:190: Obtained a X11 Window for the display ':99.0'.
Master: [DEBUG Δ001061us Nuvola] WebkitOptions.vala:49: MSE supported: yes
Master: [DEBUG Δ031897us GdkPixbuf] gdk_pixbuf_from_pixdata() called on:
Master: [DEBUG Δ000042us GdkPixbuf]     Encoding raw
Master: [DEBUG Δ000018us GdkPixbuf]     Dimensions: 14 x 14
Master: [DEBUG Δ000016us GdkPixbuf]     Rowstride: 56, Length: 808
Master: [DEBUG Δ000015us GdkPixbuf]     Copy pixels == false
Master: [DEBUG Δ026577us GdkPixbuf] gdk_pixbuf_from_pixdata() called on:
Master: [DEBUG Δ000038us GdkPixbuf]     Encoding raw
Master: [DEBUG Δ000017us GdkPixbuf]     Dimensions: 14 x 14
Master: [DEBUG Δ000015us GdkPixbuf]     Rowstride: 56, Length: 808
Master: [DEBUG Δ000015us GdkPixbuf]     Copy pixels == false
Master: [DEBUG Δ001882us DioriteGtk] Application.vala:274: XFCE session vanished: org.xfce.SessionManager
Master: [DEBUG Δ037562us GdkPixbuf] gdk_pixbuf_from_pixdata() called on:
Master: [DEBUG Δ000052us GdkPixbuf]     Encoding raw
Master: [DEBUG Δ000028us GdkPixbuf]     Dimensions: 14 x 14
Master: [DEBUG Δ000022us GdkPixbuf]     Rowstride: 56, Length: 808
Master: [DEBUG Δ000023us GdkPixbuf]     Copy pixels == false
Master: [DEBUG Δ033130us GdkPixbuf] gdk_pixbuf_from_pixdata() called on:
Master: [DEBUG Δ000043us GdkPixbuf]     Encoding raw
Master: [DEBUG Δ000018us GdkPixbuf]     Dimensions: 14 x 14
Master: [DEBUG Δ000015us GdkPixbuf]     Rowstride: 56, Length: 808
Master: [DEBUG Δ000015us GdkPixbuf]     Copy pixels == false
Master: [DEBUG Δ022613us GdkPixbuf] gdk_pixbuf_from_pixdata() called on:
Master: [DEBUG Δ000125us GdkPixbuf]     Encoding raw
Master: [DEBUG Δ000047us GdkPixbuf]     Dimensions: 14 x 14
Master: [DEBUG Δ000050us GdkPixbuf]     Rowstride: 56, Length: 808
Master: [DEBUG Δ000029us GdkPixbuf]     Copy pixels == false
Master: [DEBUG Δ015008us GdkPixbuf] gdk_pixbuf_from_pixdata() called on:
Master: [DEBUG Δ000053us GdkPixbuf]     Encoding raw
Master: [DEBUG Δ000019us GdkPixbuf]     Dimensions: 14 x 14
Master: [DEBUG Δ000016us GdkPixbuf]     Rowstride: 56, Length: 808
Master: [DEBUG Δ000015us GdkPixbuf]     Copy pixels == false
Master: [DEBUG Δ016274us GdkPixbuf] gdk_pixbuf_from_pixdata() called on:
Master: [DEBUG Δ000093us GdkPixbuf]     Encoding raw
Master: [DEBUG Δ000034us GdkPixbuf]     Dimensions: 14 x 14
Master: [DEBUG Δ000028us GdkPixbuf]     Rowstride: 56, Length: 808
Master: [DEBUG Δ000023us GdkPixbuf]     Copy pixels == false
https://nuvola.tiliado.eu/static/js/app.js:1: CONSOLE ERROR SyntaxError: Unexpected keyword 'var'. Expected ';' after variable declaration.

**Backtrace**
Decoded acktrace of the nuvola app is attached.
[bt.txt](https://github.com/tiliado/nuvolaruntime/files/1646448/bt.txt)

**Comment by fenryxo** [comment]
Hello @bartlibert. Thanks for your bug report. I'm now building packages with a fix.

**Comment by fenryxo** [comment]
Could you verify that the issue is resolved?

**Comment by bartlibert** [comment]
It's working now in the stable build.

**Comment by fenryxo** [comment]
Cool :-)
