### ISSUE TITLE
 No sound in Nuvola Player on Ubuntu 17.10 with error AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused 

### ISSUE THREAD

**Issue by MurzNN** [tiliado/nuvolaruntime#408]
After installing Nuvola Player on my Ubuntu Linux 17.10 AMD64 - it starts & works successfully, but I hear no sound, and no sound source in Pulseadio app list.

If I start app from console, I see repeating errors:
```
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused
```
Other music apps works well, without errors.

System info:
```
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
Yandex Music script 1.5
Maintainer: Aleksey Zhidkov

--- Powered by ---

Nuvola Apps - Genuine flatpak build
Version 4.9.149
Revision 149-g78479d8
Diorite 4.9.11
WebKitGTK 2.18.6
Chromium 63.0.3239.109
libsoup 2.60.0
```
And same thing with other scripts (TuneIn, Deezer).

Here is full debug output of app: https://pastebin.com/6CtRpw2d

Via manually starts `/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/MiniBrowser` sound works well on those services.

What this errors means and how can I fix them?

**Comment by fenryxo** [comment]
Hello @MurzNN. Thanks for reporting your issue. Could you add missing [basic information as specified in the Bug reporting guidelined](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#basic-information)?

**Comment by MurzNN** [comment]
I add debug info to first post. Also maybe the problem is that I use system-wide pulseaudio daemon, shared with all system users, but all other apps works well with it.

**Comment by MurzNN** [comment]
Output of aplay:
```
$ aplay -L
default
    Playback/recording through the PulseAudio sound server
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
sysdefault:CARD=PCH
    HDA Intel PCH, ALC887-VD Analog
    Default Audio Device
front:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    Front speakers
surround21:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    4.0 Surround output to Front and Rear speakers
surround41:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Digital
    IEC958 (S/PDIF) Digital Audio Output
hdmi:CARD=PCH,DEV=0
    HDA Intel PCH, HDMI 0
    HDMI Audio Output
dmix:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    Direct sample mixing device
dmix:CARD=PCH,DEV=1
    HDA Intel PCH, ALC887-VD Digital
    Direct sample mixing device
dmix:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 0
    Direct sample mixing device
dsnoop:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    Direct sample snooping device
dsnoop:CARD=PCH,DEV=1
    HDA Intel PCH, ALC887-VD Digital
    Direct sample snooping device
dsnoop:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 0
    Direct sample snooping device
hw:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    Direct hardware device without any conversions
hw:CARD=PCH,DEV=1
    HDA Intel PCH, ALC887-VD Digital
    Direct hardware device without any conversions
hw:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 0
    Direct hardware device without any conversions
plughw:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    Hardware device with all software conversions
plughw:CARD=PCH,DEV=1
    HDA Intel PCH, ALC887-VD Digital
    Hardware device with all software conversions
plughw:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 0
    Hardware device with all software conversions
```

**Comment by fenryxo** [comment]
Thanks, @MurzNN. 
* [Debug log](https://github.com/tiliado/nuvolaruntime/files/1743772/debug.txt) from pastebin. Next time, please attach debug logs as text files instead of a pastebin link.
* Could you install [any multimedia Flatpak app, e.g. Rhythmbox](https://flathub.org/apps/) to check whether the issue is in Flatpak sandbox? I'm not sure whether it can handle system-wide PulseAudio daemon.
* Please precisely describe how you have set up the system-wide PulseAudio daemon so that I can test it on a clean system.
* I'm puzzled a bit by `AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused` error message. It seems not to come from ALSA but OpenAL. I've never seen that.

**Comment by MurzNN** [comment]
About Pastebin - log is too long for paste here, and duplicate already posted main part of log, so I move it to pastebin.
I try to install Rhythmbox via Flatpak and it have same problem, so seems this is a system problem with flatpak, not in Nuvola Player.
I'll try to fix it and post results here, if found something.

**Comment by fenryxo** [comment]
> About Pastebin - log is too long for paste here

That's why I asked you to *attach* the log as a text file, not to *paste* it here. I should've made it more clear as not everybody is familiar with this GitHub function. Sorry for that.
 
![github_attach](https://user-images.githubusercontent.com/853706/37253326-98e9549e-2530-11e8-833f-f6c813a06a18.png)

> I try to install Rhythmbox via Flatpak and it have same problem, so seems this is a system problem with flatpak, not in Nuvola Player. I'll try to fix it and post results here, if found something.

Could you [create a bug report in Flatpak repo](https://github.com/flatpak/flatpak/issues/new) and link it here? They might understand this issue better than me. I'm not so familiar with Flatpak sandbox internals.

**Comment by MurzNN** [comment]
I revert pulseaudio on my system from system-wide daemon to per-user, and sounds becomes work! [Here](https://rudd-o.com/linux-and-free-software/how-to-make-pulseaudio-run-once-at-boot-for-all-your-users) is manual how to make pulseaudio system-wide and we can revert back via same commands.
Seems this is Flatpak issue, but I post here to if any other user got same problems with Nuvola Apps.
