### ISSUE TITLE
Start-up Check stuck on "XDG Desktop Portal In Progress"

### ISSUE THREAD

**Issue by andrewazores** [tiliado/nuvolaruntime#419]
Using Flatpak to run Nuvola Google Play Music (`flatpak run eu.tiliado.NuvolaAppGooglePlayMusic`), the start-up check window appears and gets stuck on this state, seemingly indefinitely:

![screenshot_2018-04-08_12-24-13](https://user-images.githubusercontent.com/3787464/38469750-c7a1e83e-3b27-11e8-916c-9dc1d61770d3.png)

I am on Arch Linux, kernel `4.15.15-1-ck-nehalem` x86_64, and use i3 window manager without any DE.

`flatpak --version`
Flatpak 0.11.3

`flatpak info eu.tiliado.Nuvola`
Ref: app/eu.tiliado.Nuvola/x86_64/stable
ID: eu.tiliado.Nuvola
Arch: x86_64
Branch: stable
Origin: eu.tiliado.Nuvola-origin
Collection ID: 
Date: 2018-04-02 12:17:45 +0000
Subject: Import nuvola 4.10.0.23
Commit: 4da540e875fe080d3dda64757c7f36097697b2d17ac22db8a96c6bb56a479b8a
Parent: 52b91f5591001b052e48cefb7ba3d8c765cfb62b97df5b929d05f682b696f79b
Location: /var/lib/flatpak/app/eu.tiliado.Nuvola/x86_64/stable/4da540e875fe080d3dda64757c7f36097697b2d17ac22db8a96c6bb56a479b8a
Installed size: 257.8 MB
Runtime: org.gnome.Platform/x86_64/3.26

`flatpak info eu.tiliado.NuvolaAppGooglePlayMusic`
Ref: app/eu.tiliado.NuvolaAppGooglePlayMusic/x86_64/stable
ID: eu.tiliado.NuvolaAppGooglePlayMusic
Arch: x86_64
Branch: stable
Origin: eu.tiliado.NuvolaAppGooglePlayMusic-origin
Collection ID: 
Date: 2018-04-02 12:23:11 +0000
Subject: Import google-play-music 6.0.5
Commit: 93d7a0356f7f280f5143de17fefca10eee2c2e3c3a25808dd5a110fb4d303315
Parent: 637226d66b75da5cf8d878a08d99a604344292d082264e94283b3a358618fc1e
Location: /var/lib/flatpak/app/eu.tiliado.NuvolaAppGooglePlayMusic/x86_64/stable/93d7a0356f7f280f5143de17fefca10eee2c2e3c3a25808dd5a110fb4d303315
Installed size: 257.8 MB
Runtime: org.gnome.Platform/x86_64/3.26

`flatpak info org.gnome.Platform`
Ref: runtime/org.gnome.Platform/x86_64/3.26
ID: org.gnome.Platform
Arch: x86_64
Branch: 3.26
Origin: gnome
Collection ID: 
Date: 2018-04-01 15:13:02 +0000
Subject: build of org.gnome.Sdk, Sun Apr  1 13:29:17 UTC 2018
Commit: 898993d70416a8f681e8d72045f38cbbb7d8a53d36ee9f13f0e7f73a77d92093
Parent: 6b68390f627e7875f1f1f738451526f7131a561b7795e95c272acd59ae9a5354
Location: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.26/898993d70416a8f681e8d72045f38cbbb7d8a53d36ee9f13f0e7f73a77d92093
Installed size: 785.1 MB

`pacman -Q | grep xdg-desktop`
xdg-desktop-portal 0.10-1
xdg-desktop-portal-gtk 0.10-1

**Comment by fenryxo** [comment]
Hello @andrewazores. Thanks for taking the time to report your issue. I need more information to investigate it further: Could you [attach debugging output](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#debugging-output)? Thanks.

**Comment by andrewazores** [comment]
Following those directions, when I run the first command (`flatpak run eu.tiliado.Nuvola --debug`), I simply get the output `Error: No command specified. Type `nuvolactl --help` for help. Launching service info...` and the service window appears.

The debug output for the Google Play Music app (`flatpak run eu.tiliado.NuvolaAppGooglePlayMusic --debug`) is attached.
[google_play_music_debug.txt](https://github.com/tiliado/nuvolaruntime/files/1897174/google_play_music_debug.txt)

**Comment by fenryxo** [comment]
> Following those directions, when I run the first command (`flatpak run eu.tiliado.Nuvola --debug`), I simply get the output `Error: No command specified. Type `nuvolactl --help` for help. Launching service info...` and the service window appears.

Oh, sorry, that instructions need to be updated.

> The debug output for the Google Play Music app (`flatpak run eu.tiliado.NuvolaAppGooglePlayMusic --debug`) is attached.

Here we have the villain.
 
`Runner: [CRITICAL Δ29s791197us DioriteGlib] file Dbus.c: line 685: unexpected error: Error calling StartServiceByName for org.freedesktop.portal.Desktop: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.portal.Desktop': timed out (service_start_timeout=120000ms) (g-dbus-error-quark, 20)`

```
if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
	if (_data_->_inner_error_->domain == G_IO_ERROR) {
		goto __catch9_g_io_error;
	}
	g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
	g_clear_error (&_data_->_inner_error_);
	g_object_unref (_data_->_async_result);
	return FALSE;
}
```

I've just committed a fix. Will be released with the next rebuild of the Flatpak packages, probably tomorrow.

**Comment by fenryxo** [comment]
Does Nuvola 4.10.26 make any difference?

**Comment by andrewazores** [comment]
The "In Progress" eventually becomes an "Error", but this still leaves me unable to use the Google Play Music web app on this machine. Is there some configuration I need to do for the XDG Desktop Portal so that the Nuvola Runtime can connect to it?

**Comment by fenryxo** [comment]
Could you provide me with a new log of `flatpak run eu.tiliado.NuvolaAppGooglePlayMusic --debug` to find out the cause of the error?

**Comment by fenryxo** [comment]
If the log says something about a timeout: There should be a file `/usr/share/dbus-1/services/org.freedesktop.portal.Desktop.service`. Could you check that the command in the exec field (`/usr/lib/xdg-desktop-portal/xdg-desktop-portal` in my case) starts correctly? Run it as a regular user (not root) as it's a user session service (not a system one).

```
$ cat /usr/share/dbus-1/services/org.freedesktop.portal.Desktop.service 
[D-BUS Service]
Name=org.freedesktop.portal.Desktop
Exec=/usr/lib/xdg-desktop-portal/xdg-desktop-portal
SystemdService=xdg-desktop-portal.service
```

**Comment by andrewazores** [comment]
I'm away from home (where I left the machine where I can reproduce this), but I will get back to you with a new debug output and check on the desktop portal service in the next day or two.

**Comment by andrewazores** [comment]
The log does now eventually (after several minutes) say something about a timeout:

`Runner: [WARNING Δ04m08s119745us Nuvola] StartupWindow.vala:205: xdg-desktop-portal-message: Error calling StartServiceByName for org.freedesktop.portal.Desktop: Timeout was reached`

Full log is attached.
[nuvola-log-2.txt](https://github.com/tiliado/nuvolaruntime/files/1921554/nuvola-log-2.txt)

My Desktop.service file looks like this:

```
$ cat /usr/share/dbus-1/services/org.freedesktop.portal.Desktop.service 
[D-BUS Service]
Name=org.freedesktop.portal.Desktop
Exec=/usr/lib/xdg-desktop-portal
SystemdService=xdg-desktop-portal.service
```

`/usr/lib/xdg-desktop-portal` looks like a sane path:

```
$ ls -l /usr/lib/xdg-desktop-portal
-rwxr-xr-x 1 root root 589776 Feb 14 10:17 /usr/lib/xdg-desktop-portal
```

However when executing this as my normal user,

```
$ /usr/lib/xdg-desktop-portal

** (/usr/lib/xdg-desktop-portal:14108): WARNING **: 16:57:33.152: Failed to create file chooser proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gtk: Timeout was reached

(/usr/lib/xdg-desktop-portal:14108): GLib-GIO-CRITICAL **: 16:57:33.152: g_dbus_interface_skeleton_set_flags: assertion 'G_IS_DBUS_INTERFACE_SKELETON (interface_)' failed

(/usr/lib/xdg-desktop-portal:14108): GLib-GObject-WARNING **: 16:57:33.152: invalid (NULL) pointer instance

(/usr/lib/xdg-desktop-portal:14108): GLib-GObject-CRITICAL **: 16:57:33.152: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(/usr/lib/xdg-desktop-portal:14108): GLib-GIO-CRITICAL **: 16:57:33.152: g_dbus_interface_skeleton_export: assertion 'G_IS_DBUS_INTERFACE_SKELETON (interface_)' failed
Segmentation fault (core dumped)
```

Digging in a little,

```
$ cat /usr/share/dbus-1/services/org.freedesktop.impl.portal.desktop.gtk.service
[D-BUS Service]
Name=org.freedesktop.impl.portal.desktop.gtk
Exec=/usr/lib/xdg-desktop-portal-gtk
SystemdService=xdg-desktop-portal-gtk.service
```

I tried running `/usr/lib/xdg-desktop-portal-gtk`, then `/usr/lib/xdg-desktop-portal`, and finally `flatpak run eu.tiliado.NuvolaAppGooglePlayMusic`, and the Nuvola Google Play Music web-app started up nearly immediately! Music playback works fine and I was able to connect my tiliado account as well. I have a warning message and inability to enable media key handling because of a missing Nuvola Apps Service. I see instructions for installing this service [here](https://nuvola.tiliado.eu/nuvola/ubuntu/) for Ubuntu, but it is not mentioned for Arch. Is this just missing documentation?

Anyway, with this new lead for the desktop portal services not starting, I'll try to find what I'm missing to make this work since it's definitely no longer a Nuvola bug at this point. I'll come back shortly and comment again on this issue with my findings, hopefully this will be useful knowledge that you can add to the installation docs or something for any other users who run very minimal desktop environments like I have on this machine.

**Comment by andrewazores** [comment]
This looks related if not the actual root cause: https://github.com/flatpak/xdg-desktop-portal-gtk/issues/107 . Trying it out now.

**Comment by andrewazores** [comment]
Solved with the comment linked from that issue I just linked above. I can now just do `flatpak run eu.tiliado.NuvolaAppGooglePlayMusic` and Nuvola appears very quickly. Media key handling can now also be enabled (?), but doesn't seem to work. I'll play with that some more and if I can't get it working, I may file a new issue.

**Comment by fenryxo** [comment]
> I have a warning message and inability to enable media key handling because of a missing Nuvola Apps Service. I see instructions for installing this service here for Ubuntu, but it is not mentioned for Arch. Is this just missing documentation?

The documentation is being updated (#423). The section "Install Nuvola Apps Runtime" of Arch Linux instructions installs the Nuvola Apps Service.
