### ISSUE TITLE
Nuvola 4.10.x

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaruntime#427]
* March 4 - Initial release: [Nuvola 4.10 Uses Chromium Engine for Spotify, Deezer, YouTube, Mixcloud, and BBC iPlayer to Play Without Flash Plugin](https://medium.com/nuvola-news/nuvola-4-10-da46a5088c94)
* March 22 - Update: [Nuvola Adds Detection of Headphones and Changes Approach to GTK Theming](https://medium.com/nuvola-news/nuvola-adds-detection-of-headphones-and-changes-approach-to-gtk-theming-274cab6772fe)
* April 3 - Update: [Nuvola 4.10.23 Updates 8tracks, Bandcamp, Google Play Music, and Google Calendar](https://medium.com/nuvola-news/nuvola-4-10-23-325c54a9d494)
* April 22 - Update X1: [Nuvola 4.10.29 Supports Ubuntu 18.04; Updates OwnCloud Music, Plex Music, Pocket Casts, and SiriusXM](https://medium.com/nuvola-news/nuvola-4-10-29-784f90063b44)
* May 6 - Update X2: [Nuvola Updates Amazon Cloud Player, BBC iPlayer & Jupiter Broadcasting; Supports Fedora 28](https://medium.com/nuvola-news/nuvola-updates-amazon-cloud-player-bbc-iplayer-jupiter-broadcasting-supports-fedora-28-38c809a08639)
* May 8 - [Draft - Nuvola 4.11.0 Released](https://medium.com/nuvola-news/nuvola-4-11-0-released-1aecb90a2fb9)
* May 20 - Update X3

**Comment by fenryxo** [comment]
* Update X2: [draft](https://medium.com/@fenryxo/nuvola-updates-amazon-cloud-player-bbc-iplayer-jupiter-broadcasting-38c809a08639)

Hello @a-m-s. Could you provide me with a representative screenshot of Nuvola window with Jupiter Broadcasting showing the selector? Could you also review the sections about your scripts in the announcement draft linked above? Thanks :-)

**Comment by a-m-s** [comment]
Here's some snapshots. One with the roll-over, and one with the drop-down open.
![screenshot from 2018-04-30 13-58-45](https://user-images.githubusercontent.com/5088295/39429363-95d77e6a-4c82-11e8-96b1-7553223ee271.png)
![screenshot from 2018-04-30 13-58-51](https://user-images.githubusercontent.com/5088295/39429367-99eb2fc4-4c82-11e8-8281-22f1843e3537.png)

The draft seems accurate, although the Amazon support statement is possibly unnecessarily aggressive. Maybe it's just enough to say "Amazon support could not say when Flash will no longer be required."

**Comment by a-m-s** [comment]
BTW, I had use gnome-snapshot in whole-screen mode to capture the drop-down.

**Comment by fenryxo** [comment]
Thanks. There was a misunderstanding. This time I need a full screenshot including window decorations etc. Could you do that?

**Comment by a-m-s** [comment]
How's this?
![jb-selector](https://user-images.githubusercontent.com/5088295/39473356-534e3344-4d46-11e8-9c8c-3d56e54cba8d.png)

**Comment by fenryxo** [comment]
That's good. If you wish to add screenshots also for Amazon or BBC iPlayer, you can post them here.

**Comment by a-m-s** [comment]
Amazon and BBC are just the original websites with nothing visible added.

For Jupiter Broadcasting, however, we also have new progress bars:
![jb-progress](https://user-images.githubusercontent.com/5088295/39474883-e99c0eaa-4d4d-11e8-94e9-197c67e41fcc.png)

**Comment by a-m-s** [comment]
BTW, there's still one JB bug I was going to fix before asking you to do a release.

**Comment by a-m-s** [comment]
OK, I think it's all done now. I added some missing sites to the selector, so here's an updated screenshot.
![jb-selector](https://user-images.githubusercontent.com/5088295/39497328-b40c2bf6-4d9a-11e8-9f6e-610d53dce460.png)

**Comment by fenryxo** [comment]
OK, I will release the announcement on Sunday, but formal releases of the scripts (as in "X.Y.0 release") will happen with Nuvola 4.11.0.

**Comment by fenryxo** [comment]
* Released: May 6 - Update X2: [Nuvola Updates Amazon Cloud Player, BBC iPlayer & Jupiter Broadcasting; Supports Fedora 28](https://medium.com/nuvola-news/nuvola-updates-amazon-cloud-player-bbc-iplayer-jupiter-broadcasting-supports-fedora-28-38c809a08639)
* Draft: May 8 - [Draft - Nuvola 4.11.0 Released](https://medium.com/nuvola-news/nuvola-4-11-0-released-1aecb90a2fb9)

**Comment by fenryxo** [comment]
Released: May 8 - [Nuvola 4.11.0 Released](https://medium.com/nuvola-news/nuvola-4-11-0-released-1aecb90a2fb9)
