### ISSUE TITLE
Can't run any plugin from console for debugging

### ISSUE THREAD

**Issue by martinkg** [tiliado/nuvolaruntime#437]
Hi,

i tried to run my installed plugins from console, but there is no debugging information.

nuvolaruntime -V -v -D -a /usr/share/nuvolaruntime/web_apps/bandcamp
Runner: [WARNING Δ125270us Nuvola] WebApp.vala:253: No requirements specified. 'Feature[flash] Codec[mp3]' used by default but that may change in the future.
Bandcamp script
Version: 2.2.0
Revision: unknown
Maintainer: Jiří Janoušek

--- Powered by ---

Web Apps - based on Nuvola Apps™ project
Version 4.11.0
Revision snapshot
Diorite 4.11.0
WebKitGTK 2.20.1
Chromium N/A
libsoup 2.62.1

nuvolaruntime -V -v -D -a /usr/share/nuvolaruntime/web_apps/spotify
Spotify script
Version: 3.0.0
Revision: unknown
Maintainer: Jiří Janoušek

--- Powered by ---

Web Apps - based on Nuvola Apps™ project
Version 4.11.0
Revision snapshot
Diorite 4.11.0
WebKitGTK 2.20.1
Chromium N/A
libsoup 2.62.1

nuvolaruntime -V -v -D -a /usr/share/nuvolaruntime/web_apps/jango
Jango script
Version: 2.3.0
Revision: unknown
Maintainer: Stefano Bagnatica

--- Powered by ---

Web Apps - based on Nuvola Apps™ project
Version 4.11.0
Revision snapshot
Diorite 4.11.0
WebKitGTK 2.20.1
Chromium N/A
libsoup 2.62.1

nuvolaruntime -V -v -D -a /usr/share/nuvolaruntime/web_apps/deezer
Deezer script
Version: 2.7.0
Revision: unknown
Maintainer: Jiří Janoušek

--- Powered by ---

Web Apps - based on Nuvola Apps™ project
Version 4.11.0
Revision snapshot
Diorite 4.11.0
WebKitGTK 2.20.1
Chromium N/A
libsoup 2.62.1

nuvolaruntime -V -v -D -a /usr/share/nuvolaruntime/web_apps/jupiter_broadcasting
Jupiter Broadcasting script
Version: 1.2.0
Revision: unknown
Maintainer: Andrew Stubbs

--- Powered by ---

Web Apps - based on Nuvola Apps™ project
Version 4.11.0
Revision snapshot
Diorite 4.11.0
WebKitGTK 2.20.1
Chromium N/A
libsoup 2.62.1

nuvolaruntime -V -v -D -a /usr/share/nuvolaruntime/web_apps/amazon_cloud_player
Amazon Cloud Player script
Version: 5.7.0
Revision: unknown
Maintainer: Andrew Stubbs

--- Powered by ---

Web Apps - based on Nuvola Apps™ project
Version 4.11.0
Revision snapshot
Diorite 4.11.0
WebKitGTK 2.20.1
Chromium N/A
libsoup 2.62.1

nuvolaruntime -V -v -D -a /usr/share/nuvolaruntime/web_apps/bbc-iplayer
BBC iPlayer script
Version: 1.5.0
Revision: unknown
Maintainer: Andrew Stubbs

--- Powered by ---

Web Apps - based on Nuvola Apps™ project
Version 4.11.0
Revision snapshot
Diorite 4.11.0
WebKitGTK 2.20.1
Chromium N/A
libsoup 2.62.1

nuvolaruntime -V -v -D -a /usr/share/nuvolaruntime/web_apps/tunein
Runner: [WARNING Δ007845us Nuvola] WebApp.vala:253: No requirements specified. 'Feature[flash] Codec[mp3]' used by default but that may change in the future.
TuneIn script
Version: 1.3.0
Revision: unknown
Maintainer: Aurélien Jabot

--- Powered by ---

Web Apps - based on Nuvola Apps™ project
Version 4.11.0
Revision snapshot
Diorite 4.11.0
WebKitGTK 2.20.1
Chromium N/A
libsoup 2.62.1

nuvolaruntime -V -v -D -a /usr/share/nuvolaruntime/web_apps/youtube
YouTube script
Version: 2.0.0
Revision: unknown
Maintainer: Jiří Janoušek

--- Powered by ---

Web Apps - based on Nuvola Apps™ project
Version 4.11.0
Revision snapshot
Diorite 4.11.0
WebKitGTK 2.20.1
Chromium N/A
libsoup 2.62.1

nuvolaruntime -V -v -D -a /usr/share/nuvolaruntime/web_apps/owncloud_music
ownCloud Music script
Version: 1.2.0
Revision: unknown
Maintainer: Jiří Janoušek

--- Powered by ---

Web Apps - based on Nuvola Apps™ project
Version 4.11.0
Revision snapshot
Diorite 4.11.0
WebKitGTK 2.20.1
Chromium N/A
libsoup 2.62.1

nuvolaruntime -V -v -D -a /usr/share/nuvolaruntime/web_apps/google_play_music
Google Play Music script
Version: 6.0.0
Revision: unknown
Maintainer: Jiří Janoušek

--- Powered by ---

Web Apps - based on Nuvola Apps™ project
Version 4.11.0
Revision snapshot
Diorite 4.11.0
WebKitGTK 2.20.1
Chromium N/A
libsoup 2.62.1

nuvolaruntime -V -v -D -a /usr/share/nuvolaruntime/web_apps/8tracks
Runner: [WARNING Δ036381us Nuvola] WebApp.vala:253: No requirements specified. 'Feature[flash] Codec[mp3]' used by default but that may change in the future.
8tracks script
Version: 5.2.0
Revision: unknown
Maintainer: Jiří Janoušek

--- Powered by ---

Web Apps - based on Nuvola Apps™ project
Version 4.11.0
Revision snapshot
Diorite 4.11.0
WebKitGTK 2.20.1
Chromium N/A
libsoup 2.62.1

nuvolaruntime -V -v -D -a /usr/share/nuvolaruntime/web_apps/mixcloud
Mixcloud script
Version: 4.1.0
Revision: unknown
Maintainer: Jiří Janoušek

--- Powered by ---

Web Apps - based on Nuvola Apps™ project
Version 4.11.0
Revision snapshot
Diorite 4.11.0
WebKitGTK 2.20.1
Chromium N/A
libsoup 2.62.1

**Comment by fenryxo** [comment]
That's correct behavior as `nuvolaruntime -V` means print version and exit. See `nuvolaruntime --help`.   Use `nuvolaruntime -D -a ...`.
