### ISSUE TITLE
Add Unity AppIndicator

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaruntime#45]
From [Launchpad bug #1130245](https://bugs.launchpad.net/nuvola-player/+bug/1130245) by Maikel:

Unity doesn't support sys tray icons, add support for AppIndicator instead.

:heart: **One [Nuvola Patron](https://tiliado.eu/nuvolaplayer/funding/) is interested in this feature.** Internal info: [(1)](https://tiliado.eu/admin/tiliado_funding/patron/1/).

**Comment by regisz** [comment]
This feature would be great, it is missing very much for me :(.

**Comment by fenryxo** [comment]
Hello @regisz. Would you like to sponsor development of this feature then?

**Comment by regisz** [comment]
ok, maybe :). How much bounty is required for this feature?

**Comment by fenryxo** [comment]
Hello @regisz. There used to be AppIndicator support in Nuvola Player but it was disabled because of some issues and the code became unmaintained and broken (#201). It might take an hour (€15) to get the old code work again and another hour to address the issues (€15) providing there are no obstacles. The process is a bit complicated by the fact that I don't use Ubuntu on my development machine, so all development will have to occur in Ubuntu in VirtualBox.

Hello @susnux. You were interested in libappindicator support in #201. Would you like to join @regisz to fund a comeback of this feature?

**Comment by fenryxo** [comment]
:heart: **One [Nuvola Patron](https://tiliado.eu/nuvolaplayer/funding/) is interested in this feature.** As a result, the ticket has been moved from the "postponed" queue to the "ready" queue and the "patron" label has been attached.

**Comment by fenryxo** [comment]
In progress: https://github.com/tiliado/nuvolaplayer/tree/appindicator

**Comment by regisz** [comment]
cool, I'm waiting this feature :)!

2016-11-26 22:04 GMT+01:00 Jiří Janoušek <notifications@github.com>:

**Comment by fenryxo** [comment]
Hello @regisz. I apologize for not finishing this feature yet. It turned out to have been more difficult that I had expected. The top priority for now is to release stable flatpak builds of Nuvola 3.1. Thrn I might get back to this issue.

**Comment by fenryxo** [comment]
Hello @regisz. With Nuvola 3.1.3 flatpaks in the wild, I can finally return to this issue.

**Comment by fenryxo** [comment]
Rebased on master: https://github.com/tiliado/nuvolaplayer/tree/appindicator2

**Comment by regisz** [comment]
@fenryxo thx :)
Can I installed (used flatpak) this branch?

**Comment by fenryxo** [comment]
No, this branch has not been merged to master as it is still incomplete. It should be included in Nuvola 3.1.4 later this month.

**Comment by fenryxo** [comment]
Remaining issues:
- [ ] Wrong icon.
- [ ] Insensitive actions.

**Comment by fenryxo** [comment]
![appindicator setting](https://cloud.githubusercontent.com/assets/853706/25754685/70a527ec-31c0-11e7-9b04-d6655bb9fda5.png)

**Comment by fenryxo** [comment]
ElementaryOS:
![eos_loki update2 running - oracle vm virtualbox_157](https://cloud.githubusercontent.com/assets/853706/25778705/994cfef8-3306-11e7-9f5b-a4c2a83430bf.png)

Ubuntu 17.04:
![u17 04 update3 running - oracle vm virtualbox_159](https://cloud.githubusercontent.com/assets/853706/25778707/a45a7c9e-3306-11e7-8cf2-1c87a709c2e1.png)

Fedora 25:
![f25 update1 running - oracle vm virtualbox_163](https://cloud.githubusercontent.com/assets/853706/25778854/7a1a30f6-330a-11e7-821d-3d4958e1e2da.png)

**Comment by fenryxo** [comment]
Final tasks:

- [ ] Documentation: Unity
- [ ] Documentation: GNOME Shell
- [ ] Documentation: elementaryOS
- [ ] Push to the stable repo

**Comment by fenryxo** [comment]
Pushed to the stable repo.  Run `flatpak update --system` or `flatpak update --user`, depending on how you have installed Nuvola Apps.

Instructions & Screenshots:

*  [Ubuntu's Unity](https://tiliado.github.io/nuvolaplayer/documentation/3.1/explore.html#appindicator-and-tray-icon)
 * [elementaryOS](https://tiliado.github.io/nuvolaplayer/documentation/3.1/explore.html#appindicator-and-tray-icon_2)
 * [GNOME Shell](https://tiliado.github.io/nuvolaplayer/documentation/3.1/explore.html#appindicator-and-tray-icon_1)
