### ISSUE TITLE
Add Flash plugin installer

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaruntime#458]
Nuvola Flatpaks now bundle the Flash plugin. It should be downloaded and installed only when necessary similarly to Widevine plugin.

**Comment by fenryxo** [comment]
Hello @ams,

The master branch of Nuvola flatpaks has introduced a Flash plugin installer, i.e., the Flash plugin bundled with Nuvola is no longer used (will be eventually removed because I don't have a license for redistribution), but it is downloaded from Adobe instead. Could you check that your apps work with this change? Nuvola version should be >= 4.12.80 (80-g25fb9c6). Thanks :-)

```
flatpak update
flatpak install nuvola eu.tiliado.NuvolaAppBbcIplayer//master
flatpak install nuvola eu.tiliado.NuvolaAppAmazonCloudPlayer//master
flatpak run eu.tiliado.NuvolaAppBbcIplayer//master -D
flatpak run eu.tiliado.NuvolaAppAmazonCloudPlayer//master -D
```

As a bonus, the Flash plugin is always updated to the latest version.

**Comment by ams** [comment]
Hi @fenryxo,  I am not sure why I am notified.  But I do not support nor use non-free software, it is is unethical and immoral to subjugate computer users right to use their computers.  If you'd like to learn more about free software then the GNU project has lots of information about it (e,g, https://www.gnu.org/philosophy/free-sw.en.html).

**Comment by fenryxo** [comment]
Hello @ams, sorry for the noise, it was a mistake. The message was for @a-m-s.

Hello @a-m-s, this time the right one :-) Could you look at https://github.com/tiliado/nuvolaruntime/issues/458#issuecomment-419729281 Thanks.

**Comment by a-m-s** [comment]
@ams Nuvola is both open source and free using a BSD license. The FSF would prefer a copyleft license, but even they agree that @fenryxo is entitled to sell his binary builds for a fee.

@fenryxo I did flatpak instructions, started the Master app, and the flash install seems to go smoothly. Amazon Music plays fine too.

The BBC radio player appears to have changed to HTML5. It looks like I need to update the integration. It's possible that we can drop the Flash dependency from this app.

**Comment by fenryxo** [comment]
> [...] and the flash install seems to go smoothly. Amazon Music plays fine too.

Great, I'll push the changes to the stable branch then.

> The BBC radio player appears to have changed to HTML5. It looks like I need to update the integration. It's possible that we can drop the Flash dependency from this app.

That would be cool :-)

**Comment by ams** [comment]
> @ams Nuvola is both open source and free using a BSD license. The FSF would prefer a copyleft license, but even they agree that @fenryxo is entitled to sell his binary builds for a fee.

Adobe Flash is definitely not free software, and Adobe is immensely hostile to free software.  It would be better to drop such support than to add it.

**Comment by fenryxo** [comment]
> Adobe Flash is definitely not free software, and Adobe is immensely hostile to free software. It would be better to drop such support than to add it.

I'm not adding support for Flash plugin as it's already there. I'm merely improving the security by providing automatic updates of the plugin.

Of course, the long-term goal is to drop support of Flash plugin eventually. There are 25 music streaming services supported by Nuvola Apps Runtime, only two of them require Flash and BBC iPlayer might join the no-Flash party soon. Anyway, it's up to the user to decide what streaming service to use. They are warned that Flash plugin is proprietary.

**Comment by fenryxo** [comment]
Announced in Update 10: [Nuvola Integrates Repeat & Shuffle Status, Adjusts to New Deezer Design, And More](https://medium.com/nuvola-news/nuvola-integrates-repeat-shuffle-status-adjusts-to-new-deezer-design-and-more-397d3bc1e03a)
