### ISSUE TITLE
Can't Install Nuvola on Linux Mint 19

### ISSUE THREAD

**Issue by mfreeman72** [tiliado/nuvolaruntime#460]
I'm trying to install Nuvola on Linux Mint 19. I can't seem to access your flathub repo for it. The Mint Software Manager couldn't add the repo. It gave me an error (I can't remember which, now). I could add it through the terminal by the instructions on your site, but trying to install Nuvola, I get this error:

```
Required runtime for eu.tiliado.Nuvola/x86_64/stable (org.gnome.Platform/x86_64/3.28) is not installed, searching...
The required runtime org.gnome.Platform/x86_64/3.28 was not found in a configured remote.
error: The Application eu.tiliado.Nuvola/x86_64/stable requires the runtime org.gnome.Platform/x86_64/3.28 which is not installed
```

So I'm stuck. What I wouldn't give for a good old-fashioned .deb file! While I understand why they are attractive to devs, I seriously hate all these new flatpaks/snaps/appimages/whatever else will be invented to reinvent the wheel. They're just exacerbating the problem for users. I just want one way to install and manage software that just works, not four or more that may or may not work!

**Comment by fenryxo** [comment]
Hello @mfreeman72. Thanks for reporting this issue.

> The Mint Software Manager couldn't add the repo. It gave me an error (I can't remember which, now).

If you happen to catch the error in the future, please report it. That's the only way and can investigate it and fix it.

> The required runtime org.gnome.Platform/x86_64/3.28 was not found in a configured remote.

As [per instructions](https://nuvola.tiliado.eu/nuvola/ubuntu/bionic/), you need to add [Flathub repository](https://flathub.org/home) first. Let me know if it works:

```
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
```

As explained in the instructions, Nuvola uses the GNOME Platform runtime from that repository to share common dependencies with other Flatpak apps to reduce disk & memory usage. 

> What I wouldn't give for a good old-fashioned .deb file! While I understand why they are attractive to devs, I seriously hate all these new flatpaks/snaps/appimages/whatever else will be invented to reinvent the wheel. They're just exacerbating the problem for users. I just want one way to install and manage software that just works, not four or more that may or may not work!

Unfortunately, I don't know how to create debs for Nuvola without huge sacrifices regarding Nuvola features and quality. *I tried and failed.* For example, Fedora provides native RPM packages, but they've disabled a few features and use the old WebKitGTK-based backend. That means some services don't work at all (e.g., Spotify, Youtube) and others use Flash plugin for audio playback. However, Nuvola is open source, so you can ask anynone more skilled than me to create debs, e.g. Linux Mint developers.

**Comment by fenryxo** [comment]
Probably solved.
