### ISSUE TITLE
I can't sing in my TuneIn via google account

### ISSUE THREAD

**Issue by artyomsazonov** [tiliado/nuvolaruntime#465]
I tried to sign in TineIn via google account but, unfortunately nothing happens, I just see "Sing In" window

**Comment by fenryxo** [comment]
Hello @artyomsazonov. Thanks for taking the time to report your issue. I need more information to investigate it further:

* Which [distribution and version](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#your-system) do you use?
* Which [version of Nuvola](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#your-nuvola-version) do you use?
* The debugging output from a terminal as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output).

**Comment by fenryxo** [comment]
> I tried to sign in TineIn via google account but, unfortunately nothing happens, I just see "Sing In" window

I cannot reproduce this with Nuvola 4.12.89 (89-g6488610). Since the reporter haven't provided any follow-up information, I cannot do anything else than to consider this issue as resolved.
