### ISSUE TITLE
Deezer: Media keys not working

### ISSUE THREAD

**Issue by guiAlberto** [tiliado/nuvolaruntime#468]
### Basic information

- Your Linux distribution and its version: Ubuntu 16.04.5 LTS
   

- Your desktop environment: Unity
   

 - Nuvola Runtime version: 4.12.46 (46-g1482aea)
   

 - The web app you use and its version: Deezer 3.0.9 (9-g30dcb32)
   

### Describe the bug

Media keys not working and media actions disabled at top bar (Play, Previous song, Next song, Favorite track)

**Steps to reproduce the behavior**

1. Open a terminal and type `flatpak run eu.tiliado.NuvolaAppDeezer`
2. Wait for the app to start
3. Click on "play/pause" media button
4. Terminal shows the following message:

> Runner: [WARNING Δ08s452965us Nuvola] Binding.vala:86: Call Web Worker sync: Nuvola.mediaKeys.emit
> Runner: [WARNING Δ001246us DioriteGtk] Action.vala:74: Cannot activate action 'toggle-play', because it is disabled.

5. Music won't play/pause. Same thing happens when "next track" and "previous track" media buttons, and terminal show the following messages:

> Runner: [WARNING Δ03s765714us Nuvola] Binding.vala:86: Call Web Worker sync: Nuvola.mediaKeys.emit
> Runner: [WARNING Δ001525us DioriteGtk] Action.vala:74: Cannot activate action 'next-song', because it is disabled.

> Runner: [WARNING Δ14s833314us Nuvola] Binding.vala:86: Call Web Worker sync: Nuvola.mediaKeys.emit
> Runner: [WARNING Δ001843us DioriteGtk] Action.vala:74: Cannot activate action 'prev-song', because it is disabled.

6. Also, when the top panel icon is clicked, the options "Play", "Previous song", "Next song" and "Favorite track" are disabled, but "Activate main window" and "Quit" are enabled.

**Expected behavior**

Media keys working and media options enabled at top panel.

**Debugging log**

Attach the debug log here: ...

**Screenshots**

(https://github.com/tiliado/nuvolaruntime/files/2380670/deezer.log)

Attach screenshots here: ...

![screenshot from 2018-09-13 16-09-48](https://user-images.githubusercontent.com/18057706/45510061-8b3bb900-b76f-11e8-9ca1-375be3f2f910.png)

**Additional context**

...

**Comment by fenryxo** [comment]
Hello @guiAlberto. Thanks for reporting this issue. Do you use the **new Deezer design**? If yes, it is not supported yet. I'm going to look at it at the weekend. Meanwhile, you can switch back to the supported old design: Click your profile avatar in the top right corner → Deezer Labs → Deactivate Try a new look.

**Comment by guiAlberto** [comment]
> Hello @guiAlberto. Thanks for reporting this issue. Do you use the **new Deezer design**? If yes, it is not supported yet. I'm going to look at it at the weekend. Meanwhile, you can switch back to the supported old design: Click your profile avatar in the top right corner → Deezer Labs → Deactivate Try a new look.

Thanks @fenryxo, I have changed the design and it works perfectly

**Comment by fenryxo** [comment]
This issue was fixed in **Nuvola 4.12.89** & **Deezer script 3.0.14**. You can update flatpaks with GNOME Software >= 3.22 or run `flatpak update --system; flatpak update --user` in a terminal.

*Keep this ticket open until the fix is officially announced.*

**Comment by Evpok** [comment]
Fix confirmed working, thanks for the prompt fix !

**Comment by fenryxo** [comment]
Announced in Update 10: [Nuvola Integrates Repeat & Shuffle Status, Adjusts to New Deezer Design, And More](https://medium.com/nuvola-news/nuvola-integrates-repeat-shuffle-status-adjusts-to-new-deezer-design-and-more-397d3bc1e03a)
