### ISSUE TITLE
cast to tv

### ISSUE THREAD

**Issue by washi6450** [tiliado/nuvolaruntime#470]
**Is your feature request related to a problem? Please describe:**

A clear and concise description of what the problem is. Ex. I have an issue when [...]

**Describe the solution you'd like:**

A clear and concise description of what you want to happen. What are the benefits and drawbacks?

**Describe alternatives you've considered:**

**Additional context:**

**Comment by fenryxo** [comment]
Hello @washi6450. It seems you forgot to fill in the details of your feature request. Could you do that?
