### ISSUE TITLE
Release Nuvola 4.13

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaruntime#472]
Nuvola 4.12.0 was released on July 21st, 2018, and the micro version number is getting high (4.12.82). Let's release Nuvola 4.13.0.

Components:

* Nuvola Runtime 4.13.0
* Diorite 4.13.0
* Nuvola SDK 4.13.0
* Scripts: FIXME

**Comment by fenryxo** [comment]
Scripts to release:

- bbc iplayer 1.5-7-g3962815
- deezer 3.0-15-g8bcaea2
- amazon 5.7-9-gf3e7cce
- spotify 3.0-8-gbbd19f4
- soundcloud 1.4-5-g5922191
- plex 1.4-5-gc0b1031
- owncloud music 1.3-4-gb25aa5e
- jango 2.4-3-gf493ea4
- google play music 6.1-4-g181724d

**Comment by fenryxo** [comment]
- I need time to prepare my talk for [Linux Days](https://www.linuxdays.cz/2018/en/), so Nuvola 4.13 is postponed to Thursday October 11th or later.
- That way, we can also include the fix for #476 and finish tiliado/nuvolasdk#5.

**Comment by a-m-s** [comment]
I did my last planned update yesterday.

**Comment by fenryxo** [comment]
Great :+1:

**Comment by fenryxo** [comment]
[Released in Nuvola 4.13.0](https://medium.com/nuvola-news/nuvola-4-13-released-2fdf80c73742).
