### ISSUE TITLE
Can't log in to NPR One

### ISSUE THREAD

**Issue by dericke** [tiliado/nuvolaruntime#481]
### Basic information

- Your Linux distribution and its version: ...
Ubuntu 18.04

- Your desktop environment: ...
   GNOME

 - Nuvola Runtime version: ...
  4.14.1

 - The web app you use and its version: ...
  NPR One 1.1.2

### Describe the bug

Cannot log in to my NPR One account through the NPR One web app

**Steps to reproduce the behavior**

1. Open NPR One App
2. Click "Sign In"
3. The NPR sign-in flow opens in my web browser
4. Logging in to the web browser does not log me in within Nuvola

Attempting to open the sign-in URL in Nuvola using the "Load URL..." function also causes the same behavior.

**Expected behavior**

The NPR sign-in flow opens, and allows me to sign in to the web app and get my personalized feed.

**Comment by fenryxo** [comment]
Hello @dericke. Thanks for reporting the issue. It seems that the filter of external URLs needs to be adjusted.

**Comment by fenryxo** [comment]
The login page is: https://secure.npr.org/oauth2/login

**Comment by fenryxo** [comment]
Hello @dericke. Could you check NPR One script 1.1.4. Just published.

**Comment by dericke** [comment]
Sign-in is working great now, thanks!
