### ISSUE TITLE
I have a premium, prepaid nuvola account

### ISSUE THREAD

**Issue by shakedei** [tiliado/nuvolaruntime#492]
it keep showing me this message every time I try to install an app:
error: Unable to load summary from remote nuvola: GPG signatures found, but none are in trusted keyring

**Comment by shakedei** [comment]
sorry, I just found out the answer:)

**Comment by fenryxo** [comment]
Hello @shakedei. Thanks for purchasing Nuvola. I'm glad that you have found the answer. I'm closing this ticket but you can still comment if you need help.
