### ISSUE TITLE
Crash when opening Preferences

### ISSUE THREAD

**Issue by sebawild** [tiliado/nuvolaruntime#493]
### Basic information

- Your Linux distribution and its version: Ubuntu 18.04
   

- Your desktop environment: Unity   

 - Nuvola Runtime version: 4.14.6
   

 - The web app you use and its version: Google Calendar script 1.3.2
   

### Describe the bug

When I click on Preferences in the setting menu, the app crashes.

Terminal output:

Runner: [CRITICAL Δ05s741856us DioriteGlib] drt_variant_utils_to_strv: assertion 'variant != NULL' failed
Runner: [CRITICAL Δ000108us DioriteGlib] Application will not function properly.
Runner: [CRITICAL Δ000061us DioriteGlib] drt_variant_utils_to_strv: assertion 'variant != NULL' failed
Runner: [CRITICAL Δ000048us DioriteGlib] Application will not function properly.
Worker: [DEBUG Δ04s438064us DioriteGlib] DuplexChannel.vala:502: Channel (0) has been closed.
Worker: [DEBUG Δ000269us DioriteGlib] DuplexChannel.vala:328: The channel has already been closed

...

**Steps to reproduce the behavior**

1. Open app
2. Click on menu button (upper right corner)
3. Select Preferences.

**Comment by sebawild** [comment]
Just updated flatpaks; same issue

Nuvola Apps - Genuine flatpak build
Version 4.15.0
Revision 0-g06de715
Diorite 4.15.0
WebKitGTK 2.22.4
Chromium 70.0.3538.77
libsoup 2.64.2

**Comment by fenryxo** [comment]
Hello @sebawild. Thanks for reporting the issue. The fix is being built right now.

**Comment by fenryxo** [comment]
Could you test the latest stable build? It contains Nuvola 4.15.0 and Diorite 4.15.1.

**Comment by sebawild** [comment]
I installed the update and the preferences show up now.
Thanks, that was amazingly fast!

**Comment by fenryxo** [comment]
Released with **Nuvola 4.16.0**, more info: [Nuvola 4.16 Brings Libre.FM Scrobbling, Ivoox Service, and more](https://medium.com/nuvola-news/nuvola-4-16-86a089068784)
