### ISSUE TITLE
Add Ivoox integration

### ISSUE THREAD

**Issue by joshuac17** [tiliado/nuvolaruntime#494]
Hello Guys!

Do you have any plans to add ivoox to nuvola apps?

It would be nice if you can add it to nuvola. I hope that you add it.

Kind Regards.

---

There are many country variants (US: <https://us.ivoox.com/en/audios_sa_f_1.html>), so a country selector similar to that of Amazon Cloud Player integration should be provided.

**Comment by fenryxo** [comment]
Hello @joshuac17. Creating this ticket is the first step to get Ivoox integrated with Nuvola :-)

**Comment by fenryxo** [comment]
Hello @joshuac17, could you test it? Thanks :-)
 
* Flatpak: https://nuvola.tiliado.eu/app/ivoox/
* Source: https://github.com/tiliado/nuvola-app-ivoox

**Comment by joshuac17** [comment]
Tried to install but, I got the error shown in the screenshot. Not sure what to do.
![captura de pantalla de 2019-01-10 12-15-34](https://user-images.githubusercontent.com/40548732/50988326-f012e000-14d1-11e9-85ff-b6beb0612aef.png)

**Comment by joshuac17** [comment]
it worked!!! Thank you @fenryxo!! Keep it up the good job!!

**Comment by fenryxo** [comment]
Great :-) Happy listening!

**Comment by fenryxo** [comment]
Released with **Nuvola 4.16.0**, more info: [Nuvola 4.16 Brings Libre.FM Scrobbling, Ivoox Service, and more](https://medium.com/nuvola-news/nuvola-4-16-86a089068784)
