### ISSUE TITLE
Pocket Casts version 1.2.0 (0-g0cc91fd) not respecting media keys and tray options

### ISSUE THREAD

**Issue by aia832003** [tiliado/nuvolaruntime#500]
### Basic information

- Your Linux distribution and its version: Fedora 29

- Your desktop environment: Gnome Xorg session

 - Nuvola Runtime version: 4.15.3 (3-g5de0a02)

 - The web app you use and its version: Pocket Casts 1.2.0 (0-g0cc91fd)

### Describe the bug

Can't use the media keys on laptop, Gnome notification panel widget, or tray icon options. They work in other Nuvola apps for SiriusXM and Google Play Music, but not for Pocket Casts.

**Steps to reproduce the behavior**

**Expected behavior**

App should launch and play while presenting the notification area widget in Gnome, tray icon, and have appropriate input from hardware media keys.

**Debugging log**

[Pocket Casts output.txt](https://github.com/tiliado/nuvolaruntime/files/2776147/Pocket.Casts.output.txt)
![screenshot from 2019-01-19 18-57-48](https://user-images.githubusercontent.com/11007827/51433937-28c26000-1c1c-11e9-8cb8-74e225697b32.png)
![screenshot from 2019-01-19 18-57-53](https://user-images.githubusercontent.com/11007827/51433938-28c26000-1c1c-11e9-85b3-362e87526b72.png)

**Screenshots**

Attach screenshots here: ...

**Additional context**

...

**Comment by fenryxo** [comment]
Hello @aia832003. Thanks for taking the time to report your issue. I need more information to investigate it further. Could you provide me with the debugging output from a terminal as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output)? The output you attached is incomplete because you didn't use the `--debug` argument.

**Comment by aia832003** [comment]
I wish I could but the debug argument fails. I get that the flatpak for
Pocket Casts is not installed. Even though it is.

**Comment by aia832003** [comment]
Sorry Jiri...was forgetting the "s" on the end of the app name. Attached is a new output from debug and screenshots of the indicator and notification area not updating while app is playing. The last two screenshots are of Play Music app running on the same environment just for reference to a working app.pl
![screenshot from 2019-01-20 08-41-29](https://user-images.githubusercontent.com/11007827/51440751-e470a780-1c8f-11e9-97ab-6a13aac60931.png)
![screenshot from 2019-01-20 08-41-19](https://user-images.githubusercontent.com/11007827/51440752-e470a780-1c8f-11e9-89dd-0daa35d667e3.png)
[PocketCasts output.txt](https://github.com/tiliado/nuvolaruntime/files/2776714/PocketCasts.output.txt)

![screenshot from 2019-01-20 08-47-48](https://user-images.githubusercontent.com/11007827/51440779-1c77ea80-1c90-11e9-936f-f13dee0bc39e.png)
![screenshot from 2019-01-20 08-47-41](https://user-images.githubusercontent.com/11007827/51440780-1c77ea80-1c90-11e9-9522-9862ecaa39d2.png)

**Comment by aia832003** [comment]
Decided to check this against my Ubuntu install as well and have the same results with PocketCasts. Attaching that debug as well to see if that can help.
[PocketCasts debug Ubuntu.txt](https://github.com/tiliado/nuvolaruntime/files/2776840/PocketCasts.debug.Ubuntu.txt)

**Comment by fenryxo** [comment]
@aia832003, thanks for the logs. It seems that Pocket Casts switched the web interface: The beta version of the new player interface, previously used only for playbeta.pocketcasts.com, has become the new stable interface for play.pocketcasts.com.

Could you test **PocketCasts1.2.2 (2-gad9da92)** (just published)?

**Comment by aia832003** [comment]
Awesome as always Jiri. This looks to be fixed on both my machines!

Andrew Allen

**Comment by fenryxo** [comment]
Great :+1:
