### ISSUE TITLE
Flatpak not recognizing nvidia-410-79

### ISSUE THREAD

**Issue by matej14086** [tiliado/nuvolaruntime#501]
Hello,
when I try to open Deezer I get following error:

Graphics driver 'nvidia-410-79' for Flatpak has not been found on your system

but I have that driver version
![screenshot from 2019-01-26 22-07-55](https://user-images.githubusercontent.com/28957206/51792793-e4eccf00-21b6-11e9-81e7-c8aef07c5c3c.png)

**Comment by fenryxo** [comment]
Hello @matej14086. Yes, you have nvidia driver 410.79 on your system. However, it cannot be used by Flatpak applications as is. You need the same driver packaged as a Flatpak extension. Have you followed [the instructions for NVidia Proprietary Drivers](https://github.com/tiliado/nuvolaruntime/wiki/Graphics-Drivers)?

**Comment by matej14086** [comment]
Hi @fenryxo ,

I cannot change my nvidia driver because it would break my whole Tensorflow installation, which took me a whole day to get it working.
Can I force Flatpak to use 410.79 driver or is there some other workaround?

**Comment by fenryxo** [comment]
The usual approach is to [package the driver as a Flatpak extension](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia). However, the driver 410.79 is no longer available for [download from Nvidia](https://www.nvidia.com/object/linux-amd64-display-archive.html). That typically happens for beta releases and the Flathub team doesn't support beta versions for this reason.

There could be a workaround but it might be tricky: Could you create a directory `/var/lib/flatpak/extension/org.freedesktop.Platform.GL.nvidia-410-79/x86_64/1.4` with the following strucure?

```
├── glvnd
│   └── egl_vendor.d
│       └── 10_nvidia.json
├── lib
│   ├── libGLX_nvidia.so.410.79
│   └── ...
├── OpenCL
│   └── vendors
│       └── nvidia.icd
└── vulkan
    └── icd.d
        └── nvidia_icd.json
```

**Comment by fenryxo** [comment]
N. B. All files and directories must be copied, symlinks won't work as they would point to nothing in the sandbox.

**Comment by fenryxo** [comment]
Could you create an archive of the driver from your system and upload it somewhere? I might do some experiments with that on Thursday. Also, the output of `tree -pugh /var/lib/flatpak/extension/org.freedesktop.Platform.GL.nvidia-410-79/x86_64/1.4` might come in handy.

**Comment by fenryxo** [comment]
Hello. I'm cleaning stale tickets after the release of [Nuvola 4.16](https://medium.com/nuvola-news/nuvola-4-16-86a089068784). If this ticket still concerns you, feel free to reopen it.

**Comment by fenryxo** [comment]
Related: tiliado/nuvolaruntime#513 (Nvidia 418.40.04)
