### ISSUE TITLE
FreeBSD Support?

### ISSUE THREAD

**Issue by czbaker** [tiliado/nuvolaruntime#502]
I was just wondering if it's possible to get this working (Spotify, specifically) with FreeBSD.

I tried to install via Ports, but it's installing 3.x instead of 4.x (seems to be only available via Flatpak, which is Linux only?), and it crashes when I attempt to start it up.

Don't know if this is OS specific, but I can't get Spotify working under Nuvola at all.

![image](https://user-images.githubusercontent.com/8585575/52300581-384ce300-2956-11e9-9961-14b5b64f1abc.png)

I also get an error about not having a Flash Player plugin, but I have `www/flashplayer` installed from Ports.

Thoughts?

**Comment by fenryxo** [comment]
Hello @czbaker. Thanks for your interest in Nuvola.

> I was just wondering if it's possible to get this working (Spotify, specifically) with FreeBSD.

I don't know whether it is possible to get Nuvola 4.x working with FreeBSD as I have never tried that. If you can build [Chromium Embedded Framework](https://bitbucket.org/chromiumembedded/cef) in FreeBSD, then it should be possible to build Nuvola as well, maybe with some minor modifications to disable Linux-only stuff if there is any.

> I tried to install via Ports, but it's installing 3.x instead of 4.x (seems to be only available via Flatpak, which is Linux only?)

Nuvola 3.x was available as source code (for third-party packagers) and DEB/RPM packages (for users), Nuvola 4.x is available as source code (for third-party packagers) and Flatpak packages (for users). I guess FreeBSD ports are build from source, so the change of packaging format is irrelevant.

> Don't know if this is OS specific, but I can't get Spotify working under Nuvola at all.

That error isn't OS specific. Spotify stopped working with both Nuvola 3.x and 4.x on September 11, 2017 (#374) and was broken until February 11, 2018 when Nuvola 4.9 switched from WebKitGTK+ to Chromium Embedded Framework.

**Comment by fenryxo** [comment]
Hello. I'm cleaning stale tickets after the release of [Nuvola 4.16](https://medium.com/nuvola-news/nuvola-4-16-86a089068784). If this ticket still concerns you, feel free to reopen it.
