### ISSUE TITLE
Integration with desktop doesnt work

### ISSUE THREAD

**Issue by satonio** [tiliado/nuvolaruntime#504]
Basic information

- Your Linux distribution and its version: Ubuntu 16.04.5 LTS

- Your desktop environment: Cinnamon

 - Nuvola Runtime version: 4.15.3

 - The web app you use and its version: Tried play music and youtube

### Describe the bug

All works except the integration with the desktop, so I can't stop, play, skip etc using the buttons in the devices neither It appear over sound icon.

**Steps to reproduce the behavior**

1. Open Google Play Music in nuvola app runtime

**Expected behavior**

Sound icon changes to Music icon in the taskbar and controls to play, stop, etc appears there with the information of what is being played. When a new song starts it used to send a notification to the desktop, that doesn't work either.

**Debugging log**

Attach the debug log here: [debug.txt](https://github.com/tiliado/nuvolaruntime/files/2890191/debug.txt)

**Screenshots**

I think its not neccesary

**Additional context**

No comments

**Comment by fenryxo** [comment]
Hello @satonio, thanks for reporting the issue. Could you enable [Media Player DBus Interface](https://nuvola.tiliado.eu/docs/4/mpris.html) in Preferences and try again?

**Comment by satonio** [comment]
It don't let me do it. It says I need a license. It only works if you pay or should it work anyway?

**Comment by fenryxo** [comment]
When your 31-day free trial ends, you need to [purchase Nuvola](https://nuvola.tiliado.eu/pricing/) to use the features which are not available in the [free tier](https://nuvola.tiliado.eu/pricing/). The [Media Player DBus Interface](https://nuvola.tiliado.eu/docs/4/mpris.html) feature requires a purchase. Alternatively, you can build Nuvola from the source code for free or try out third-party builds.

**Comment by fenryxo** [comment]
Hello. I'm cleaning stale tickets after the release of [Nuvola 4.16](https://medium.com/nuvola-news/nuvola-4-16-86a089068784). If this ticket still concerns you, feel free to reopen it.
