### ISSUE TITLE
Feature Request: Amazon Cloud Player - Add Canada to the list of national selections

### ISSUE THREAD

**Issue by macsrok** [tiliado/nuvolaruntime#511]
Currently Canada is not in the list of "Preferred national variant" options.
manually loading in https://music.amazon.ca/home seems to load the page. When I manually load in the Canadian page however, I don't seem to have integration with the player controls that appear when you click the sound tray icon. The player controls appear and I see the amazon logo but clicking the buttons doesn't actually do anything. I don't know if that is unrelated to manually loading the URL however.

Amazon Cloud Player Script version 5.9.0 (0-g235c32e)
Nuvola Apps Runtime version 4.16.4 (4-g819cdb2)
elementary OS 5.0 Juno

**Comment by a-m-s** [comment]
Not having an account, I don't have any way to test the Canadian site.

Please open the "developer" sidebar (you need to have enabled "Developer's tools" in the app preferences), and post a screenshot here while a track is playing.

**Comment by a-m-s** [comment]
Just to be clear, I can add Canada to the official list, but the "Load URL..." method ought to have worked too, so there's something more happening here.

**Comment by macsrok** [comment]
The integration seems to be working fine now. I'm not sure why it wasn't before. The screenshot can be downloaded [here](https://www.dropbox.com/s/uqxubpjflh9zl97/Selection_001.png?dl=0)

**Comment by fenryxo** [comment]
Hello @macsrok. Thanks for creating this ticket. Could you try Nuvola with Amazon Cloud Player version **5.9.1 (1-gd88646b)** (just published)? You can now choose Canada in Preferences → Web App Settings and the Home button in Nuvola's header bar should load Canadian variant.

![web_app_settings](https://user-images.githubusercontent.com/853706/55561060-cabcf900-56f1-11e9-82c6-ce3c9652a1c7.png)

Hello @a-m-s, thanks for adding Canada so promptly :+1:
