### ISSUE TITLE
Missing nvidia driver version 418.40.04

### ISSUE THREAD

**Issue by rguerrab** [tiliado/nuvolaruntime#513]
This is maybe due to nvidia's cuda repository file, but my driver version (418.40.04) is missing from the list of available modules org.freedesktop.Platform.GL.nvidia-*
There are newer and older ones, but not the one that nvidia's repository installs by default.

**Comment by fenryxo** [comment]
Hello @rguerrab. Thanks for reporting this issue. I'm afraid that 418.40.04 is not available in the [Linux AMD64 Display Driver Archive](https://www.nvidia.com/object/linux-amd64-display-archive.html). Could you point me to more information about Nvidia Cuda repository?

**Comment by rguerrab** [comment]
Hi @fenryxo, thanks for the quick reply.  Nvidia curates a repository with distribution-appropriate divers and CUDA binaries on their developer server.  For my Mint 19.1 installation their Ubuntu 18.04 group works well.  You can find that repository here:
https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/
and the deb file that installs the appropriate source.list file here:
https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.1.105-1_amd64.deb
Equivalent files for other distributions and releases are available in the parent directories.

**Comment by fenryxo** [comment]
Thanks for the info. I've been a bit busier lately because of my job interview this week. I hope to examine the issue on Saturday.

**Comment by fenryxo** [comment]
Hello @rguerrab. It might be possible to use your host drivers inside Flatpak sandbox as an unmanaged extension ([Using host Nvidia driver with Flatpak](https://blog.tingping.se/2018/08/26/flatpak-host-extensions.html)). Could you provide me with the output of these two commands?

```
flatpak --gl-drivers
cat /sys/module/nvidia/version
```

**Comment by rguerrab** [comment]
Sure the outputs are:
```
flatpak --gl-drivers
nvidia-418-40-04
default
host
```
and
```
cat /sys/module/nvidia/version
418.40.04
```

**Comment by fenryxo** [comment]
Thanks, @rguerrab. Sorry for the late response. I've been moving to a new flat so life is a bit crazy nowadays.

Could you try out these instructions?

1. Download [libnvidia-gl-418_418.40.04-0ubuntu1_amd64.deb](https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/libnvidia-gl-418_418.40.04-0ubuntu1_amd64.deb).
2. Unpack the deb file and the `data.tar.xz` archive inside.
3. Create a directory `~/.local/share/flatpak/extension/org.freedesktop.Platform.GL.nvidia-418-40-04/x86_64/1.4` with the following content:

```
├── glvnd
│   └── egl_vendor.d
│       └── 10_nvidia.json
├── lib
│   ├── libGLX_nvidia.so.X.Y
│   └── All libs omitted for brevity…
└── vulkan
    └── icd.d
        └── nvidia_icd.json
```

* The content of `glvnd` comes from `data.tar.xz/usr/share/glvnd`.
* The content of `vulkan` comes from `data.tar.xz/usr/share/vulkan`.
* The content of `lib` comes from `data.tar.xz/usr/lib/x86_64-linux-gnu`.

4. Run `flatpak run --command=ls org.gnome.Platform//3.32 -lhR /usr/lib/x86_64-linux-gnu/GL`. If the directory is not empty, the driver might be recognized.
5. Run Nuvola.

**Comment by rguerrab** [comment]
Np.  It worked!  Presumably I'll have to repeat the equivalent steps whenever I install a driver update, which is fine by me.  Thanks

**Comment by fenryxo** [comment]
Indeed, you need to repeat the procedure every time you upgrade the drive to a version which is not in FlatHub.

**Comment by fenryxo** [comment]
I've updated the graphics driver instructions with [Host driver as unmanaged extension](https://github.com/tiliado/nuvolaruntime/wiki/Graphics-Drivers#host-driver-as-unmanaged-extension).
