### ISSUE TITLE
Idagio music streaming

### ISSUE THREAD

**Issue by grichard48** [tiliado/nuvolaruntime#519]
I'd like to encourage you to add Idagio music streaming to your already excellent list of services you've included.

**Comment by fenryxo** [comment]
Hello @grichard48. Thanks for your suggestion.

**Comment by fenryxo** [comment]
Released. [Installation instructions](https://nuvola.tiliado.eu/app/idagio/). [Source code](https://github.com/tiliado/nuvola-app-idagio).
