### ISSUE TITLE
Webpages not shown in offscreen rendering mode (GetVSyncParametersIfAvailable error)

### ISSUE THREAD

**Issue by bartlibert** [tiliado/nuvolaruntime#520]
### Basic information

- Your Linux distribution and its version: Debian GNU/Linux buster/sid
- Your desktop environment: Gnome 3.30.2
- Nuvola Runtime version: 4.16.4 (4-g819cdb2)
 - The web app you use and its version: Youtube Music 1.3.0 (0-gbbf30d7) (but also with other scripts)
 
### Describe the bug

When I open the app, it seems it tries to load the webpage, but nothing is shown. Using "home" or "reload" does not change anything. Trying "CTRL-L" and entering any url does not work either.
This is on wayland.
Completely uninstalling and reinstalling the flatpaks and their dependencies does not solve the issue.
The log shows a lot of "GetVSyncParametersIfAvailable" errors. If I move my mouse around over the window, these error keep popping up.

**Steps to reproduce the behavior**
 Open the app

**Expected behavior**
Website is shown, I can listen to music.

**Debugging log**

Attach the debug log here: ...
[log.txt](https://github.com/tiliado/nuvolaruntime/files/3186760/log.txt)

**Screenshots**
![Screenshot from 2019-05-16 12-59-59](https://user-images.githubusercontent.com/948770/57849453-9ef65e00-77db-11e9-97cb-acbe14d1967c.png)

**Comment by fenryxo** [comment]
Hello @bartlibert. Thanks for reporting the issue. Is it a fresh installation of Nuvola? If not, is there a chance that Nuvola stopped working because of a system upgrade, possibly graphics drivers?

**Comment by fenryxo** [comment]
I can see `
Runner: [INFO Δ000211us CefGtk] WebView.vala:75: CEF rendering mode: CEF_GTK_RENDERING_MODE_OFFSCREEN` in the log. Does the issue persist if you switch to normal rendering mode?

**Comment by bartlibert** [comment]
It is indeed something that stopped working suddenly, but I did not see any
suspicious driver updated. However, using normal rendering mode fixes it.
From my logs I see that I enabled offscreen rendering mode somewhere in may
last year, but I don't remember why, so probably it's not needed anymore
now.

Op do 16 mei 2019 om 21:08 schreef Jiří Janoušek <notifications@github.com>:

**Comment by fenryxo** [comment]
I'm afraid I won't have enough time to look at the offscreen rendering mode anytime soon.

**Comment by fenryxo** [comment]
ValaCEF is deprecated and will be replaced with the QtWebWengine port of Nuvola in #583. The work-in-progress components [Wayland Embedded View Framework Server](https://github.com/tiliado/wayland-embedded-view-server) and [Wayland Embedded View Framework Client](https://github.com/tiliado/wayland-embedded-view-client) do use offscreen rendering.
