### ISSUE TITLE
Error while trying to install app

### ISSUE THREAD

**Issue by hanut11** [tiliado/nuvolaruntime#521]
While trying to install apps from terminal, I am getting this error:
Error searching remote nuvola: Cant find ref eu.tiliado.NuvolaAppTidal

Any Solution ?

**Comment by fenryxo** [comment]
Hello @hanut11. What's your Linux distribution, architecture (32bin/64bit) and Flatpak version (`flatpak --version`)?

**Comment by fenryxo** [comment]
Closing this ticket as there hasn't been any response since May 18th.
