### ISSUE TITLE
Multi-selection

### ISSUE THREAD

**Issue by Dimergon** [tiliado/nuvolaruntime#522]
**Is your feature request related to a problem? Please describe:**

Wouldn't go as far as to say that it's a problem, but I will admit not having the opportunity to select multiple tracks / albums is a minor nuisance.

**Describe the solution you'd like:**

A simple checkbox or button that opens for multi-selection of songs in a playlist and entire albums, makes creating huge playlists so much less of a pain in the butt and saves a ton of time and mouseclicking.

**Describe alternatives you've considered:**

Using Soundiiz as a makeshift replacement, it's a third-party playlist manager that allows for import/export of playlists across multiple platforms.

**Additional context:**

See attached image
![Screenshot from 2019-05-18 11-38-27](https://user-images.githubusercontent.com/10378826/57967727-e30b6f00-7951-11e9-8c8c-1fd6035bb9ce.png)

**Comment by fenryxo** [comment]
Hello @Dimergon. I'm afraid I don't understand your feature request. Nuvola itself doesn't manage any playlists. It's the responsibility of the streaming service which is loaded in Nuvola.

**Comment by fenryxo** [comment]
Closing as there is no response for over a month.
