### ISSUE TITLE
Widevine support for Tidal

### ISSUE THREAD

**Issue by spence10101** [tiliado/nuvolaruntime#524]
### Basic information

- Your Linux distribution and its version: Ubuntu 19.04

- Your desktop environment: GNOME 3

 - Nuvola Runtime version: 4.16.4

 - The web app you use and its version: Tidal 1.0.0

### Describe the bug

Tidal does not recognize Widevine support, cannot play in HiFi.

**Steps to reproduce the behavior**

1. Open Tidal Streaming Quality
2. See HiFi is disabled and says "Requires browser with Widevine support"

**Expected behavior**

Able to change streaming quality to HiFi

**Screenshots**

![image](https://user-images.githubusercontent.com/43445303/58358883-67745b00-7e46-11e9-8918-4f9ffa29bae2.png)

**Additional context**

This works correctly in Google Chrome installed on the OS, just not inside Nuvola.

**Comment by fenryxo** [comment]
Hello @spence10101. Thanks for reporting the issue. I haven't noticed that Tidal switched to Widevine for HiFi playback.

**Comment by fenryxo** [comment]
Fix committed to the source code repository and will be released with the next rebuild of Flatpak packages.

![tidal_hifi](https://user-images.githubusercontent.com/853706/58750332-42f53000-8491-11e9-8f63-1aa815be8a54.png)

**Comment by fenryxo** [comment]
Published as Nuvola 4.16.10 & Tidal script 1.0.3. Could anyone verify that the issue is fixed?

**Comment by spence10101** [comment]
Confirmed fixed - it works after update. Thanks!
