### ISSUE TITLE
Pocket Casts app shows white screen instead of player

### ISSUE THREAD

**Issue by archmunky** [tiliado/nuvolaruntime#527]
### Basic information

- Your Linux distribution and its version: Fedora 30 (Cinnamon Spin)
- Your desktop environment: Cinnamon 4.0.10
 - Nuvola Runtime version: 4.16.10 (10-gb11d0c4)
 - The web app you use and its version: Pocket Casts 1.3.0 (0-gcba8da7)

### Describe the bug

When opening the Pocket Casts app, the web app briefly appears and then the app screen goes white.  I could occasionally get the app to function by repeatedly pressing reload but that no longer appears to work.

**Steps to reproduce the behavior**

1. Start Pocket Casts app
2. See white screen :)

**Expected behavior**

Ability to listen to podcasts

**Debugging log**

Attach the debug log here: [pocketcasts.log](https://github.com/tiliado/nuvolaruntime/files/3267954/pocketcasts.log)

**Screenshots**

Attach screenshots here: 
![pocketcasts error](https://user-images.githubusercontent.com/45470438/59139890-a507d680-8964-11e9-9c74-118941fa6921.png)

**Additional context**

I have already tried uninstalling the app, removing everything in the .var/app/eu.tiliado.NuvolaPocketCasts, and reinstalling but problem persists.

This might not be a problem that you can fix; it may be a problem with the Pocket Casts website itself.  I can open and use Pocket Casts in Chrome but latest version of Chromium appears to exhibit the same behavior.  Additionally, the debug log shows the following:

`Runner: [INFO Δ278510us CefGtk] WebView.vala:106: Console: https://www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js:60: document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.`

`Runner: [INFO Δ120117us CefGtk] WebView.vala:106: Console: https://www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js:54: Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.`

When you click on the link listed, it says it'll be removed in M75 around June 2019 which is when this problem started.  So it looks like a problem with the website itself using deprecated or removed features.  

So this might not be a bug you can fix but I wanted to bring it to your attention in case you know of a workaround.

**Comment by fenryxo** [comment]
Hello @archmunky. Thanks for reporting the issue. 

There are other errors in the log that look suspicious:

```
https://play.pocketcasts.com/web/bundle.js:57:
    TypeError: Cannot read property 'media' of undefined
https://play.pocketcasts.com/web/bundle.js:57:
    uncaught at mj
```

**Comment by fenryxo** [comment]
Hello @archmunky. Could you try pressing the *Home* button in Nuvola's header bar and then reloading the web page?

**Comment by archmunky** [comment]
It started working a few days ago.  at least i haven't seen any occurrence of the issue in the past few days.  thx!

**Comment by fenryxo** [comment]
Great :-)
