### ISSUE TITLE
Nuvola runtime service

### ISSUE THREAD

**Issue by grechanyuk** [tiliado/nuvolaruntime#528]
Help. How install Nuvola Runtime Service for using multimedia keys?

**Comment by fenryxo** [comment]
Hello @grechanyuk. Visit https://nuvola.tiliado.eu/nuvola/ and follow instructions of the *Install Nuvola Apps Service* section for your distribution. Does it help?

**Comment by grechanyuk** [comment]
Thanks for the answer. No. I use this command "flatpak install nuvola eu.tiliado.Nuvola" and after that i take warning from this issuse https://github.com/tiliado/nuvolaruntime/issues/529

**Comment by grechanyuk** [comment]
After fix this issuse https://github.com/tiliado/nuvolaruntime/issues/529 everything worked as it should!

**Comment by fenryxo** [comment]
> Thanks for the answer. No. I use this command "flatpak install nuvola eu.tiliado.Nuvola" and after that i take warning from this issuse #529

That means Nuvola Service is already installed.
