### ISSUE TITLE
Dark Theme not applied to Calendar?

### ISSUE THREAD

**Issue by zefram-cochrane** [tiliado/nuvolaruntime#534]
<I think I may have broken something in uploading new themes. When I first ran up the calendar under nuvola and selected Adwaita Dark, I saw a lovely dark calendar. 

Or at least I think I did - since loading up further themes, I've been unable to see it again. Don't get me wrong - I'd use Google calendar over any other calendar even if the glare hurts my eyes. 

But I suspect either PEBCAK or a bug. If the former, well, I've twiddled every setting so I think I'm missing something that should be obvious ...

**Comment by fenryxo** [comment]
Hello @zefram-cochrane. [Could you set a dark theme in Nuvola preferences](https://nuvola.tiliado.eu/docs/4/appearance.html) and then attach a screenshot for me to see what's wrong? Thanks.

**Comment by fenryxo** [comment]
Closing this ticket as there hasn't been any response since June 17th.
