### ISSUE TITLE
Login fails for SiriusXM using correct username/password

### ISSUE THREAD

**Issue by linuxgameconsortium** [tiliado/nuvolaruntime#539]
### Basic information

- Your Linux distribution and its version: Ubuntu MATE 18.04.2 LTS

- Your desktop environment: ...
   

 - Nuvola Runtime version: ...
   

 - The web app you use and its version: ...
   

### Describe the bug

The SiriusXM app installed and updated. But for some reason the login fails. 

Is the app Country specific? I'm in Canada right now. And I have a legit SiriusXM account, which I can listen to live via Windows. Why can't I log in?

**Debugging log**

Attach the debug log here: ...

**Screenshots**

Attach screenshots here: ![siriusxm-nuvola-a- 2019-06-17 17-00-54](https://user-images.githubusercontent.com/3820491/59707333-6ed21e80-91d0-11e9-807d-d4468079068d.png)

**Additional context**

I just purchased a Premium key. Supporting the open source development for Nuvola.

**Comment by fenryxo** [comment]
Hello @linuxgameconsortium. Do you have the account of SiriusXM US or SiriusXM Canada?

**Comment by fenryxo** [comment]
> Is the app Country specific?

It seems so. When I need to access SiriusXM, I need to use a US VPN service. I've never tried SiriusXM with a Canadian VPN service though.

**Comment by linuxgameconsortium** [comment]
Well it looks like a different login or redirect is needed for use in
Canada.

Even though I can use the same login in the US without any problem.

Best Regards,


*Todd Batrynchuk*
Founder and CEO

toddb@linuxgameconsortium.com

*LinuxGameConsortium.com* <http://www.linuxgameconsortium.com/>


<http://LinuxGameConsortium.com> <http://linuxgamenews.com/>

*Discord:** [Todd B] LinuxGameConsortium#3555*
*Twitter:* @linuxgamecons <https://twitter.com/linuxgamecons>
*YouTube:* LinuxGameConsortium
<https://www.youtube.com/user/linuxgameconsortium>
*SkypeID:* linuxgameconsortium
*LinkedIn:* todd-batrynchuk
<http://ca.linkedin.com/pub/todd-batrynchuk/5/4a6/940/>

**Comment by fenryxo** [comment]
Indeed, it is necessary to add a selection of national variants - USA and Canada.

**Comment by linuxgameconsortium** [comment]
Yes indeed. That would fantastic. Since it is just a URL change.

**Comment by fenryxo** [comment]
Sorry that it took so long. I was hit by a strange crash in GTK that required a lot of time to investigate.

Updated Sirius XM script should be available later today.

**Comment by fenryxo** [comment]
Released in SiriusXM 1.5.5 (5-gba43c84).

**Comment by linuxgameconsortium** [comment]
All good. GTK issue, really?
Well I'm glad you have it worked out.

Just updated and voila SiriusXM works in Canada. :D

Thanks Jiří!!!

Best Regards,


*Todd Batrynchuk*
Founder and CEO

toddb@linuxgameconsortium.com

*LinuxGameConsortium.com* <http://www.linuxgameconsortium.com/>


<http://LinuxGameConsortium.com> <http://linuxgamenews.com/>

*Discord:** [Todd B] LinuxGameConsortium#3555*
*Twitter:* @linuxgamecons <https://twitter.com/linuxgamecons>
*YouTube:* LinuxGameConsortium
<https://www.youtube.com/user/linuxgameconsortium>
*SkypeID:* linuxgameconsortium
*LinkedIn:* todd-batrynchuk
<http://ca.linkedin.com/pub/todd-batrynchuk/5/4a6/940/>
