### ISSUE TITLE
Start-up Check for BBC iPlayer reports Error

### ISSUE THREAD

**Issue by JohnParten** [tiliado/nuvolaruntime#540]
Fedora 28 ~ KDE Desktop.
I am new to to flatpak etc. This is the first time I have tried to get BBC IPlayer on Fedora
Switched to sudo terminal and installed as follows as per instructions ...
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo 
flatpak remote-add --if-not-exists nuvola https://dl.tiliado.eu/flatpak/nuvola.flatpakrepo
flatpak update
flatpak install nuvola eu.tiliado.Nuvola
dnf install nuvola-app-bbc-iplayer.noarch
... restarted machiine
... bbciplayer program found in menu system. Attempt to run (as user) and reports Error.
I am probably missing something obvious (picture of app showing error attached)
Any help appreciated ~ thanks ~ JP
![ErrorBBCIPlayer](https://user-images.githubusercontent.com/52199586/60089891-58304800-9739-11e9-900b-37f646f05ed1.png)

**Comment by a-m-s** [comment]
You probably can't mix flatpaks and the distro packages. Please remove the Fedora package and install the iPlayer flatpak.

`flatpak install nuvola eu.tiliado.NuvolaAppBbcIplayer`

Alternatively, you may be able use the Fedora packages, but you're going to need to get support from the Fedora community.

**Comment by fenryxo** [comment]
Hello @JohnParten. You have launched BBC iPlayer from this package provided by Fedora:

```
dnf install nuvola-app-bbc-iplayer.noarch
```

We don't provide support for this package. I recommend removing all Fedora packages of Nuvola (`sudo dnf remove 'nuvola*'`) and [installing our flatpaks of BBC iPlayer](https://nuvola.tiliado.eu/app/bbc_iplayer/fedora/fc28/).

**Comment by JohnParten** [comment]
Hi fenryxo
Thanks for your assistance but I still have a slight problem as shown by the terminal session below. Can you help further?...
# flatpak list

# rpm -qa | grep flatpak
flatpak-1.0.7-1.fc28.x86_64
flatpak-libs-1.0.7-1.fc28.x86_64
plasma-discover-flatpak-5.13.5-1.fc28.x86_64
# flatpak install nuvola eu.tiliado.NuvolaAppBbcIplayer
error: Remote "nuvola" not found
# dnf remove 'nuvola*'
No match for argument: nuvola*
Error: No packages marked for removal.
# flatpak install nuvola eu.tiliado.NuvolaAppBbcIplayer
error: Remote "nuvola" not found
# 
... am I doing something wrong ?

**Comment by JohnParten** [comment]
Hi "Tiliado/NovulaRuntime" ~ sorry I don't know what title to call you.

Thankyou so much for helping me with my failed attempt to install 
FlatPak BBC IPlayer on Fedora.
I have tried to follow your instructions and performed the following ...

$ sudo dnf remove nuvola-app-bbc-iplayer.noarch
$ sudo flatpak uninstall nuvola eu.tiliado.NuvolaAppBbcIplayer
$ sudo flatpak uninstall eu.tiliado.NuvolaAppBbcIplayer
# flatpak uninstall org.freedesktop.Platform.html5-codecs/x86_64/18.08
# flatpak uninstall eu.tiliado.Nuvola/x86_64/stable
# flatpak uninstall org.gnome.Platform/x86_64/3.30
# flatpak remote-delete nuvola
# flatpak remote-delete flathub

... then I perform the following checks as sudo ...

# flatpak list

# rpm -qa | grep flatpak
flatpak-1.0.7-1.fc28.x86_64
flatpak-libs-1.0.7-1.fc28.x86_64
plasma-discover-flatpak-5.13.5-1.fc28.x86_64
#

... then I tried to install using your command and I get an error ...

# flatpak install nuvola eu.tiliado.NuvolaAppBbcIplayer
error: Remote "nuvola" not found
#

... so is this error caused by one or more of the native fedora 
packages. If  and your email instructions imply I should run ...

# dnf remove flatpak-1.0.7-1.fc28.x86_64
# dnf flatpak-libs-1.0.7-1.fc28.x86_64
# dnf plasma-discover-flatpak-5.13.5-1.fc28.x86_64

Eeeek ~ I have just seen you have closed this issue before I have had a 
chance to reply ~ I am hoping this reply reaches you

...thanks for any additional advice you can give ...
... John Parten


    -- 

------------------------------------------------------------------------
Skype:
Email:
Home Tel:
Mobile Tel: 	john.parten
john.parten@ntlworld.com <mailto:john.parten@ntlworld.com>
01189 617837
07801 124215 	

------------------------------------------------------------------------

**Comment by fenryxo** [comment]
Hello @JohnParten. 

* Remove only `nuvola-app-bbc-iplayer` Fedora packages: `sudo dnf remove nuvola-app-bbc-iplayer`.
* Keep these packages - don't remove them: `flatpak-1.0.7-1.fc28.x86_64`, `flatpak-libs-1.0.7-1.fc28.x86_64`, `plasma-discover-flatpak-5.13.5-1.fc28.x86_64`.
* Follow [Install Nuvola Apps Runtime](https://nuvola.tiliado.eu/nuvola/fedora/fc28/)
* Follow [Install BBC iPlayer script 1.6](https://nuvola.tiliado.eu/app/bbc_iplayer/fedora/fc28/)

**Comment by JohnParten** [comment]
I am leaving this comment in case it helps anyone. (I HAVE BBC IPLAYER WORKING NOW)
Remember I am Fedora28 KDE user. So I followed the advice given above ...

flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak remote-add --if-not-exists nuvola https://dl.tiliado.eu/flatpak/nuvola.flatpakrepo
flatpak update
flatpak install nuvola eu.tiliado.Nuvola
flatpak install nuvola eu.tiliado.NuvolaAppBbcIplayer

... and now it works fine.
A big thank you to the support engineers that gave me the advice on this ticket. THANKYOU :)
