### ISSUE TITLE
Cannot launch Nuvola - bwrap: Can't find source path /home/mx/.fonts 

### ISSUE THREAD

**Issue by gerlinux-design** [tiliado/nuvolaruntime#542]
Linux Mint"
VERSION="19.1 (Tessa)"

**Comment by gerlinux-design** [comment]
Hi, First at all, I am quite a newbie.
I can not launch Nuvola.
I tried everything that is here:
[https://forums.linuxmint.com/viewtopic.php?f=47&t=296839&p=1654491#p1653333](url)
I hope you can give me a hand,
thanks

**Comment by fenryxo** [comment]
Hello @gerlinux-design.
 
```
mx@mx:~$ flatpak run eu.tiliado.NuvolaAppBandcamp
bwrap: Can't find source path /home/mx/.fonts: No such file or directory
```

It seems that `/home/mx/.fonts` is a broken symlink. Could you try removing it?

```
rm /home/mx/.fonts
```

Let me know whether it helps.

**Comment by fenryxo** [comment]
Closing this ticket as there hasn't been any response since July 14th.
