### ISSUE TITLE
nuvola install: why does it want to override (maybe upgrade) my NVidia driver

### ISSUE THREAD

**Issue by regisz** [tiliado/nuvolaruntime#544]
### Basic information

- Your Linux distribution and its version: ...
```
Linux Mint 19.1 Tessa
```
- Your desktop environment: ...
```
Cinnamon 4.0.10
```
 - Nuvola Runtime version: ...
_Not installed yet_

 - The web app you use and its version: ...
_Not installed yet_

### Describe the bug

I would like to install app (again, I reinstalled my system), but it would like to install
```
org.freedesktop.Platform.GL.nvidia-390-116/x86_64/1.4 flathub 0498116dc949
```
too.
I would like to stay the actual version of NVidia driver (which comes from system via linux package manager).

How can I avoid driver upgrade? Why is it required basically?

**Steps to reproduce the behavior**

```
$ flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
$ flatpak remote-add --if-not-exists nuvola https://dl.tiliado.eu/flatpak/nuvola.flatpakrepo
$ flatpak update
$
$ flatpak install nuvola eu.tiliado.Nuvola
Required runtime for eu.tiliado.Nuvola/x86_64/stable (runtime/org.gnome.Platform/x86_64/3.32) found in remote flathub
Do you want to install it? [y/n]: y
Installing in system:
org.gnome.Platform/x86_64/3.32                        flathub 6869751f600d
org.gnome.Platform.Locale/x86_64/3.32                 flathub 3d69d5100a25
org.freedesktop.Platform.GL.nvidia-390-116/x86_64/1.4 flathub 0498116dc949
org.gtk.Gtk3theme.Mint-Y/x86_64/3.22                  flathub a2a4a6456cc6
org.freedesktop.Platform.html5-codecs/x86_64/18.08    flathub f5389d9c2a68
eu.tiliado.Nuvola/x86_64/stable                       nuvola  e5d8d5200450
  permissions: ipc, network, pulseaudio, wayland, x11, dri
  file access: /sys/fs/cgroup/pids/system.slice:ro, /sys/module/i915:ro, /sys/module/nvidia:ro, xdg-run/dconf, ~/.config/dconf:ro
  dbus access: ca.desrt.dconf, eu.tiliado.*, org.gnome.SessionManager, org.gnome.SettingsDaemon, org.gnome.SettingsDaemon.MediaKeys, org.xfce.SessionManager
  system dbus access: org.freedesktop.NetworkManager
Is this ok [y/n]: n
```

**Expected behavior**

No driver upgrade.

**Comment by fenryxo** [comment]
It isn't a driver update. Flatpak just installs [NVidia driver flatpak extension](https://github.com/tiliado/nuvolaruntime/wiki/Graphics-Drivers) matching the driver on your system. Flatpak apps cannot use the driver on your system. That's why Flatpak installs a driver extension for them. However, Flatpak never upgrades your system driver, only the flatpak extensions.

To sum up, it's desired behavior and system driver is not upgraded. You can safely proceed.

**Comment by regisz** [comment]
Thx a lot :).
