### ISSUE TITLE
Multimedia keys doesn't work NuvolaAppYandexMusic

### ISSUE THREAD

**Issue by AlexGluck** [tiliado/nuvolaruntime#547]
### Basic information

- Your Linux distribution and its version: Fedora 30
   

- Your desktop environment: Gnome 3.32
   

 - The web app you use and its version: NuvolaAppYandexMusic
   

 - Nuvola Runtime version: 
```
$ flatpak list
Name                                    Application ID                        Версия Ветка  Origin      Установка
Nuvola Apps Service                     eu.tiliado.Nuvola                            stable nuvola      system
Yandex Music • Nuvola App               eu.tiliado.NuvolaAppYandexMusic              stable nuvola      system
Intel                                   org.freedesktop.Platform.VAAPI.Intel         18.08  flathub__1_ system
html5-codecs                            org.freedesktop.Platform.html5-codecs        18.08  flathub__1_ system
GNOME Application Platform version 3.32 org.gnome.Platform                           3.32   flathub__1_ system
Adwaita dark GTK theme                  org.gtk.Gtk3theme.Adwaita-dark               3.22   flathub__1_ system
```

   

### Describe the bug
Multimedia keys doesn't work. 

**Steps to reproduce the behavior**

1. Install fedora 30
2. Install by manual Nuvola
3. Try press play\pause button.

**Expected behavior**
Multimedia keys work properly.

**Comment by fenryxo** [comment]
Hello @AlexGluck. Thanks for reporting the issue. Could you provide me with following details to help me to investigate the issue further?

* **The version of Nuvola Runtime** (you provided only a branch). You can get it from About dialog, click Menu button, then About.
* **The version of NuvolaAppYandexMusic**. You can get it from About dialog, click Menu button, then About.
* **Debugging output**. See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#debugging-output) for instructions on how to get a debugging log. then save it as a text file (*.txt) and attach it to the bug report using the *Attach files by dragging & dropping or selecting them.* feature available under the textbox.

**Comment by AlexGluck** [comment]
- The version of Nuvola Runtime.
- The version of NuvolaAppYandexMusic. ![Image of Yaktocat](https://i.imgur.com/CuSHFEq.png)
- Debugging output.  [eu.tiliado.NuvolaAppYandexMusic.debug.txt](https://github.com/tiliado/nuvolaruntime/files/3600098/eu.tiliado.NuvolaAppYandexMusic.debug.txt)


I think [this](https://bugzilla.redhat.com/show_bug.cgi?id=1643937) can help

**Comment by AlexGluck** [comment]
**UPD**
gnome at wayland media keys work properly before sleep or hibernate
After sleep or hibernate media keys not working

**Comment by fenryxo** [comment]
> I use gdm on wayland and gnome at xorg.
> ...
> gnome at wayland media keys work properly before sleep or hibernate

Do I understand correctly that media keys in GNOME/Xorg never work while they always work in GNOME/Wayland before sleep/hibernate?

**Comment by AlexGluck** [comment]
Yep

**Comment by fenryxo** [comment]
I could not reproduce the issue on my system yet but I have a few ideas for test scenarios.

**Comment by fenryxo** [comment]
Is this issue still present in the latest Nuvola (4.16.30)?

**Comment by AlexGluck** [comment]
I removed app, because needed feature not worked and pay for testing feature i can't. Sorry.

**Comment by fenryxo** [comment]
I understand that. I'm sorry that I haven't managed to reproduce and fix the issue for you.
