### ISSUE TITLE
Spotify does not play audio, error: "spotify no longer supports this version of Chrome"

### ISSUE THREAD

**Issue by archmunky** [tiliado/nuvolaruntime#548]
### Basic information

- Your Linux distribution and its version: Fedora 30 
- Your desktop environment: Cinnamon 4.2.3
 - Nuvola Runtime version: 4.16.20 (20-gaa3880c)
 - The web app you use and its version: Spotify 3.1.1 (1-g310fb02)

### Describe the bug

Spotify opens but trying to play anything gives an error "Spotify no longer supports this version of Chrome. Please update your browser for uninterrupted listening."

Looks like Spotify now requires a newer version of Chromium -- debug has it at 74.0.3729.131

**Steps to reproduce the behavior**

1. Start Spotify app
2. Open any song or playlist
3. Press play

**Expected behavior**

Hear music.  :)

**Debugging log**

Attach the debug log here: 
[nuvola-spotify-debug.log](https://github.com/tiliado/nuvolaruntime/files/3532330/nuvola-spotify-debug.log)

**Screenshots**

Attach screenshots here: 
![Nuvola-Spotify-error](https://user-images.githubusercontent.com/45470438/63557810-36c0c200-c518-11e9-8a32-4a1a1fb87d8a.png)

**Additional context**

I think Spotify now requires a newer version of Chrome/Chromium than 74.

**Comment by fenryxo** [comment]
Hello @archmunky. Thanks for your report. Port to Chrome 75 is in progress (tiliado/valacef#16). There are quite large API changes so it isn't as easy as Chrome 73 → 74.

**Comment by archmunky** [comment]
Thanks!

**Comment by fenryxo** [comment]
I've managed to build Nuvola with the latest Chromium (76.3809), but more testing is needed to be sure there aren't any regressions.

**Comment by fenryxo** [comment]
Hello @archmunky. Could you test with the latest Nuvola 4.16.21 based on Chromium 75.0.3770.100? (Nuvola with Chromium 76 is not ready for prime time yet tiliado/valacef#17.)

**Comment by archmunky** [comment]
Looks like it is working on fully updated Fedora 30.
![image](https://user-images.githubusercontent.com/45470438/64912977-86547100-d705-11e9-8d00-4e10bb606e37.png)

**Comment by fenryxo** [comment]
Glad to hear that the issue is resolved for you :-)
