### ISSUE TITLE
Unable to login to Google-based apps (Youtube, Calendar)

### ISSUE THREAD

**Issue by modvavet** [tiliado/nuvolaruntime#549]
### Basic information

- Your Linux distribution and its version: ...
   Ubuntu 19.04, Ubuntu 18.04

- Your desktop environment: ...
   Budgie

 - Nuvola Runtime version: ...
   4.16.20 (20-gaa3880c)

 - The web app you use and its version: ...
   Youtube 2.1.0 (0-g38157ab), Google Calendar 1.3.2 (2-g41538c1)

### Describe the bug

I just recently tried the Nuvola apps for Ubuntu, on both my 19.04 tablet and my 18.04 desktop.
I installed via flatpak per the instructions from the Nuvola website.
However, in neither app on either machine can I actually sign into Google in Nuvola's apps.
The login comes up and allows me to enter my username and password, but instead of a successful sign-in, I get:
"Couldn't Sign You In"
"You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
Try using a different browser. Learn more"

**Steps to reproduce the behavior**

1. Open app
2. Enter username for Google account
3. Enter password for Google account
4. Press Enter, or click login button

**Expected behavior**

Signed in to Google Calendar or Youtube

**Debugging log**

Attach the debug log here: ...

**Screenshots**

Attach screenshots here: ...

**Additional context**

...

**Comment by modvavet** [comment]
I'm not certain it took my debug log, as I don't see it listed, so pasting it here-

flatpak run eu.tiliado.NuvolaAppYoutube --debug
Runner: [DEBUG Δ031942us GVFS-RemoteVolumeMonitor] Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

Runner: [DEBUG Δ004439us  GVFS] cannot open directory /usr/share/gvfs/remote-volume-monitors: Error opening directory “/usr/share/gvfs/remote-volume-monitors”: No such file or directory
Runner: [DEBUG Δ160352us  GVFS] org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

Runner: [DEBUG Δ000271us GLib-GIO] _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
Runner: [DEBUG Δ222049us Nuvola] AboutDialog.vala:54: Nuvola Apps 4.16.20 (20-gaa3880c)
Runner: [DEBUG Δ000218us Nuvola] AboutDialog.vala:56: YouTube script 2.1.0 (0-g38157ab)
Runner: [DEBUG Δ000130us Nuvola] AboutDialog.vala:60: Diorite 4.16.8
Runner: [DEBUG Δ000153us Nuvola] AboutDialog.vala:62: Chromium 74.0.3729.131
Runner: [DEBUG Δ010227us DioriteGtk] DesktopShell.vala:239: Shell: mutter(budgie) (null), CSD 1, appmenu 0, menubar 0
Runner: [DEBUG Δ064087us Nuvola] Connection.vala:121: Network Proxy: system settings
Runner: [DEBUG Δ003920us GLib-GIO] _g_io_module_get_default: Found default implementation portal (GProxyResolverPortal) for ‘gio-proxy-resolver’
Runner: [DEBUG Δ545134us Nuvola] AppRunnerController.vala:118: Scale factor: 1
Runner: [DEBUG Δ005791us DioriteGtk] Application.vala:255: XFCE session vanished: org.xfce.SessionManager
Runner: [DEBUG Δ071290us Nuvola] FormatSupport.vala:86: Trying to play /app/share/nuvolaruntime/audio/audiotest.mp3.
Runner: [DEBUG Δ014641us Nuvola] FormatSupport.vala:86: Pipeline state changed from NULL to READY.
Runner: [DEBUG Δ000317us Nuvola] Graphics.vala:47: Nvidia 304.137, i915 0, bumblebeed 0 => ignored 0
Runner: [DEBUG Δ210930us Nuvola] FormatSupport.vala:86: Pipeline state changed from READY to PAUSED.
Runner: [DEBUG Δ009609us Nuvola] FormatSupport.vala:86: Pipeline state changed from PAUSED to PLAYING.
Runner: [DEBUG Δ038375us Nuvola] FormatSupport.vala:86: End of stream for file /app/share/nuvolaruntime/audio/audiotest.mp3.
Runner: [DEBUG Δ012091us Nuvola] StartupCheck.vala:164: Checking requirements with Chromium 74.0.3729.131
Runner: [DEBUG Δ000120us Nuvola] Traits.vala:62: Chromium[63] -> DRT_REQUIREMENT_STATE_SUPPORTED 
Runner: [DEBUG Δ000055us Nuvola] Traits.vala:62: Codec[MP3] -> DRT_REQUIREMENT_STATE_SUPPORTED 
Runner: [DEBUG Δ000053us Nuvola] Traits.vala:62: Feature[MSE] -> DRT_REQUIREMENT_STATE_SUPPORTED 
Runner: [WARNING Δ085954us Nuvola] StartupWindow.vala:146: tiliado-account-message: Features Tier: ★ Premium
Runner: [DEBUG Δ049839us CefGtk] init.vala:97: No widevine plugin dir.
Your system is broken: dlsym doesn't work! This has been reported to be caused by Nvidia's libGL. You should expect time related functions to misbehave. http://code.google.com/p/chromium/issues/detail?id=16800
[0824/030137.174494:ERROR:address_tracker_linux.cc(175)] Could not bind NETLINK socket: Address already in use (98)
Runner: [INFO Δ225237us Nuvola] CefEngine.vala:302: Partially implemented: register_ipc_handlers()
Runner: [INFO Δ001869us CefGtk] WebView.vala:75: CEF rendering mode: CEF_GTK_RENDERING_MODE_WINDOWED
Runner: [INFO Δ045352us CefGtk] Client.vala:106: get_life_span_handler
Runner: [DEBUG Δ030331us Nuvola] WebAppWindow.vala:179: Sidebar position: 1143
Runner: [DEBUG Δ110836us CefGtk] WebViewWindowed.vala:65: allocation 0,1+1332,994 child_allocation 0,0+1332,994
Runner: [INFO Δ033148us CefGtk] WebView.vala:114: Renderer #1 created.
[0823/230137.498875:ERROR:gl_context_glx.cc(227)] Couldn't make context current with X drawable.
[0823/230137.499114:ERROR:gpu_info_collector.cc(69)] gl::GLContext::MakeCurrent() failed
[0823/230137.499539:ERROR:gpu_info_collector.cc(187)] Could not create context for info collection.
[0823/230137.499708:ERROR:gpu_init.cc(62)] gpu::CollectGraphicsInfo failed.
[0823/230137.516509:WARNING:x11_util.cc(1422)] X error received: serial 188, error_code 9 (BadDrawable (invalid Pixmap or Window parameter)), request_code 155, minor_code 4 (Unknown)
[0823/230137.517026:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
Runner: [DEBUG Δ177005us CefGtk] WebViewWindowed.vala:65: allocation 0,1+1280,942 child_allocation 0,0+1280,942
Worker: [DEBUG Δ022194us GVFS-RemoteVolumeMonitor] Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

Worker: [DEBUG Δ000127us  GVFS] cannot open directory /usr/share/gvfs/remote-volume-monitors: Error opening directory “/usr/share/gvfs/remote-volume-monitors”: No such file or directory
Worker: [DEBUG Δ035004us  GVFS] org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

Worker: [DEBUG Δ000249us GLib-GIO] _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
Runner: [DEBUG Δ134353us Nuvola] CefEngine.vala:378: Init finished
Runner: [DEBUG Δ000847us Nuvola] WebWorker.vala:80: Cannot call ('Nuvola.actions.emit', <('ActionEnabledChanged', 'go-forward', false)>, false)
Runner: [DEBUG Δ000119us Nuvola] WebWorker.vala:80: Cannot call ('Nuvola.actions.emit', <('ActionEnabledChanged', 'go-back', false)>, false)
Runner: [INFO Δ008263us Nuvola] Component.vala:82: Load tray_icon Tray Icon
Runner: [INFO Δ000082us Nuvola] Component.vala:134: Activate: tray_icon Tray Icon
Runner: [DEBUG Δ007879us Nuvola] AppRunnerController.vala:676: Component tray_icon (Tray Icon) available=true, enabled=true
Runner: [INFO Δ000141us Nuvola] Component.vala:82: Load audio_tweaks Audio Tweaks
Runner: [INFO Δ000047us Nuvola] Component.vala:134: Activate: audio_tweaks Audio Tweaks
Runner: [DEBUG Δ013421us Nuvola] AppRunnerController.vala:676: Component audio_tweaks (Audio Tweaks) available=true, enabled=true
Runner: [INFO Δ000864us Nuvola] Component.vala:82: Load unity_launcher Extra Dock Actions
Runner: [INFO Δ000193us Nuvola] Component.vala:134: Activate: unity_launcher Extra Dock Actions
Runner: [DEBUG Δ002315us Nuvola] AppRunnerController.vala:676: Component unity_launcher (Extra Dock Actions) available=true, enabled=true
Runner: [INFO Δ000310us Nuvola] Component.vala:82: Load notifications Notifications
Runner: [INFO Δ000139us Nuvola] Component.vala:134: Activate: notifications Notifications
Worker: [DEBUG Δ094911us Nuvola] CefRendererExtension.vala:137: Got JS context
Worker: [INFO Δ000144us CefGtk] RendererContext.vala:57: JS Context created 1
Runner: [DEBUG Δ038990us Nuvola] Notifications.vala:160: Notifications: persistence false, actions true, icons true
Runner: [DEBUG Δ000373us Nuvola] AppRunnerController.vala:676: Component notifications (Notifications) available=true, enabled=true
Runner: [INFO Δ000226us Nuvola] Component.vala:82: Load mediakeys Multimedia keys
Runner: [DEBUG Δ000151us Nuvola] AppRunnerController.vala:676: Component mediakeys (Multimedia keys) available=true, enabled=true
Runner: [INFO Δ000170us Nuvola] Component.vala:82: Load scrobbler Audio Scrobbling
Runner: [DEBUG Δ000124us Nuvola] AppRunnerController.vala:676: Component scrobbler (Audio Scrobbling) available=true, enabled=true
Runner: [INFO Δ000165us Nuvola] Component.vala:82: Load mpris Media Player DBus Interface
Runner: [DEBUG Δ000122us Nuvola] AppRunnerController.vala:676: Component mpris (Media Player DBus Interface) available=true, enabled=true
Runner: [DEBUG Δ000162us Nuvola] AppRunnerController.vala:676: Component httpremotecontrol (Remote control over HTTP (experimental)) available=true, enabled=false
Runner: [INFO Δ000170us Nuvola] Component.vala:82: Load lyrics Lyrics
Runner: [DEBUG Δ000131us Nuvola] AppRunnerController.vala:676: Component lyrics (Lyrics) available=true, enabled=true
Runner: [DEBUG Δ000167us Nuvola] AppRunnerController.vala:676: Component developer (Developer's tools) available=true, enabled=false
Runner: [DEBUG Δ050110us Nuvola] CefEngine.vala:164: App Runner Initialized
Runner: [DEBUG Δ000287us Nuvola] CefEngine.vala:168: App Runner Ready
Runner: [DEBUG Δ015653us Nuvola] CefEngine.vala:381: Web Worker Ready
Runner: [DEBUG Δ001072us Nuvola] CefEngine.vala:589: Navigation: new window: false → false, uri: 'https://accounts.google.com/signin/v2/deniedsigninrejected?service=youtube&uilel=3&passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3D%252Fmusic&hl=en&flowName=GlifWebSignIn&flowEntry=ServiceLogin&cid=1&navigationDirection=forward' → 'https://accounts.google.com/signin/v2/deniedsigninrejected?service=youtube&uilel=3&passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3D%252Fmusic&hl=en&flowName=GlifWebSignIn&flowEntry=ServiceLogin&cid=1&navigationDirection=forward', approved: true, frame: (null), type: TT_EXPLICIT, user gesture: true
Runner: [DEBUG Δ005107us Nuvola] CefEngine.vala:488: Load started
Runner: [DEBUG Δ298592us Nuvola] CefEngine.vala:488: Load started
Runner: [INFO Δ114171us Nuvola] Component.vala:134: Activate: mpris Media Player DBus Interface
Runner: [INFO Δ000258us Nuvola] Component.vala:134: Activate: lyrics Lyrics
Runner: [DEBUG Δ004437us Nuvola] WebWorker.vala:80: Cannot call ('Nuvola.actions.emit', <('ActionEnabledChanged', 'toggle-sidebar', true)>, false)
Runner: [INFO Δ002418us Nuvola] Component.vala:134: Activate: mediakeys Multimedia keys
Runner: [DEBUG Δ000529us Nuvola] MPRISProvider.vala:67: Bus acquired: org.mpris.MediaPlayer2.NuvolaAppYoutube, registering objects
Runner: [DEBUG Δ011645us Nuvola] MPRISProvider.vala:80: Bus name acquired: org.mpris.MediaPlayer2.NuvolaAppYoutube
Runner: [INFO Δ018857us Nuvola] Component.vala:134: Activate: scrobbler Audio Scrobbling
Runner: [DEBUG Δ002317us Nuvola] HeadphonesWatch.vala:47: Sink 0 alsa_output.pci-0000_00_05.0.hdmi-stereo - Built-in Audio Digital Stereo (HDMI)
Runner: [DEBUG Δ000120us Nuvola] HeadphonesWatch.vala:50: Sink 0 Port: hdmi-output-0: HDMI / DisplayPort (priority 5900, available: unknown, headphones: no)
Runner: [DEBUG Δ178437us CefGtk] WebViewWindowed.vala:65: allocation 0,1+1143,942 child_allocation 0,0+1143,942
Runner: [DEBUG Δ010115us Nuvola] CefEngine.vala:589: Navigation: new window: false → false, uri: 'https://accounts.google.com/ServiceLogin?service=youtube&uilel=3&passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3D%252Fmusic&hl=en&flowName=GlifWebSignIn&flowEntry=ServiceLogin&cid=1&navigationDirection=forward' → 'https://accounts.google.com/ServiceLogin?service=youtube&uilel=3&passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3D%252Fmusic&hl=en&flowName=GlifWebSignIn&flowEntry=ServiceLogin&cid=1&navigationDirection=forward', approved: true, frame: (null), type: TT_EXPLICIT, user gesture: true
Runner: [DEBUG Δ000121us Nuvola] CefEngine.vala:601: Allowed because it matches one of global allowed URIS: 'https://accounts.google.com/ServiceLogin?service=youtube&uilel=3&passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3D%252Fmusic&hl=en&flowName=GlifWebSignIn&flowEntry=ServiceLogin&cid=1&navigationDirection=forward'.
Runner: [INFO Δ074259us Nuvola] config.vala:223: Config saved to /home/modvavet/.var/app/eu.tiliado.NuvolaAppYoutube/config/nuvolaruntime/apps_data/youtube/config.json
Worker: [DEBUG Δ022736us GVFS-RemoteVolumeMonitor] Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

Worker: [DEBUG Δ000120us  GVFS] cannot open directory /usr/share/gvfs/remote-volume-monitors: Error opening directory “/usr/share/gvfs/remote-volume-monitors”: No such file or directory
Worker: [DEBUG Δ043237us  GVFS] org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

Worker: [DEBUG Δ000282us GLib-GIO] _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
Runner: [DEBUG Δ319115us Nuvola] CefEngine.vala:381: Web Worker Ready
Worker: [DEBUG Δ011635us Nuvola] CefRendererExtension.vala:137: Got JS context
Worker: [INFO Δ008829us CefGtk] RendererContext.vala:57: JS Context created 1
Runner: [DEBUG Δ016109us Nuvola] CefEngine.vala:488: Load started
Worker: [DEBUG Δ01s134941us Nuvola] CefRendererExtension.vala:145: Lost JS context
Worker: [INFO Δ000085us CefGtk] RendererContext.vala:64: JS Context released: 1
Runner: [DEBUG Δ022896us DioriteGlib] DuplexChannel.vala:502: Channel (2) has been closed.
Runner: [DEBUG Δ000365us DioriteGlib] DuplexChannel.vala:328: The channel has already been closed
Runner: [INFO Δ016602us CefGtk] WebView.vala:114: Renderer #1 created.
Runner: [INFO Δ326519us Nuvola] config.vala:223: Config saved to /home/modvavet/.var/app/eu.tiliado.NuvolaAppYoutube/config/nuvolaruntime/apps_data/youtube/config.json
Runner: [INFO Δ01s366476us Nuvola] config.vala:223: Config saved to /home/modvavet/.var/app/eu.tiliado.NuvolaAppYoutube/config/nuvolaruntime/apps_data/youtube/config.json
Runner: [INFO Δ07s557651us Nuvola] config.vala:223: Config saved to /home/modvavet/.var/app/eu.tiliado.NuvolaAppYoutube/config/nuvolaruntime/apps_data/youtube/config.json
Runner: [INFO Δ06s590755us Nuvola] config.vala:223: Config saved to /home/modvavet/.var/app/eu.tiliado.NuvolaAppYoutube/config/nuvolaruntime/apps_data/youtube/config.json
Runner: [INFO Δ03s381981us CefGtk] Client.vala:106: get_life_span_handler
Worker: [DEBUG Δ19s293143us Nuvola] CefRendererExtension.vala:145: Lost JS context
Worker: [INFO Δ001065us CefGtk] RendererContext.vala:64: JS Context released: 1
Runner: [DEBUG Δ054443us DioriteGlib] DuplexChannel.vala:502: Channel (3) has been closed.
Runner: [DEBUG Δ000590us DioriteGlib] DuplexChannel.vala:328: The channel has already been closed

**Comment by fenryxo** [comment]
Hello @modvavet. Thanks for your report. Port to Chrome 75 is in progress (tiliado/valacef#16), Chome 76 is the next and I hope the upgrade solves the issue. There are quite large API changes so it isn't as easy as Chrome 73 → 74.

**Comment by fenryxo** [comment]
I've managed to build Nuvola with the latest Chromium (76.3809), but more testing is needed to be sure there aren't any regressions.

**Comment by fenryxo** [comment]
Hello @modvavet. Could you test with the latest Nuvola 4.16.21 based on Chromium 75.0.3770.100? (Nuvola with Chromium 76 is not ready for prime time yet tiliado/valacef#17.)

**Comment by modvavet** [comment]
Hi All,

Did a 'flatpak update' and all installed Nuvola apps had the new updates
available. After updating. I was able to successfully sign in to Google
Calendar and YouTube!

Great job, and thanks again! :)

**Comment by fenryxo** [comment]
Glad to hear that the issue is resolved for you :-)
