### ISSUE TITLE
Playback stops soon after starting with connectivity error

### ISSUE THREAD

**Issue by spence10101** [tiliado/nuvolaruntime#550]
### Basic information

- Your Linux distribution and its version: Ubuntu 19.04

- Your desktop environment: Gnome

 - Nuvola Runtime version: 4.16.20 (20-gaa3880c)

 - The web app you use and its version: Tidal 1.0.3 (3-g72f3d2f)

### Describe the bug

Playback stops a few seconds after starting and returns to the beginning with error "Could not connect to streaming server. Check your internet connection." Waiting some time on that screen seems to let it play longer, almost if buffering.

I have tried in multiple locations with high speed internet access, that is not the issue.

**Steps to reproduce the behavior**

1. Open Tidal app
2. Press play on something
3. Playback stops after a few seconds with error "Could not connect to streaming server. Check your internet connection," and returns to the beginning.

**Expected behavior**

1. Open Tidal app
2. Press play on something
3. Playback does not stop or buffers properly before continuing (if on slow connection).

[NuvolaTidal_Debug_8-26-19.txt](https://github.com/tiliado/nuvolaruntime/files/3542021/NuvolaTidal_Debug_8-26-19.txt)

![Tidal_Error_8-26-19](https://user-images.githubusercontent.com/43445303/63707032-90fea300-c7f6-11e9-9b6e-44a3d1eaad6e.png)

**Comment by fenryxo** [comment]
Hello @spence10101. Thanks for reporting the issue. Nuvola is going to upgrade the built-in Chromium engine. I'll check this issue afterward.

**Comment by fenryxo** [comment]
I've managed to build Nuvola with the latest Chromium (76.3809), but more testing is needed to be sure there aren't any regressions.

**Comment by fenryxo** [comment]
Hello @spence10101. Could you test with the latest Nuvola 4.16.21 based on Chromium 75.0.3770.100? (Nuvola with Chromium 76 is not ready for prime time yet tiliado/valacef#17.)

**Comment by spence10101** [comment]
Good day @fenryxo! I pulled the latest Nuvola update (4.16.21), the latest Widevine/Chrome plugin downloaded, and it is now working. Thanks very much for your work on this!
