### ISSUE TITLE
Amazon Cloud Player error on various actions after login

### ISSUE THREAD

**Issue by halcyon22** [tiliado/nuvolaruntime#552]
I suspect that Chromium needs to be updated. I've seen this issue in Amazon Music with another app that wraps it with Chromium and had not updated.

### System
OS: Linux Mint 18.3 Sylvia
Arch: x86_64
DE: Cinnamon 3.6.7

### Nuvola
```
$ flatpak run eu.tiliado.NuvolaAppAmazonCloudPlayer --version
Amazon Cloud Player script
Version: 5.9.5
Revision: 5-g01b5575
Maintainer: Andrew Stubbs

--- Powered by ---

Nuvola Apps - Genuine flatpak build
Version 4.16.20
Revision 20-gaa3880c
Diorite 4.16.8
WebKitGTK 2.24.3
Chromium 74.0.3729.131
libsoup 2.66.1
```

### Steps to reproduce

1. Login - works
1. Try to play a global station - error appears
1. Visit a saved station - error appears
1. Try to play any album or saved station - the first time music plays for a second, then an error appears. Subsequent attempts to play work.

![error1](https://user-images.githubusercontent.com/2044014/64345411-ef294400-cfb5-11e9-942b-f39937a145b7.png)

#### Debug log
[debug-output.log](https://github.com/tiliado/nuvolaruntime/files/3579455/debug-output.log)

**Comment by fenryxo** [comment]
Hello @halcyon22. Thanks for taking the time to report this issue, I appreciate that. I'm terribly sorry that I wasn't able to keep up with Chrome releases past months as I switched jobs and moved to a new flat. Two crazy changes at the same time! However, I've recently managed to build Nuvola with Chromium upgraded from 74 to 76 and I hope to iron it out this weekend. There were some radical API changes and I witnessed a few crashes. Keep your fingers crossed :-) Thanks for your patience.

**Comment by halcyon22** [comment]
Not a problem, @fenryxo! Let me know if I can help with testing.

**Comment by fenryxo** [comment]
Hello @halcyon22. Could you test with the latest Nuvola 4.16.21 based on Chromium 75.0.3770.100? (Nuvola with Chromium 76 is not ready for prime time yet tiliado/valacef#17.)

**Comment by halcyon22** [comment]
It's working so far, thanks! 

I updated via `flatpak update --system; flatpak update --user` and am now running:
```
Amazon Cloud Player script
Version: 5.9.5
Revision: 5-g01b5575
Maintainer: Andrew Stubbs
--- Powered by ---
Nuvola Apps - Genuine flatpak build
Version 4.16.21
Revision 21-gce55552
Diorite 4.16.8
WebKitGTK 2.26.0
Chromium 75.0.3770.100
ValaCEF 75.3770.11
libsoup 2.66.1
```

**Comment by fenryxo** [comment]
Glad to hear that the issue is resolved for you :-)
