### ISSUE TITLE
Archlinux installation instructions contain an unsafe command.

### ISSUE THREAD

**Issue by Pdbrantley** [tiliado/nuvolaruntime#558]
The installation instructions for Archlinux located at https://nuvola.tiliado.eu/nuvola/archlinux/  contain the following:

> All packages are available in Arch Linux's extra/community repositories. Run pacman -Sy flatpak xdg-desktop-portal-gtk gnome-software as root/sudo. Then restart your computer to add Flatpak paths alongside the system ones. Otherwise, you may see strange errors. Unfortunately, just logging out and logging in is not enough.

`pacman -Sy flatpak xdg-desktop-portal-gtk gnome-software` is an unsafe command.

From the Archlinux wiki https://wiki.archlinux.org/index.php/Pacman

> Warning: When installing packages in Arch, avoid refreshing the package list without upgrading the system (for example, when a package is no longer found in the official repositories). In practice, do not run pacman -Sy package_name instead of pacman -Syu package_name, as this could lead to dependency issues. See System maintenance#Partial upgrades are unsupported and BBS#89328.

I recommend changing the command to `pacman -Syu flatpak xdg-desktop-portal-gtk gnome-software` to update the package list **update the system** and then install the packages, or simply `pacman -S flatpak xdg-desktop-portal-gtk gnome-software` to install the packages from the current package list without updating.

**Comment by fenryxo** [comment]
Hello @Pdbrantley. Thanks for reporting this issue.

**Comment by fenryxo** [comment]
Fixed. Thanks again :+1:
