### ISSUE TITLE
I didn't have a trial period

### ISSUE THREAD

**Issue by ahmedhamdy90** [tiliado/nuvolaruntime#560]
I didn't have a trial period, I just have installed it and I wanted to make sure the media keys are working before buying it. 

That is what is showing to me:
Trial Started: 12/22/2018
Trial expired: 01/22/2019

Again, I just installed it today!

Kindly find below the debugging information:
[Nuvola (Trial period bug) Debug Information.txt](https://github.com/tiliado/nuvolaruntime/files/3642021/Nuvola.Trial.period.bug.Debug.Information.txt)

**Comment by fenryxo** [comment]
Hello @ahmedhamdy90. Thanks for reporting the issue. Could you provide me with a debugging log? 

See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#debugging-output) for instructions on how to get a debugging log. Then save it as a text file (*.txt) and attach it to the bug report.

- Use the "Attach files by dragging & dropping or selecting them." feature available under the textbox.
- Never trim the logs or you will be asked to provide new complete logs.
- Don't use "pastebin" services as the logs there may disappear anytime.
- Don't attach screenshots of the terminal output. Use text files.

**Comment by ahmedhamdy90** [comment]
Hi @fenryxo,
Thanks for the fast reply, I have updated the post with the debugging log.

**Comment by ahmedhamdy90** [comment]
Is there any news?

**Comment by fenryxo** [comment]
Hello @ahmedhamdy90. I need more information:

1. Remove Nuvola configuration: `rm -r ~/.var/app/eu.tiliado.Nuvola`
2. Launch Nuvola service: `flatpak run --command=nuvola eu.tiliado.Nuvola --debug` and keep it running.
3. Launch Deezer.
4. Attach the log from step 2.

**Comment by ahmedhamdy90** [comment]
@fenryxo Kindly find the log output from step 2 attached.
[Step 2 debugging output.txt](https://github.com/tiliado/nuvolaruntime/files/3713195/Step.2.debugging.output.txt)

**Comment by fenryxo** [comment]
Thanks @ahmedhamdy90. There are no errors in the log so I need to add new debugging calls to investigate the issue further. I hope to manage it this weekend.

**Comment by fenryxo** [comment]
Hello @ahmedhamdy90. I've published new flatpaks so you can try this:

1. Update Nuvola and all Nuvola apps.
2. Remove Nuvola configuration: `rm -rf ~/.var/app/eu.tiliado.Nuvola ~/.var/app/eu.tiliado.NuvolaAppDeezer`
3. Launch Nuvola service: `flatpak run --command=nuvola eu.tiliado.Nuvola --debug` and keep it running.
4. Launch Deezer: `flatpak run eu.tiliado.NuvolaAppDeezer --debug`
5. Accept terms and privacy policy.
6. Attach the log from steps 3 and 4..

**Comment by ahmedhamdy90** [comment]
Hello @fenryxo, I have updated the app, kindly find attached the log from step 3 and 4.
[step 3.txt](https://github.com/tiliado/nuvolaruntime/files/3784396/step.3.txt)
[step 3.txt](https://github.com/tiliado/nuvolaruntime/files/3784397/step.3.txt)

**Comment by fenryxo** [comment]
Hello @ahmedhamdy90. It seems that you attached log 3 once again instead the log 4.

**Comment by ahmedhamdy90** [comment]
@fenryxo Sorry, my mistake, I have updated the last comment with step 4 log.

**Comment by fenryxo** [comment]
There probably was a rare collision of machine-id hash. I removed the old entry from the database. You may now repeat steps 1-4 to start the trial.

**Comment by ahmedhamdy90** [comment]
Yeah, it is working now, thank you very much :)

**Comment by rbbernardino** [comment]
Hello there!

First of all, thank you very much for all your effort, I just discovered this amazing project.

It seems exactly the same thing happened to me... I have here attached my log, where you can see my machine hash:
`nuvolaplayer/fb062368815b105e705355932c4a20ddd98e9ba38ebf0bc9a67abe2322956618`

My setup:
- **Linux Mint 19.2**
- **Cinnamon**
- Nuvola Runtime version **4.16.33 (33-gea8267a)**
- **Idagio** app

Can you help me?

[log_idagio.log](https://github.com/tiliado/nuvolaruntime/files/4499864/log_idagio.log)
[log_runtime.log](https://github.com/tiliado/nuvolaruntime/files/4499865/log_runtime.log)

**Comment by fenryxo** [comment]
Hello @rbbernardino. The machine id hash was removed from the database.
