### ISSUE TITLE
BBC iplayer sound continues after closing

### ISSUE THREAD

**Issue by mupster** [tiliado/nuvolaruntime#561]
In ubuntu 18.04 (Zorin 15 dist) after opening and closing the iplayer app, the sound remains playing.

Only manually killing the runtime process from a terminal terminates the sound:

8019  8018  9 08:36 tty2     00:00:01 nuvolaruntime -a /app/share/nuvolaruntime/web_apps/bbc_iplayer

kill -9 8018

**Comment by fenryxo** [comment]
Hello @mupster. That's expected behavior as [background playback](https://nuvola.tiliado.eu/docs/4/background_playback.html) is enabled by default. You can disable it [in preferences](https://nuvola.tiliado.eu/docs/4/background_playback.html). Does that work for you?

**Comment by mupster** [comment]
Hello @fenryxo - thanks for the pointer - that does indeed work and solves the issue reported !

**Comment by a-m-s** [comment]
Alternatively, you can select "Quit" from the hamburger menu (top left, in Gnome at least).
