### ISSUE TITLE
add music quality info (format, bitrate, etc.)

### ISSUE THREAD

**Issue by mark-senn** [tiliado/nuvolaruntime#564]
Please add the music quality information somewhere so I know for sure what format, bitrate, etc. I'm listening to.  Amazon has this in the HD Amazon Music for Windows application.  They have a yellow rectangle next to the song titles that one can click on to get the info.  I think I'd prefer unconditionally printing that somewhere on the screen though.  I'll pay 100 U.S. dollars if you implement this---even if it is in the for-money version of the software.

(I couldn't figure out any way to see this information from within the application.)

**Comment by a-m-s** [comment]
I don't believe the Amazon web player provides such information. There's a bitrate selection template in the page source, but I can't see any evidence that it ever gets used.

The music itself is hidden behind DRM and played through Widevine (unless you own the playing track). As far as I know all the music is standard MP3.

**Comment by fenryxo** [comment]
I'm not sure whether Amazon supports high-quality music in web browsers with Widevine (Tidal does though). If information about bitrate is not provided by the web player, as @a-m-s said, there is no easy way to get that info. It might be somehow possible in low-level Chromium code, but I don't have time to explore this option. I'm sorry but our team is small.
