### ISSUE TITLE
Enable the possibility to set up the keyboard shortcut for I'm Feeling Lucky action in Google Music

### ISSUE THREAD

**Issue by vlnn** [tiliado/nuvolaruntime#565]
**Is your feature request related to a problem? Please describe:**

When I want to start/change autogenerated "I'm feeling lucky" playlist I have to click the dice icon with the mouse. I can't use keyboard for this, which is sad.

**Describe the solution you'd like:**

I would like to extend the list of possible keyboard shortcuts with new action "I'm Feeling Lucky". As those are user-configured, no drawbacks from the UX side can be seen at the moment (by me).

**Describe alternatives you've considered:**

No such thing.

**Additional context:**

No such thing.

**Comment by fenryxo** [comment]
Hello @vlnn, thanks for your feature request.

**Comment by fenryxo** [comment]
Google Play Music is EOL  #660.
