### ISSUE TITLE
Nuvola Deezer App Not Responding - At All After Starting It

### ISSUE THREAD

**Issue by skiski-spam** [tiliado/nuvolaruntime#569]
### Basic information

- Your Linux distribution and its version: Description:	Ubuntu 18.04.3 LTS
   

- Your desktop environment: GNOME
   

 - Nuvola Runtime version: eu.tiliado.Nuvola/x86_64/stable                    system,current
                                          eu.tiliado.NuvolaAppDeezer/x86_64/stable           system,current

   

 - The web app you use and its version: Deezer 3.2.0 (0-gb04e220)
   

### Describe the bug

The Deezer app is unresponsive. I start the Deezer app inthe normal way. It displays the user interface, with the last playlist i accessed. Then the app does not respond to any mouse click in the main window. 

The app does respond to mouse clicks in the sidebar, and to enable/disable to sidebar. 

**Steps to reproduce the behavior**

1. Start the Deezer app using the app icon
2. Wait for the  app main window to be displayed
3. Click anywhere you like in the main window (track, search, column headers, whatever)  
4. Nothing happens - there is no response. 

**Expected behavior**

1. When I click on a column header, the list of tracks should be sorted by that column
2. When I click on a track, that track should start to play
3. When I click on favourites or favourite tracks, then they should be shown

**Debugging log**

Attach the debug log here: 
[nuvola_debug.txt](https://github.com/tiliado/nuvolaruntime/files/3908292/nuvola_debug.txt)

ski@skibuntumusic:~$ flatpak run eu.tiliado.NuvolaAppDeezer --debug
Runner: [DEBUG Δ007185us GVFS-RemoteVolumeMonitor] Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown
[nuvola_debug.txt](https://github.com/tiliado/nuvolaruntime/files/3908287/nuvola_debug.txt)
[nuvola_debug.txt](https://github.com/tiliado/nuvolaruntime/files/3908288/nuvola_debug.txt)
[nuvola_debug.txt](https://github.com/tiliado/nuvolaruntime/files/3908290/nuvola_debug.txt)

: org.freedesktop.DBus.Error.ServiceUnknown

Runner: [DEBUG Δ001927us  GVFS] cannot open directory /usr/share/gvfs/remote-volume-monitors: Error opening directory “/usr/share/gvfs/remote-volume-monitors”: No such file or directory
Runner: [DEBUG Δ013571us  GVFS] org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

Runner: [DEBUG Δ000215us GLib-GIO] _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
Runner: [DEBUG Δ028155us Nuvola] AboutDialog.vala:55: Nuvola Apps 4.16.22 (22-g1bf660b)
Runner: [DEBUG Δ000032us Nuvola] AboutDialog.vala:57: Deezer script 3.2.0 (0-gb04e220)
Runner: [DEBUG Δ000032us Nuvola] AboutDialog.vala:61: Diorite 4.16.8
Runner: [DEBUG Δ000069us Nuvola] AboutDialog.vala:63: Chromium 75.0.3770.100
Runner: [DEBUG Δ000039us Nuvola] AboutDialog.vala:64: ValaCEF 75.3770.11
ski@skibuntumusic:~$ 

**Screenshots**

Attach screenshots here: None

**Additional context**

None

**Comment by skiski-spam** [comment]
I have looked back at this error again, and it may be linked to the appearance of a cookie message in the main window of the Deezer app. This is a fairly standard 'this website uses cookies' message, with buttons "I  agree" and to "review settings and learn more". 

Like the rest of the main window, the buttons on the cookie section are totally dead.

**Comment by fenryxo** [comment]
Hello @skiski-spam. Thanks for reporting the issue. I'm afraid I cannot reproduce the issue on my system so it might be hard to fix it. If you've purchased Nuvola Premium license, you can ask for a refund.

**Comment by fenryxo** [comment]
Is it still an issue with the latest Nuvola? Could you update all Flatpak runtimes, reboot your system and try again?

```
flatpak update --system
flatpak update --user
```
