### ISSUE TITLE
Ubuntu 18.04 nvidia-410-48 support

### ISSUE THREAD

**Issue by davidlavy88** [tiliado/nuvolaruntime#572]
### Basic information

- Your Linux distribution and its version: Ubuntu 18.04
   

- Your desktop environment: GNOME
   

 - Nuvola Runtime version: 4.16.22
   

 - The web app you use and its version: Youtube Music 1.3.2
   

### Describe the bug

Graphics driver 'nvidia-410-48' for Flatpak has not been found on your system. Please consult documentation on graphics drivers to get help with installation.

**Steps to reproduce the behavior**

I'm running nuvola service

**Expected behavior**

...

**Debugging log**

Attach the debug log here: ...

**Screenshots**

Attach screenshots here: ...

**Additional context**

...

**Comment by fenryxo** [comment]
Hello @davidlavy88. I'm afraid version 410.48 [is not available for download from Nvidia](https://www.nvidia.com/en-us/drivers/unix/linux-amd64-display-archive/). Is it possible to upgrade to a newer version?

**Comment by davidlavy88** [comment]
Oh, that's weird. I have a specific setup for my work and I'm afraid it will break if I update my version. Is there any workaround?

**Comment by fenryxo** [comment]
It is possible to create [an unmanaged extension with the driver](https://github.com/tiliado/nuvolaruntime/wiki/Graphics-Drivers#host-driver-as-unmanaged-extension). Could you follow the instructions? If you don't have the installation package as mentioned in the second step, you should be able to copy the necessary files from your system.

**Comment by davidlavy88** [comment]
Thank you! That seemed to work. I have a question, although this has seemed to work fine, when I ran the last command I got this output: 

`$ flatpak run --command=ls org.gnome.Platform//3.32 -lhR /usr/lib/x86_64-linux-gnu/GL
error: app/org.gnome.Platform/x86_64/3.32 not installed
`
Is this an issue?

**Comment by fenryxo** [comment]
You probably have `org.gnome.Platform//3.34` and that's ok.
