### ISSUE TITLE
Cant Start anything

### ISSUE THREAD

**Issue by madox85** [tiliado/nuvolaruntime#573]
Hi. 
Currently I am not able to start anything of Nuvola. 
If I am trying to start:

flatpak run eu.tiliado.Nuvola
Error: No command specified. Type `nuvolactl --help` for help.
Launching service info...

flatpak run eu.tiliado.NuvolaAppAmazonCloudPlayer it just hangs and nothing else happens.

flatpak run eu.tiliado.NuvolaAppDeezer
Runner: [WARNING Δ820600us Nuvola] StartupWindow.vala:146: tiliado-account-message: Features Tier: Free (because I can not Enter my licence)

What can I do? Thanks for your help!

---

### Basic information

- Your Linux distribution and its version: Ubuntu 18.04
   

- Your desktop environment: GNOME
   

 - Nuvola Runtime version: Not possible, because it does not start. (probably. 4.16.0.22)
   

 - The web app you use and its version: Deezer3.2.0
   

### Describe the bug

...

**Steps to reproduce the behavior**

Just start, as already discribed.

**Expected behavior**

It should start. But not Nuvola itself nor deezer are starting. There are no error messages. Please see also other posts, where I already discribed it. (Nothing really happens.)

**Debugging log**

Attach the debug log here: 
[Deezerdebuglog.txt](https://github.com/tiliado/nuvolaruntime/files/3973519/Deezerdebuglog.txt)
[Amazondebuglog.txt](https://github.com/tiliado/nuvolaruntime/files/3973527/Amazondebuglog.txt)
[generallog.txt](https://github.com/tiliado/nuvolaruntime/files/3973533/generallog.txt)

**Screenshots**

Attach screenshots here: Nothing visible happens, so I dont have one. ;)

**Additional context**

...

Thanks again for your help!

**Comment by fenryxo** [comment]
Hello @madox85. I've updated your report with a bug reporting template. Could you provide me with more information by filling the template? Thanks :-)

**Comment by madox85** [comment]
Hi @fenryxo , first of all, thank you. :) 

Basic information

    Your Linux distribution and its version: Linux version 5.0.0-37-generic (buildd@lcy01-amd64-023) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019


    Your desktop environment: Ubuntu Default Desktop

    Nuvola Runtime version: 4.16.0.22

    The web app you use and its version: Deezer 3.2.0

Describe the bug

Currently I am not able to start anything of Nuvola.
If I am trying to start:

flatpak run eu.tiliado.Nuvola
Error: No command specified. Type nuvolactl --help for help.
Launching service info...

flatpak run eu.tiliado.NuvolaAppAmazonCloudPlayer it just hangs and nothing else happens.

flatpak run eu.tiliado.NuvolaAppDeezer
Runner: [WARNING Δ820600us Nuvola] StartupWindow.vala:146: tiliado-account-message: Features Tier: Free (because I can not Enter my licence)

Steps to reproduce the behavior

    Go to bash and enter commands as above. 
    Click on Deezer App Symbol: Nothing seems to happen
        See error: No real error message. It just wont start. 

Expected behavior

Normal start of deezer app

Debugging log

Attach the debug log here: How?

Screenshots

Nothing happen, what I can screenshot. 

Additional context

...

Hope that will help.

**Comment by fenryxo** [comment]
> Attach the debug log here: How?

Oh, sorry. I forgot to tell you that you need to edit your report (three dots → Edit). You will then see comments with instructions which are visible only during editing:

See https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#debugging-output
for instructions on how to get a debugging log. Then save it as a text file (*.txt) and attach it to the bug report.

- Use the "Attach files by dragging & dropping or selecting them." feature available under the textbox.
- Never trim the logs or you will be asked to provide new complete logs.
- Don't use "pastebin" services as the logs there may disappear anytime.
- Don't attach screenshots of the terminal output. Use text files.

**Comment by madox85** [comment]
Hi @fenryxo ,
I did it. Hope, that will help. And thanks for your explanation and assistance. :)
Regards.

**Comment by fenryxo** [comment]
Could you try again with the latest Nuvola? Also update all Flatpak runtimes and reboot your system.

```
flatpak update --system
flatpak update --user
```
