### ISSUE TITLE
Cant install Nuvola

### ISSUE THREAD

**Issue by android9pie2** [tiliado/nuvolaruntime#574]
When i try and install Nuvola using flatpak, it says: error: Can't find eu.tiliado.Nuvola in remote nuvola, I am using a raspberry pi 3 model b running raspbian stretch with an xfce desktop environment.

**Comment by fenryxo** [comment]
Hello @android9pie2. Thanks for reporting the issue. We currently provide builds only for amd64 platform. ARM (raspberry pi) is not supported and it is unlikely it will ever be.
