### ISSUE TITLE
Google sign-in needs newer browser

### ISSUE THREAD

**Issue by sebawild** [tiliado/nuvolaruntime#575]
I'm using the Google Calendar app, and since today cannot sign into my google account. Google complains the browser is too old and insecure.
Can you update the underlying Chrome version?

Nuvola runtime version 4.16.22 (22-g1bf660b)
Google cal script version 1.3.2 (2-g41538c1)

**Comment by fenryxo** [comment]
Hello @sebawild. Thanks for reporting the issue. There was a major problem in upgrading to Chrome 76 (tiliado/valacef#17). I'll try Chrome 78 instead. Keep fingers crossed :-)

Btw the Google Calendar app will be deprecated in Nuvola 4.17 and not included in Nuvola 5. I want to simplify the architecture (single window mode) & installation (targeting Flathub) and focus only on music streaming apps. However, I expect Nuvola 4.x to be supported until the end of 2020.

**Comment by dhitchcock** [comment]
same problem with Youtube Music

**Comment by fenryxo** [comment]
It might help to set the user agent to Firefox (!!!): `Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0`. It works in Falkon.

Also, [‘Couldn’t Sign You In’ — Google Denies Access to Several Linux Browsers](https://www.omgubuntu.co.uk/2019/12/couldnt-sign-you-in-google-browser-error-linux).

**Comment by ondrejholy** [comment]
@fenryxo Is there any easy way to change the user-agent string for nuvola without rebuilding it manually?

**Comment by fenryxo** [comment]
> Is there any easy way to change the user-agent string for nuvola without rebuilding it manually?

No, there isn't.

**Comment by fenryxo** [comment]
Hello @sk8darr, @K4S1, @sebawild, @dhitchcock, @ondrejholy. Could you test with the latest Nuvola flatpaks (4.16.30 )?

**Comment by sk8darr** [comment]
> Hello @sk8darr, @K4S1, @sebawild, @dhitchcock, @ondrejholy. Could you test with the latest Nuvola flatpaks (4.16.30 )?

it's working like a charm

![image](https://user-images.githubusercontent.com/1724673/74090847-fa593200-4a75-11ea-9e95-1826e17cbc88.png)

**Comment by regisz** [comment]
yes, yes, yes, it works! :) Thx a lot!

**Comment by ondrejholy** [comment]
It works fine now, great job!

**Comment by K4S1** [comment]
<3
Works !
Thanks for great and very fast response !!!
I'll be enjoining my music now :P

**Comment by fenryxo** [comment]
I'm glad it works for you. However, I recommend switching to another service. Google is getting increasingly hostile to all browsers that are not Google Chrome. The current workaround, masking Nuvola as *Safari browser on Mac OS X*, might not work forever.
