### ISSUE TITLE
Unable to add keyboard shortcuts to some Numpad Keys

### ISSUE THREAD

**Issue by Schleuse** [tiliado/nuvolaruntime#577]
### Basic information

- Your Linux distribution and its version: Ubuntu 19.10
   

- Your desktop environment: Budgie
   

 - Nuvola Runtime version: 4.16.22
   

 - The web app you use and its version: Plex Music script 1.5.0 (0-ge41e59d)
   

### Describe the bug

Keybindings on Numpad Keys seem not to work. If I bind a command to <kbd>Numpad 6</kbd> for example, the following output is logged in the syslog

```
eu.tiliado.Nuvola[1333]: Master: [WARNING Δ503963us Nuvola] XKeyGrabber.vala:162: Unknown keybinding <Primary>KP_Right
```
Binding to Numpad <kbd>+</kbd> or <kbd>-</kbd> are working fine.

**Steps to reproduce the behavior**

1. Go to 'Preferences'
2. Click on 'Keyboard Shortcuts'
3. Add a global keybinding for <kbd>CTRL</kbd> + <kbd>Numpad 6</kbd>
4. Press <kbd>CTRL</kbd> + <kbd>Numpad 6</kbd>
4. See error in syslog

**Expected behavior**

Keybinding for numpad key should work as any other binding

**Debugging log**

Attach the debug log here:

```
eu.tiliado.Nuvola[1333]: Master: [WARNING Δ503963us Nuvola] XKeyGrabber.vala:162: Unknown keybinding <Primary>KP_Right
```

**Comment by fenryxo** [comment]
Hello @Schleuse, thanks for reporting the issue.

**Comment by fenryxo** [comment]
Hello @Schleuse, could you [provide me with the full debugging output](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#debugging-output)? Thanks.

**Comment by fenryxo** [comment]
Closing as I cannot proceed further without a debugging log.
