### ISSUE TITLE
Widevine not installable

### ISSUE THREAD

**Issue by Schmetzler** [tiliado/nuvolaruntime#580]
Hello there,
it seems like that in the newest version of Chrome `libwidevinecdmadapter.so` is no longer distributed (only `libwidevinecdm.so`). This prevents widevine from getting installed on nuvola (as the software states, that widevine is not available in the package)

Maybe widevine works without that adapter?

And it would be nice if there is a way to manually install the plugin. But I didn't find any information on where to place the file.

I will now look into the source and search for the install location, maybe I can find the appropriate location.

OS: Manjaro x64
Installed: Amazon Music Cloud Player

EDIT:
Okay after inspecting the source it might not be a problem with the missing adapter file, but with the download of the deb file (it does not throw an exception, but maybe it does and I just don't see it)

**Comment by Schmetzler** [comment]
If I start the flatpak with root privileges I can install widevine but xdg library does not working.
And after I start the flatpak again without root it cannot install the widevine plugin.

What am I doing wrong?

**Comment by fenryxo** [comment]
Hello @Schmetzler. I cannot reproduce your issue. 

Could you obtain [a debugging log](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#debugging-output)? Then save it as a text file (*.txt) and attach it to the bug report.

- Use the "Attach files by dragging & dropping or selecting them." feature available under the textbox.
- Never trim the logs or you will be asked to provide new complete logs.
- Don't use "pastebin" services as the logs there may disappear anytime.
- Don't attach screenshots of the terminal output. Use text files.

**Comment by Schmetzler** [comment]
I found a partial solution. I found the widevine folder in home directory of root (`/root/.var/.../widevine`) and copied it to my home folder. It detects the widevine plugin, but now it is taking forever to start the Amazon Cloud Player. ... Maybe I need to mention that i am using KDE.

I tried to remove the widevine folder, but nuvola now detects it even if it is not in place (maybe it does not check again?)

I added the little log that was print out after trying to start it.  
It is now idling for 10 minutes (And states the the player will load in a few seconds). On Thursday it started somewhen but I do not know how long it took. (Because I was some hours absent from PC)

[log.txt](https://github.com/tiliado/nuvolaruntime/files/4152515/log.txt)

**Comment by fenryxo** [comment]
Log says:
```
Runner: [DEBUG Δ003153us Nuvola] CefWidevineDownloaderDialog.vala:46: Need to install Widevine.
Runner: [WARNING Δ29s691490us Nuvola] CefPluginDownloaderDialog.vala:152: NuvolaCefWidevineDownloader: installation cancelled.
```

Did you click cancel?

**Comment by Schmetzler** [comment]
Of course, after I clicked accept License agreement and clicked install.
And clicked install again (because nothing happens) at some point I have to click cancel because nothing happens. 

The problem is that it does not install and also does not give an appropriate error message in the log.
(I am currently not at the machine, but as I recall. I click install -> it just says something (like try again .. or so) --> I have to accept license again --> click install --> and so on. To close the program (to get the complete log) I have to click on cancel.)

**Comment by fenryxo** [comment]
I see. I've added more logging to Nuvola **4.16.31**. Could you provide me with a new log? Thanks.

**Comment by Schmetzler** [comment]
Whatever you did, now it works flawlessly,
the plugin is installed and the web app opened.
Either way I added the log.

If it somehow makes sense you can close the issue.

Thank you.

[New_log.txt](https://github.com/tiliado/nuvolaruntime/files/4186253/New_log.txt)

**Comment by fenryxo** [comment]
There was no change in functionality except for the logging. Whatever the issue was, it just disappeared. I was never able to reproduce it on my system, so I assume that something changed on yours.

Anyway, the issue is gone and we have better logging in place to investigate it if it appears again :-)
