### ISSUE TITLE
Not installing in Kubuntu 19.10 Kde 5.18

### ISSUE THREAD

**Issue by EvilSpark** [tiliado/nuvolaruntime#581]
After Installing Flatpak and friends, then rebooting. And then after enabling those 2 repos.

When I try to install Nuvola Service or any app like Nuvola Spotify through Discover or through Terminal, both of them shows this error- 
`error: The application eu.tiliado.NuvolaAppSpotify/x86_64/stable requires the runtime org.gnome.Platform/x86_64/3.34 which was not found`

Any idea why this is happening?

OS: Ubuntu 19.10 x86_64 
Kernel: 5.3.0-29-generic 
DE: KDE

**Comment by blauch** [comment]
have you tried `flatpak install org.gnome.Platform` ?

**Comment by EvilSpark** [comment]
doing flatpak update fixed it.
