### ISSUE TITLE
KDE Media Keys not working 

### ISSUE THREAD

**Issue by blauch** [tiliado/nuvolaruntime#582]
My system:
Manjaro Linux (18.1.5)
KDE 5.66.0
Plasmashell 5.17.5
kernel 5.4.15-2
Flatpak 1.6.0. 

Previously I was able to control Nuvola media players (e.g. Soundcloud or Amazon Music) with the media keys in KDE. The app would be visible in the media player widget. I believe this functionality was broken with some recent update. At the time when I was able to use the media keys I saw the app in the media player widget - since it is not there anymore I am also unable to use  `XF86AudioPlay`, `XF86AudioPause` and `XF86AudioStop`. Volume controls are still working. I can control other players like VLC without problems.

**Comment by fenryxo** [comment]
Hello @blauch. Do you have features [Media Player DBus Interface](https://nuvola.tiliado.eu/docs/4/mpris.html) and [Multimedia Keys](https://nuvola.tiliado.eu/docs/4/media_keys.html) toggled on in preferences?

**Comment by blauch** [comment]
I have re-installed the apps but still no luck. Thanks for the hint with the DBus interface. Now the app shows up in the media player widget in KDE. But I am still not able to use the media buttons.

**Comment by fenryxo** [comment]
You still haven't replied whether you have Multimedia Keys toggled on in Nuvola preferences.

**Comment by blauch** [comment]
Yes, I have both enabled but it's still not working.

Jiří Janoušek <notifications@github.com> schrieb am Mi., 5. Feb. 2020,
12:04:

**Comment by fenryxo** [comment]
In bug triaging, it is harmful to make any assumptions. That's why I needed to get explicit confirmation from you.

Could get [debugging output](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#debugging-output)?  Then save it as a text file (*.txt) and attach it to the bug report.

- Use the "Attach files by dragging & dropping or selecting them." feature available under the textbox.
- Never trim the logs or you will be asked to provide new complete logs.
- Don't use "pastebin" services as the logs there may disappear anytime.
- Don't attach screenshots of the terminal output. Use text files.

**Comment by blauch** [comment]
I have opened SoundCloud in debug mode and hit the play button a few times. Please see attached debug output: [debug.txt](https://github.com/tiliado/nuvolaruntime/files/4159894/debug.txt)

I also noticed some warnings in the system logs when hitting the play button 

```Feb 05 15:05:04 christoph-xps eu.tiliado.Nuvola[1018]: Master: [WARNING Δ11s856455us Nuvola] XKeyGrabber.vala:162: Unknown keybinding AudioPlay
Feb 05 15:05:05 christoph-xps eu.tiliado.Nuvola[1018]: Master: [WARNING Δ01s210706us Nuvola] XKeyGrabber.vala:162: Unknown keybinding AudioPlay
Feb 05 15:05:08 christoph-xps eu.tiliado.Nuvola[1018]: Master: [WARNING Δ03s110016us Nuvola] XKeyGrabber.vala:162: Unknown keybinding AudioPlay
Feb 05 15:05:09 christoph-xps eu.tiliado.Nuvola[1018]: Master: [WARNING Δ538877us Nuvola] XKeyGrabber.vala:162: Unknown keybinding AudioPlay
Feb 05 15:05:10 christoph-xps eu.tiliado.Nuvola[1018]: Master: [WARNING Δ01s180981us Nuvola] XKeyGrabber.vala:162: Unknown keybinding AudioPlay
Feb 05 15:05:11 christoph-xps eu.tiliado.Nuvola[1018]: Master: [WARNING Δ459005us Nuvola] XKeyGrabber.vala:162: Unknown keybinding AudioPlay
Feb 05 15:05:21 christoph-xps eu.tiliado.Nuvola[1018]: Master: [WARNING Δ10s871347us Nuvola] XKeyGrabber.vala:162: Unknown keybinding AudioPlay
Feb 05 15:05:23 christoph-xps eu.tiliado.Nuvola[1018]: Master: [WARNING Δ01s728833us Nuvola] XKeyGrabber.vala:162: Unknown keybinding AudioPlay
```

**Comment by fenryxo** [comment]
That's from Nuvola service. Could you provide the full log? It must be launched before SoundCloud.

```
flatpak run --command=nuvola eu.tiliado.Nuvola --debug
```

**Comment by blauch** [comment]
My bad! Here the correct debug output

* [debug_soundcloud.txt](https://github.com/tiliado/nuvolaruntime/files/4161334/debug_soundcloud.txt)
* [debug_nuvola.txt](https://github.com/tiliado/nuvolaruntime/files/4161335/debug_nuvola.txt)

**Comment by fenryxo** [comment]
Could you test with the latest Nuvola (4.16.30)?

**Comment by blauch** [comment]
the update for the latest Nuvola (4.16.30) came through and the problem is solved! 

Many Thanks!
