### ISSUE TITLE
Youtube Music: login problem

### ISSUE THREAD

**Issue by regisz** [tiliado/nuvolaruntime#585]
Hi,

I tried to use Youtube Music, everything were installed well, but I can not login into my youtube profile.
I tried to use application password too, because I use two-step auth, but it could not help.
By the way, I can use Google Play Music well (not auth problem), the two-step auth works well.
Any idea?
Thx!
Balázs

**Comment by ondrejholy** [comment]
This seems to be a duplicate of https://github.com/tiliado/nuvolaruntime/issues/575.

**Comment by regisz** [comment]
yes, this is my problem too
