### ISSUE TITLE
Youtube Music always start with Greybird by default on Gnome 3.34 (Adwaita)

### ISSUE THREAD

**Issue by pedrofleck** [tiliado/nuvolaruntime#586]
I'm using Fedora 31 with Gnome 3.34 and the default Adwaita theme, however, whenever I start the app, it is using Greybird. I go to the settings, change it to "default" and, if I close and open again, there is Greybird again. I'm using the "prefer a dark variant" setting enabled.

**Nuvola Runtime version:** 4.16.26
**YoutTube Music version:** 1.3.2

The attached text file is the output of running `eu.tiliado.NuvolaAppYoutubeMusic --debug`, waiting the web page to load and closing again: [Nuvola Greybird.txt](https://github.com/tiliado/nuvolaruntime/files/4192069/Nuvola.Greybird.txt)

**Comment by fenryxo** [comment]
Hello @pedrofleck. Thanks for reporting the issue. Could you update to the latest Nuvola flatpaks (Nuvola 4.16.31, Diorite 4.16.11)? You should be now able to select Adwaita in preferences and it should persist after the restart of the app.

**Comment by pedrofleck** [comment]
Wow, that was fast. I didn't use the computer until now, I booted and saw there was an update for Nuvola in the Software app. I updated, opened YouTube Music and voilá: correct theme (I didn't even have to change it), it also persisted after restarting the app. Thanks a lot!

**Comment by fenryxo** [comment]
Great :-)
