### ISSUE TITLE
Built in adblock

### ISSUE THREAD

**Issue by jimbob88** [tiliado/nuvolaruntime#587]
I would love to see a built in adblock for the YoutubeMusic App so as to remove annoying ads that appear during music listening. 

**Describe the solution you'd like:**

I would happily see it as a premium feature - I would definitely pay premium for this feature - that could be turned on or off within a menu setting perhaps? The issue with this is obviously that the original artist would not get all of the revenue from their music so paying for youtube premium may be preferable, although would cost a lot more ;(.

Thanks in advance,
James B

**Comment by fenryxo** [comment]
Hello @jimbob88. Thanks for your idea. However, I have no plans to implement any ad blocking in Nuvola for two reasons:

1. There are far more pressing issues than ad blocking, especially porting Nuvola to a new web engine sooner than the current one stops working.

2. I fully respect advertisement as a valid monetization method and I don't want to cause any financial harm to music streaming services Nuvola depends on. At least one streaming service goes out of business every year. If you don't like ads, you should choose a service that offers an ad-free premium account or a service that doesn't use ads at all.

I'm closing this ticket in favor of #412 - once Nuvola gets support for Chrome extensions, users will be able to use any ad-blocker they wish.
