### ISSUE TITLE
Is there a way to debug why my multimedia keys are not working?

### ISSUE THREAD

**Issue by themightyjanbur** [tiliado/nuvolaruntime#588]
I have them enabled in preferences (along with DBUS) but none of the keys are working.  The volume keys are working, but they control the desktop volume, not the app volume.

Ubuntu 18.04
Amazon cloud player 5.9.6
Nuvola Runtime 4.16.31

[debug.txt](https://github.com/tiliado/nuvolaruntime/files/4219768/debug.txt)

Thanks,

Brian

**Comment by fenryxo** [comment]
Hello, I've added more debugging info for media keys in the latest Nuvola build. Could you upgrade and provide me with new logs? Thanks.

**Comment by themightyjanbur** [comment]
Hey there fenryxo... this problem had been going on for a few months, but I had not rebooted my machine.  Yesterday, the machine froze due to something unrelated, so I rebooted.  When it came back up, the mm keys worked!  So, it is not happening now, which makes me quite happy, but it also means I won't have useful debug output until it happens again (if it happens again).  My gut feel on it is that something else camped onto the mm keys and wouldn't let them go, but I have no proof of that, nor any idea if that is even possible.  Please feel free to close this issue if you want and if it happens again, I will get you the improved debug output.  Thanks so much for the quick response time!

**Comment by fenryxo** [comment]
> My gut feel on it is that something else camped onto the mm keys and wouldn't let them go, but I have no proof of that, nor any idea if that is even possible.

This is a very likely explanation.

**Comment by brianredbeard** [comment]
FYI, I put a note about this [in the wiki](https://github.com/tiliado/nuvolaruntime/wiki/Fixing-Hardware-Media-Keys), but I found that Google Chrome itself was intercepting the keys (without any additional configuration from my part).  

Try going to chrome://flags/#hardware-media-key-handling and then explicitly disabling support in Chrome.

**Comment by fenryxo** [comment]
Thanks, @brianredbeard. I should add it to user documentation.

**Comment by fenryxo** [comment]
Documentation updated: https://nuvola.tiliado.eu/docs/4/media_keys.html
