### ISSUE TITLE
Application still runs in background after closing it through Cross icon.

### ISSUE THREAD

**Issue by BetaZeon** [tiliado/nuvolaruntime#593]

**Comment by fenryxo** [comment]
Hello @BetaZeon. Nuvola [runs in the background when music is playing](https://nuvola.tiliado.eu/docs/4/background_playback.html) by default. You can [change it](https://nuvola.tiliado.eu/docs/4/background_playback.html). Does it help?

**Comment by fenryxo** [comment]
I hope my comment helped. Closing.
