### ISSUE TITLE
Playback only with alsa, without PulseAudio

### ISSUE THREAD

**Issue by mrkapqa** [tiliado/nuvolaruntime#594]
Hello ,

i use a Debian/Devuan box with alsa only.

it seems that the apps are nont playing back when pulseaudio is not installed.

any workaround for this?

Thanks!

**Comment by fenryxo** [comment]
Hello @mrkapqa, I'm afraid I cannot think of any workaround for that.

**Comment by fenryxo** [comment]
It might be possible with `--device=all` but I'm not going to explore this path.
