### ISSUE TITLE
Google Play Music: 5-star rating system

### ISSUE THREAD

**Issue by marek287** [tiliado/nuvolaruntime#598]
Is this possible to implement 5 start rating system back to google play music?
I found this Tampermonkey script:
https://github.com/Velenir/google-play-music-star-ratings/blob/master/GPMusic-stars-rating.jQuery.js

https://productforums.google.com/d/msg/play/HwKmVF5N5YA/elrxaUL_BgAJ

:heart: **One [Nuvola Patron](https://tiliado.eu/nuvolaplayer/funding/) is interested in this feature.** Internal info: [(1)](https://tiliado.eu/admin/tiliado_funding/patron/64/).
##

**Comment by fenryxo** [comment]
Google Play Music is EOL  #660.
