### ISSUE TITLE
Google Play Music: "Add Album to Queue" and "Play Album Next" don't work in Chromium build

### ISSUE THREAD

**Issue by markstos** [tiliado/nuvolaruntime#599]
Blocked by tiliado/valacef#11

Hello, I'm testing the Chromium backend. Version 6, on Nuvola Apps 4.9.96.

I'm looking at my Recently Played page.  I click on an album and select from the "dot dot dot" menu the option "Play Album Next" or "Add Album to Queue". Then I look in the queue in the lower right and it's empty. 

To confirm this is a bug, I repeated the same steps in Firefox and confirmed albums were added to the queue. 

I tried again with the DevTools console open. I saw no errors in the "Console" tab, and no failed requests in the "Network" tab.

These features also works in the WebKit version.

**Comment by fenryxo** [comment]
Nuvola will change its rendering engine again (#583). The good news is that it will be implemented via offscreen rendering, which could fix this issue. Keep fingers crossed.

**Comment by fenryxo** [comment]
Google Play Music is closing... #660
