### ISSUE TITLE
Blank screen on DeezerApp (3.2.0) launch (Nuvola 4.16.33)

### ISSUE THREAD

**Issue by FernandoDonati** [tiliado/nuvolaruntime#604]
### Basic information

- Your Linux distribution and its version: Ubuntu 18.04

- Your desktop environment: GNOME 

 - Nuvola Runtime version: 4.16.33 (33-gea8267a)

 - The web app you use and its version: Deezer 3.2.0 (0-gb04e220)

### Describe the bug

Can't login on Deezer. After launching app, it seems to be loading for a short while then nothing happens (stays on a blank page).

**Steps to reproduce the behavior**

1. Launch app.

**Expected behavior**

1. Loading homepage or login page (as it's been a few days since I used Deezer on this machine)

**Debugging log**

Attach the debug log here: 
[debug.txt](https://github.com/tiliado/nuvolaruntime/files/4575228/debug.txt)

**Screenshots**

Attach screenshots here: 
![Screenshot from 2020-05-04 11-27-22](https://user-images.githubusercontent.com/7408748/80976798-43f9b480-8dfa-11ea-9695-2eae96427d21.png)

**Additional context**

I tried reinstalling AppDeezer but no success. Other apps, like YouTube for example, work as usual.

**Comment by fenryxo** [comment]
Hello @FernandoDonati, is the issue resolved?

**Comment by FernandoDonati** [comment]
Yes! Maybe it was something on Deezer's side (I think the problem had something to do with a script while loading the page)... I tried launching again today and no problems at all, even after logging off and on, reinstalling, rebooting and whatnot :stuck_out_tongue:
