### ISSUE TITLE
Missing Arts on GNOME Notifications

### ISSUE THREAD

**Issue by FastOSlinux** [tiliado/nuvolaruntime#605]
![Captura de tela de 2020-05-07 17-29-00](https://user-images.githubusercontent.com/17401812/81341842-9a7c2280-9088-11ea-8b91-11804cf5670d.png)

```
$ cat /etc/issue /etc/*release

GNOME Wayland
Fedora release 32 (Thirty Two)
NAME=Fedora
VERSION="32.20200505.0 (Silverblue)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32.20200505.0 (Silverblue)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='32.20200505.0'
Fedora release 32 (Thirty Two)
Fedora release 32 (Thirty Two)

```
`$ flatpak info eu.tiliado.NuvolaAppDeezer 

Deezer • Nuvola App - Web app running in Nuvola Apps Runtime.

        ID: eu.tiliado.NuvolaAppDeezer
       Ref: app/eu.tiliado.NuvolaAppDeezer/x86_64/stable
      Arq.: x86_64
      Ramo: stable
   Licença: BSD-2-Clause
    Origem: nuvola
   Coleção: 
Instalação: system
 Instalado: 267,4 MB
   Runtime: org.gnome.Platform/x86_64/3.34
       Sdk: org.gnome.Sdk/x86_64/3.34

    Commit: 0c4fe3ca6958ca2766fd7a51e74b24deac3684f76abcf574194805f243a509f1
       Pai: 370e845e2fe5944ba36715ae150997259c62ebbe24f5a077b69c1ff6f3358d57
   Assunto: Import deezer 3.2.0
      Data: 2020-04-05 10:20:08 +0000
`

Sometimes shows art, but wrong
![Captura de tela de 2020-05-07 17-52-56](https://user-images.githubusercontent.com/17401812/81343618-b1704400-908b-11ea-99d4-a66d65fc8250.png)

**Comment by fenryxo** [comment]
Hello @FastOSlinux, thanks for reporting the issue. It seems that GNOME MPRIS applet is also affected.

**Comment by FastOSlinux** [comment]
it's working now..thanks anyway!
