### ISSUE TITLE
Wrong song data when Deezer is switched to Queue view 

### ISSUE THREAD

**Issue by 3rgo** [tiliado/nuvolaruntime#609]
### Basic information

- Your Linux distribution and its version: Ubuntu 18.04
- Your desktop environment: GNOME
- Nuvola Runtime version: 4.16.36 (36-gb24246c)
- The web app you use and its version: Deezer 3.2.0 (0-gb04e220)

### Describe the bug

When listening to Deezer Flow, the "song starting" notification will not show the correct song (always displays the first song chosen by Deezer Flow).
The "currently playing song" in GNOME Notification center displays "Unknown title" & "Unknown artist", and the covert art is sometimes wrong (not all the time)

**Steps to reproduce the behavior**

1. Open deezer
2. Start deezer flow (not a playlist or album where the play queue is predetermined)
3. Put the window to the background and change song using a shortcut => See bug in notifications
4. Open the GNOME notification center => See bug in notification center

**Expected behavior**

The "song starting" notifications and the "currently playing" information in notification center should show the correct data

**Debugging log**

[nuvola.deezer.log.txt](https://github.com/tiliado/nuvolaruntime/files/4676732/nuvola.deezer.log.txt)
[nuvola.log.txt](https://github.com/tiliado/nuvolaruntime/files/4676733/nuvola.log.txt)

**Screenshots**

![image](https://user-images.githubusercontent.com/437847/82804042-d33a3b00-9e81-11ea-8f43-b24bf3fdd1ec.png)

![image](https://user-images.githubusercontent.com/437847/82804336-62dfe980-9e82-11ea-9c55-c5226409d44c.png)

**Comment by fenryxo** [comment]
Thanks for your bug report.

**Comment by 3rgo** [comment]
It appears that the bug is no longer present on my machine. I've done flatpak updates, but Nuvola runtime and Deezer script versions are unchanged from the ones on the bug report.
I've purchased a premium license if that changes anything (although I doubt it, since I was using the free premium trial at the time of my report). I'm thinking it's more likely something changed on Deezer's end...

**Comment by fenryxo** [comment]
I hope to look at it at the weekend.

**Comment by fenryxo** [comment]
It actually isn't related to Deezer flow. It happens every time Deezer is switched to *queue* view.

**Comment by fenryxo** [comment]
It should be now fixed in Nuvola 4.16.42 / Deezer 3.2.1.
