### ISSUE TITLE
Add support for Primephonic

### ISSUE THREAD

**Issue by rwnobrega** [tiliado/nuvolaruntime#610]
Could you please add support for the music streaming service [Primephonic](https://www.primephonic.com/)?

**Comment by fenryxo** [comment]
Hello @rwnobrega. Thanks for your suggestion about a new streaming service.

**Comment by fenryxo** [comment]
The initial release has been published and will be announced with Nuvola 4.17. See [installation instructions](https://nuvola.tiliado.eu/app/primephonic/).
