### ISSUE TITLE
Nuvola apps no longer open on Ubuntu 18.04

### ISSUE THREAD

**Issue by BenPhillipsBMLL** [tiliado/nuvolaruntime#614]
- Your desktop environment: ...
 Gnome

 - Nuvola Runtime version: ...
 Flatpak 1.0.9

 - The web app you use and its version: ...
   I tried opening Google Calendar and Nuvola App Store. None open.

### Describe the bug

Hangs on opening. The mouse carot turns into a loading wheel for a while then stops (and nothing further happens).

**Steps to reproduce the behavior**
1. Try open google calendar or nuvola app store

**Expected behavior**
the apps should open

**Debugging log**

I don't know how to debug. In the provided help link (https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#debugging-output) I don't know how to resolve NuvolaAppXXX (as I just open apps in Gnome).

**Comment by fenryxo** [comment]
Hello @BenPhillipsBMLL, the instructions for obtaining the debugging log certainly need improvement. You can list the flatpaks with `flatpak remote-ls --app nuvola`:

```
$ flatpak remote-ls --app nuvola
Name                                     Application ID                                Version       Branch
Nuvola                                   eu.tiliado.Nuvola                                           master
Nuvola Apps Service                      eu.tiliado.Nuvola                                           stable
NuvolaAdk                                eu.tiliado.NuvolaAdk                                        master
NuvolaAdk                                eu.tiliado.NuvolaAdk                                        stable
NuvolaApp8tracks                         eu.tiliado.NuvolaApp8tracks                                 master
8tracks • Nuvola App                     eu.tiliado.NuvolaApp8tracks                                 stable
NuvolaAppAmazonCloudPlayer               eu.tiliado.NuvolaAppAmazonCloudPlayer                       master
Amazon Cloud Player • Nuvola App         eu.tiliado.NuvolaAppAmazonCloudPlayer                       stable
...
NuvolaAppGoogleCalendar                  eu.tiliado.NuvolaAppGoogleCalendar                          master
Google Calendar • Nuvola App             eu.tiliado.NuvolaAppGoogleCalendar                          stable
...
```

Could you obtain the logs for `eu.tiliado.NuvolaAppGoogleCalendar`? Thanks :-)

**Comment by fenryxo** [comment]
Closing as no logs have been provided.
