### ISSUE TITLE
Youtube Music Cannot Logout

### ISSUE THREAD

**Issue by rcandelu** [tiliado/nuvolaruntime#616]
Hi, I cannot logout from youtube music. When I select Sign-Out button from application it opened with default browser (in my case Firefox) 
![Screenshot_1](https://user-images.githubusercontent.com/2798944/85532532-123de680-b610-11ea-92b6-5456d2cb1f6a.jpg)

**Comment by fenryxo** [comment]
Hello @rcandelu, thanks for your bug report.

**Comment by fenryxo** [comment]
Nuvola has a feature to open external links in a web browser instead of in Nuvola. It also keeps a list of URL patterns to always open in Nuvola rather in a web browser. I need to add a new pattern for `https://accounts.google.com/Logout?continue=https%3A%2F%2Fmusic.youtube.com%2F&service=youtube`.

**Comment by fenryxo** [comment]
It should be now fixed in Nuvola 4.16.42.
