### ISSUE TITLE
Add ListenBrainz scrobbling support

### ISSUE THREAD

**Issue by theli-ua** [tiliado/nuvolaruntime#617]
https://listenbrainz.readthedocs.io/en/production/

There is even a Last.fm compatible API so should be just possible to reuse most of existing code.

**Comment by fenryxo** [comment]
Hello @theli-ua, thanks for your feature request. Although the top priority for the year 2020 is #583, I might manage to add ListenBrainz scrobbling if there are no issues with its Last.fm compatible API.

**Comment by fenryxo** [comment]
Available in Nuvola 4.16.48 (48-g05e2d30). Fresh flatpak packages have been published. The feature will be officially announced with Nuvola 4.17. Thanks for improving Nuvola by submitting your feature request :-)
