### ISSUE TITLE
MPRIS2 integration and Multimedia keys stopped working with Qobuz

### ISSUE THREAD

**Issue by bpresles** [tiliado/nuvolaruntime#619]
### Basic information

- Your Linux distribution and its version: Ubuntu 18.04 LTS.

- Your desktop environment: GNOME 3.28.2

- Nuvola version:

Nuvola Runtime version: 4.16.36
Nuvola Qobuz Script version: 1.2.0

 - The web app you use and its version:

Nuvola Qobuz Script: 1.2.0
Qobuz web player version: 5.6.2-b016

### Describe the bug

Since a few weeks I noticed that MPRIS2 integration stopped working with Qobuz as you can see on the screenshot below.

Also Multimedia keys and actions in Nuvola menu don't work.

**Steps to reproduce the behavior**

1. Install Nuvola Runtime and Nuvola Qobuz script
2. Login in the Qobuz web player within Nuvola Runtime
3. Play a song

**Expected behavior**

- Song name and album art should be visible in GNOME notification zone
- Actions from Nuvola menu for Play/Pause, Previous song, Next song should work
- Multimedia keys should work

**Screenshots**

![image](https://user-images.githubusercontent.com/220623/86591544-14019580-bf92-11ea-8cb3-c48656ea1dbc.png)

**Additional context**

I also opened a bug report on Qobuz Script repository: tiliado/nuvola-app-qobuz#6

**Comment by fenryxo** [comment]
Hello @bpresles, thanks for your bug report.

**Comment by fenryxo** [comment]
I regret to say that Qobuz app is currently unsupported until a new maintainer is found as I don't have access to the service. More details in #634.

**Comment by fenryxo** [comment]
We have a new maintainer :tada:  If the issue still persists in **Quobuz 1.2.9 (9-g3ddd68a)**, please create a new bug report referencing this issue.
