### ISSUE TITLE
prevent screensaver while tv is active

### ISSUE THREAD

**Issue by ivostoykov** [tiliado/nuvolaruntime#625]
Hi, I'm using iPlayer on Ubuntu desktop 18.04 (latest and patched) and noticed that screensaver activates after the set time regardless of TV is active and playing. I failed to find any preferences where I could prevent this. Any suggestions?

Thank you.
Ivo

**Comment by a-m-s** [comment]
Assuming you're using the default GNOME-based desktop, install the [Caffeine extension](https://extensions.gnome.org/extension/517/caffeine/). Then Gnome will automatically disable the screensaver whenever any app is displayed in full-screen mode. To disable the screensaver at any other time simply click the "cup" icon in the top bar, and click it again when you're done.

This is the normal GNOME solution to this problem.

**Comment by ivostoykov** [comment]
Thank you for the fast reply. I did already, but though there might be some settings in the app somewhere.
I noticed youtube has a similar feature and assumed iPlayer might have as well, hidden somewhere. Cheers.

**Comment by a-m-s** [comment]
YouTube has that? Where?

**Comment by ivostoykov** [comment]
I see it when I'm playing something on youtube using Chrome on Ubuntu (all latest)... It seems to prevent the screensaver from starting, but has other issues ;-)

**Comment by a-m-s** [comment]
Oh, I thought you meant the Nuvola YouTube app.

**Comment by fenryxo** [comment]
Hello @ivostoykov, thanks for your feature request. I hope it will be possible once Nuvola is ported to QtWebEngine (#583). Anyway, I'm closing this issue in favor of #503.
