### ISSUE TITLE
Features requested for Qobuz app

### ISSUE THREAD

**Issue by chrisabbeytx** [tiliado/nuvolaruntime#628]
I would like three improvements:

    A dark theme

    Volume normalization

    Seamless transitions from track to track

I am otherwise very happy with the app.  Thank you!

**Comment by fenryxo** [comment]
Hello @chrisabbeytx. Thanks for your ideas.

> A dark theme

Nuvola does support [dark themes](https://nuvola.tiliado.eu/docs/4/appearance.html#dark-theme). Or do you mean a dark theme of the Qobuz web app?

> Volume normalization

Not sure whether it is possible.

> Seamless transitions from track to track

It isn't possible to do that in Nuvola. This must be done by Qobuz developers.

**Comment by fenryxo** [comment]
Closing as no response has been received.
