### ISSUE TITLE
Can't install Nuvola Services Pop_OS!

### ISSUE THREAD

**Issue by aia832003** [tiliado/nuvolaruntime#630]
I'm getting the below when using Pop_OS!. The system has Flathub enable and allows for the Nuvola repo to be added, but then fails to move forward on dependencies.

andrewallen@pop-os:~$ sudo apt install flatpak xdg-desktop-portal-gtk gnome-software-plugin-flatpak
[sudo] password for andrewallen: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xdg-desktop-portal-gtk is already the newest version (1.6.0-1build1).
xdg-desktop-portal-gtk set to manually installed.
flatpak is already the newest version (1.6.5-0ubuntu0.1).
flatpak set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gnome-software-plugin-flatpak : Depends: gnome-software (= 3.36.1-0ubuntu0.20.04.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
andrewallen@pop-os:~$ flatpak remote-add --if-not-exists nuvola https://dl.tiliado.eu/flatpak/nuvola.flatpakrepo
andrewallen@pop-os:~$ flatpak install nuvola eu.tiliado.Nuvola
Looking for matches…
error: The application eu.tiliado.Nuvola/x86_64/stable requires the runtime org.gnome.Platform/x86_64/3.34 which was not found

**Comment by fenryxo** [comment]
Hello @aia832003,

Are you sure flathub repo is enabled?

```
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
```

**Comment by aia832003** [comment]
Well... maybe it wasn't. That worked. Thanks Jiri!

**Comment by fenryxo** [comment]
Glad to help :-)
