### ISSUE TITLE
Upgrade to org.gnome.Platform/x86_64/3.36

### ISSUE THREAD

**Issue by miostreams** [tiliado/nuvolaruntime#632]
On Ubuntu 20.04, updating flatpak results in the error:

`Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.`

I have version 3.36 installed, but attempting to remove 3.34 results in this error:

`Error: Can't remove org.gnome.Platform/x86_64/3.34, it is needed for: eu.tiliado.Nuvola/x86_64/stable, eu.tiliado.NuvolaAppAmazonCloudPlayer/x86_64/stable, eu.tiliado.NuvolaAppPlex/x86_64/stable`

Is there some other method of updating the Nuvola apps, so that they are not requiring an EoL version of Gnome platform?

**Comment by fenryxo** [comment]
Hello @miostreams, Nuvola needs to be rebuilt with GNOME SDK 3.36. I'll look at it at the weekend.

**Comment by miostreams** [comment]
Awesome! Thank you!

**Comment by fenryxo** [comment]
New packages have been published. Thanks for creating this issue :-)

**Comment by miostreams** [comment]
Awesome, thank you!
