### ISSUE TITLE
New maintainer for Qobuz is needed

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaruntime#634]
The original maintainer lost interest in Qobuz. I tried to take over but I can't. Qobuz is not available in my country and implements very strict geographic checks.

1. Geolocation according to IP address - I connected via a VPN service to Paris in France
2. ZIP code - I managed to find a correct Paris ZIP code
3. Payment card country - I don't have a Frech payment card

**Comment by fenryxo** [comment]
@Romunix, if you want to take over maintainership of Qobuz, please create a new PR in tiliado/nuvola-app-qobuz:

1. Replace `Quobuz is unsupported ...` with `New maintainer <name>. Issue: tiliado/nuvolaruntime#634` in `CHANGELOG.md`.
2. Update `maintainer_name` and `maintainer_link` in `metadata.in.json`.
3. Create a commit with this message:

```
New maintainer

Issue: tiliado/nuvolaruntime#634
```

**Comment by fenryxo** [comment]
* Quobuz 1.2.9 (9-g3ddd68a) packages published.
* Qobuz 1.3.0 will be released with Nuvola 4.18.0.
* I need to update the website to include the new maintainer.

**Comment by fenryxo** [comment]
@Romunix, welcome aboard :-) You should receive an invitation to join Tiliado organization on GitHub with commit access to qobuz repository and a free license key (e-mail from support@tiliado.eu).

**Comment by Romunix** [comment]
yes, all received :-)

**Comment by fenryxo** [comment]
https://nuvola.tiliado.eu/team/ & https://nuvola.tiliado.eu/index/ updated.
