### ISSUE TITLE
Amazon streaming quality

### ISSUE THREAD

**Issue by jason-a69** [tiliado/nuvolaruntime#639]
Hi there,

What quality does the Amazon Cloud Player stream music at? Will it go to HD / Ultra HD flacs if the hardware supports it (with an external DAC).

Many thanks

Jason

**Comment by a-m-s** [comment]
The web player used in Nuvola supports "High", "Medium", and "Low" quality, with the default being "Auto". It is not specified what this actually means.

Amazon does offer a subscription service named "Amazon Music HD", but you need to use one of the official clients for that (their help page explicitly notes that the web player is not supported).
