### ISSUE TITLE
MPRIS2 integration and Multimedia keys stopped working with Qobuz

### ISSUE THREAD

**Issue by bpresles** [tiliado/nuvolaruntime#640]
**Basic information**

Your Linux distribution and its version: Ubuntu 18.04 LTS.

Your desktop environment: GNOME 3.28.2

**Nuvola version:**

Nuvola Runtime version: 4.16.36
Nuvola Qobuz Script version: 1.2.0

The web app you use and its version:
Nuvola Qobuz Script: 1.2.0
Qobuz web player version: 5.6.2-b016

**Describe the bug**

Since a few weeks I noticed that MPRIS2 integration stopped working with Qobuz as you can see on the screenshot below.

Also Multimedia keys and actions in Nuvola menu don't work.

**Steps to reproduce the behavior**

Install Nuvola Runtime and Nuvola Qobuz script
Login in the Qobuz web player within Nuvola Runtime
Play a song
Expected behavior

Song name and album art should be visible in GNOME notification zone
Actions from Nuvola menu for Play/Pause, Previous song, Next song should work
Multimedia keys should work

See screenshot on #619

**Comment by fenryxo** [comment]
Hello @bpresles, could you upgrade to **Quobuz 1.2.9 (9-g3ddd68a)** and try again?

**Comment by bpresles** [comment]
It works indeed with 1.2.9 version. Thank you!

I close the issue :)
