### ISSUE TITLE
Script Reguest: Gaana

### ISSUE THREAD

**Issue by ssreddy555** [tiliado/nuvolaruntime#644]
Homepage: https://gaana.com/

**Comment by fenryxo** [comment]
Hello @ssreddy555. We occasionally add new services from [the backlog](https://github.com/tiliado/nuvolaruntime/labels/type%3A%20script%20request) but there is no plan when to add service XYZ, etc.

**Comment by fenryxo** [comment]
Gaana is ready :rocket:

* Installation: https://nuvola.tiliado.eu/app/gaana/
* Repository: https://github.com/tiliado/nuvola-app-gaana
