### ISSUE TITLE
Support For Apple Music

### ISSUE THREAD

**Issue by dlalinsp** [tiliado/nuvolaruntime#645]
**Is your feature request related to a problem? Please describe:**
Apple Music isn't available on Nuvola.

**Describe the solution you'd like:**
Provide support for Apple Music. It is one of the most popular streaming services so it would be great to have it here.

Homepage: https://www.apple.com/apple-music/

**Comment by fenryxo** [comment]
Hello @dlalinsp. Thanks for your script request.

**Comment by fenryxo** [comment]
Published :+1: 

* Installation instructions: https://nuvola.tiliado.eu/app/pocket_casts/
* Repository: https://github.com/tiliado/nuvola-app-apple-music

**Comment by ericandrer** [comment]
> Published +1
> 
>     * Installation instructions: https://nuvola.tiliado.eu/app/apple_music/
> 
>     * Repository: https://github.com/tiliado/nuvola-app-apple-music

I'm not able to reproduce any script installation for apple music as there is 404 response at https://nuvola.tiliado.eu/app/apple_music/ Was it discontinued ?

**Comment by fenryxo** [comment]
Hello @ericandrer, Apple Music support was discontinued because of #730.
