### ISSUE TITLE
youtube music installation problem

### ISSUE THREAD

**Issue by devangbairwa** [tiliado/nuvolaruntime#654]
hello sir,
when i try to install youtube music from terminal some failed message occur.
please help to resolve it and install youtube music.
![Screenshot from 2020-10-19 15-51-49](https://user-images.githubusercontent.com/68903171/96434950-322e9100-1223-11eb-8cd5-3cd71e8addac.png)

**Comment by fenryxo** [comment]
Hello @devangbairwa, thanks for reporting the issue. Could you try again and  record the exact time in UTC timezone? I'll look at the logs to see if there is any hint.

**Comment by fenryxo** [comment]
Closing in favor of #653.
