### ISSUE TITLE
Support HTTP(S) Proxy with Authentification

### ISSUE THREAD

**Issue by Auze** [tiliado/nuvolaruntime#66]
Tasks:
- [ ] Install and set up HTTP(S) proxy with Authentification.
- [ ] How does Nuvola Player 3 behave?
- [ ] Does glib/gio proxy resolver support HTTP(S) proxy with Authentification?
- [ ] Is it possible to use environment variables?

Original report:

> Request support  for Proxy with authentification (HTTP/HTTPS ?) or use Network-Manager or /etc/environnement variables. 
##

**Comment by fenryxo** [comment]
Hello @Auze. Is this still an issue in Nuvola 4.x? Thanks.

**Comment by fenryxo** [comment]
Closing because there has been no response from the reporter over a month. Feel free to reopen this issue if it still persist.
