### ISSUE TITLE
Read activation code / license from config file

### ISSUE THREAD

**Issue by mzuther** [tiliado/nuvolaruntime#661]
**Is your feature request related to a problem? Please describe:**

When I lately updated my flatpak installation, both nuvola apps I use (Deezer and DI.FM) "forgot" my life-time premium license.

**Describe the solution you'd like:**

When an app is activated, write the activation code to a file like `"$XDG_CONFIG_HOME/nuvola/activation.txt" (`$XDG_CONFIG_HOME` defaults to `"$HOME/.config"`). Alternatively, you could offer downloadable license files, but as users don't read instructions, writing the file inside the app will probably help you keeping your sanity... :smile: 

Before asking users to enter their activation code, check the above file first (you could still validate licenses using a server, of course). This would be much less hassle for users, as they'll only have to enter the license once and it won't be overwritten on updates.

**Describe alternatives you've considered:**

Licenses in the config folder (or, slightly worse, the home directory) are some sort of standard on Linux systems.

Thanks!

**Comment by fenryxo** [comment]
Hello @mzuther, Nuvola already stores license keys in  `~/.var/app/eu.tiliado.Nuvola*/config/`. Did you remove this directory when you updated your Flatpak installation?

**Comment by mzuther** [comment]
You are absolutely right, there is a file `~/.var/app/eu.tiliado.Nuvola/config/nuvolaruntime/master/config.json`. However, I definitely had to re-enter my license data. Weird!

Shall we close this issue and I'll re-open it in case the problem occurs again?

**Comment by fenryxo** [comment]
Sure, reopen it if the issue appears again.

**Comment by fenryxo** [comment]
Actually, it probably happened because of this from #658:

> Accept the warning about version mismatch (the problem occurred with the former version, too)

1. If Nuvola Service is available, the license key is stored there and used by all Nuvola apps. Any locally stored license information is ignored because Nuvola Service is the ultimate source of truth.
2. If Nuvola Service is not available, each app stores the license information individually as the global storage cannot be reached.

You probably started at 2 and was asked to enter the license when you updated Nuvola Service and it became available.

**Comment by mzuther** [comment]
You are absolutely right! The differentiation between Nuvola Service and Apps is slightly confusing, but I know that you're working on it.

Good luck with that! :)
