### ISSUE TITLE
Amazon Music: I can't use the widget on the notification section

### ISSUE THREAD

**Issue by rpayanm** [tiliado/nuvolaruntime#670]
### Basic information

- Your Linux distribution and its version: Pop!_OS 20.10

- Your desktop environment: GNOME 3.38.1

 - Nuvola Runtime version: 4.17.8 (8-g7524f64)

 - The web app you use and its version: Amazon Cloud Player script 5.10.0 (0-g29a57d1)

### Describe the bug

I can't use the widget on the notification section:

**Steps to reproduce the behavior**

1. Open the app.
2. Try to click on the play button or other buttons, none of them work. The Artist and Song title aren't showing.

**Expected behavior**
Oposite of above.

**Screenshots**

Attach screenshots here:
![image](https://user-images.githubusercontent.com/6087454/97722213-c52bbe80-1aa0-11eb-8e76-fab0ee6e1f9c.png)

Video:
https://gofile.io/d/g0VREq

**Comment by fenryxo** [comment]
Hello @rpayanm. Thanks for reporting the issue. We track it here: #656
