### ISSUE TITLE
Service Request: music.163.com

### ISSUE THREAD

**Issue by lgaticaq** [tiliado/nuvolaruntime#95]
This future plans to integrate the service http://music.163.com/?

**Comment by fenryxo** [comment]
Hello. Nobody has expressed a serious interest to have this streaming service in Nuvola Player so far.  Are you interested in becoming a patron of this web app integration script by supporting the development of the script financially?

---
Jiri Janousek, Nuvola Player Developer • My work on Nuvola Player and user support are [funded by Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/).

**Comment by fenryxo** [comment]
This ticket has been added to the list of [postponed feature requests](https://github.com/tiliado/nuvolaplayer/labels/postponed). I hope to start working on these tickets when [project funding](https://tiliado.eu/nuvolaplayer/funding/) gets better.

**Comment by fenryxo** [comment]
This ticket is ancient and I'm not sure whether it is still relevant. If anybody is interested in this service, please create a new ticket :+1:
